### ISSUE TITLE
SELECT returns no rows

### ISSUE THREAD

**Issue by phillipCouto** [denisenkom/go-mssqldb#100]
Hi Guys,

So I have encountered an interesting issue.

I executed a SELECT \* FROM Table query in mac and linux and I get all the records from the table.

When I execute the same query on windows rows.Next() returns false but there are no errors.

After some testing I found out it was because I had the server name as an FDQN. When in a windows machine that is joined to a domain go-mssql needs the server just to be the host name and not a FQDN.

The part that was weird was no error was returned.

I am not sure if this is expected behaviour. 

Also I tested with using windows Single Sign on or providing credentials and it still has issues with FQDN.

**Comment by HeyImAlex** [comment]
I had a similar issue on a long running script last night. A bunch of workers consuming from a channel. At some point a bunch of my workers log `WSARecv tcp <host>:<port>: i/o timeout`. Ok network problem, maybe the connection died, whatever.

However, from that point forward all of those workers show a "no records found" error, which would only be displayed when the select _succeeded_ but `rows.Next()` returned false on the first iteration. I probably should have been pinging the database every time I consumed from the channel, but I would still expect `Query` to return an error if it's not actually able to query.

For me it seems like it was triggered by a network issue; while it's running on Windows and uses an (intranet) FQDN, the select was working fine for many hours before. Let me know if you want any more details!

**Comment by denisenkom** [comment]
Try latest version, it has some improvements in logging errors.
Run it with logging enabled and post logs here.

**Comment by haochun** [comment]
@phillipCouto @denisenkom i also encountered the same problem .but,it not return NoRows every time.sometimes return result.my code:

func getSQLConn(databaseUri string) (*sql.DB , error) {
	sqlLock.Lock()
	defer sqlLock.Unlock()
	
	if conn,ok := connections[databaseUri]; !ok {
		conn, err := sql.Open("mssql", fmt.Sprintf(connectUri, databaseUri))
		if err != nil {
			return nil, err
		}
		conn.SetMaxOpenConns(config.EveryDBConnectionSize)
		conn.SetMaxIdleConns(config.EveryDBConnectionSize)
		connections[databaseUri] = conn
		return conn, nil
	} else {
		return conn, nil
	}
}

func rowsCount(conn *sql.DB,task string) (int64, error){
	var count int64
	err := conn.QueryRow(fmt.Sprintf(countSQL, task, task)).Scan(&count)
	
	if err != nil && err == sql.ErrNoRows {
		return 0,nil
	}
	
	if err != nil {
		fmt.Printf("count query error:%s    info:%s\n",task, err.Error())
		return 0,err
	}
	
	return count,nil
}

i want to know it is the bug of golang,or the bug of this driver.

**Comment by bradleyankrom** [comment]
@haochun Are you still seeing inconsistent results when running the count query? If so, can you copy and paste the errors you're receiving?

**Comment by haochun** [comment]
@bradleyankrom sometimes it also return 0.but i does not log the error into file.I think it should be too frequent statistics

**Comment by blitzd** [comment]
This may be related to this issue:

https://github.com/denisenkom/go-mssqldb/issues/105

I get 'no results' from any query on any server when I use a short name or FQDN to connect. Using an IP address works.

**Comment by denisenkom** [comment]
try log=63

**Comment by kardianos** [comment]
Timeout. If this is still an issue please open a new issue.
