### ISSUE TITLE
issue with long string-numbers in queries

### ISSUE THREAD

**Issue by brenol** [denisenkom/go-mssqldb#101]
Hi,

I'm having issues with querying while passing a 10 numbers varchar to the select.

I have set the log level @63 and it just keeps printing:
```sql
select * from table where phone = ?;
@p1 = 33219894564621
```

The code that is making me able to reproduce this is the following:
```golang
sql := "select * from users where phone = ?"
number := "33219894564621"
rows, _ := db.Query(sql, number)
```

I believe it simply keeps timing out, as every 30 seconds if shows the select again. (Changing the connection timeout to another value also made me notice this)

**Comment by denisenkom** [comment]
Hi.
I've improved logging, can you run latest version and upload log output again?

**Comment by brenol** [comment]
Hello!

Thanks for the quick answer.

I tried again with the new logging features but did not see a difference:

```log
2015/05/18 11:04:37 select * from users where number = @p1
2015/05/18 11:04:37 	@p1 33219894564621
2015/05/18 11:04:42 select * from users where number = @p1
2015/05/18 11:04:42	@p1 33219894564621
```
(I have connection timeout set to 5 seconds, also, I used db.Exec())

Also, note that I found a 'quick fix' to this problem using the CAST syntax:
```golang
sql := "select * from users where phone = CAST(? as varchar(max))"
number := "33219894564621"
rows, _ := db.Query(sql, number)
```

And it's now returning rows as expected, however, I find it very strange that the common syntax just _hangs_ while querying.

**Comment by denisenkom** [comment]
I think the problem in your case was that your query wasn't optimal, and that was causing timeouts.
By default go-mssql will use nvarchar type for strings.  and you phone column is probably of type varchar.  That mismatch causes sql server to not to use index and instead do full table scan.
You can reproduce that by running query following query in query analyzer:

select * from users where phone = N'33219894564621'

You can also enable execution plan to see what is going on.

**Comment by denisenkom** [comment]
so the solution is to use cast as you did, or to change type of column to nvarchar

**Comment by brenol** [comment]
I see - however, I forgot to mention the fact that it only _hangs_ when I pass the _number_ as args to ...interface{} that Query() accepts.

If I do it like this:
```golang
number := "33219894564621"
sql := fmt.Sprintf("select * from users where number = %s", number)
rows, _ := db.Query(sql)
```
instead of
```golang
number := "33219894564621"
sql := fmt.Sprintf("select * from users where number = ?")
rows, _ := db.Query(sql, number)
```
... the first case does not hang. If the reason is because it's converting to nvarchar then it makes sense.

Thanks!

**Comment by denisenkom** [comment]
In first case you will have:

select * from users where number = 33219894564621

in second:

select * from users where number = N'33219894564621'

**Comment by denisenkom** [comment]
That should work fast:
```
number := 33219894564621
sql := fmt.Sprintf("select * from users where number = ?")
rows, _ := db.Query(sql, number)
```

**Comment by brenol** [comment]
Great, thank you for all your help!
