### ISSUE TITLE
get "invalid domain name" error when connection db on centos6.6

### ISSUE THREAD

**Issue by sdhjl2000** [denisenkom/go-mssqldb#102]
OS:centos6.6
ARCH:amd64
this lib works well on my local windows and  ubuntu machine ,but after i  cross compile the source code and deploy to a centos(6.6/amd64) machine i got a  "invalid domain name" error,but if i change etc/hosts use alias name it works well,i search the lib‘s source and don't find any function return this error.any suggestion.

**Comment by sdhjl2000** [comment]
```go
package main

import "fmt"
import "net"

func main() {
	ips, err := net.LookupIP("192.168.102.227")
	if err != nil {
		fmt.Println(err.Error())
	}
	for _, ip := range ips {
		fmt.Println(ip)
	}

}
```
after dig into the source code find the error occur when lookup the ipaddress, if just use go run test this code it works well,but if cross compile it and deploy to the target get the invalid domain name error.

**Comment by sdhjl2000** [comment]
after install a new centos virtual machine with same arch,i  compile the source code and deploy to the target it works ok,there must be some problem with cross compile.

**Comment by denisenkom** [comment]
Maybe cross compiler has a bug?

**Comment by dimdin** [comment]
Go cross compiler compiles with the CGO disabled. That means that go net library does not call the C OS API for resolving the ip; go tries to resolve the ip by using the hosts file.
When you compile natively CGO is enabled and the proper OS resolver is called.

**Comment by sdhjl2000** [comment]
@dimdin ,3ks,i will try
