### ISSUE TITLE
Login error: EOF from windows machine + azure v12 only

### ISSUE THREAD

**Issue by chadkouse** [denisenkom/go-mssqldb#103]
This is strange...

My code works fine from my development machine (mac) - even pointed at the production sql server - but when I compile it for windows amd64 and run it from that machine I get
`Login error: EOF`
After any query.  The SQL instance is a v12 azure database.  Other applications on this windows machine are able to query the database so I know it's not a firewall issue.

Also the code seems to work with an older v2 database.

How can I help debug this?

**Comment by colorcyan** [comment]
getting exactly same problem.
SQL Server is Azure v12, go program runs on my mac, runs on my windows, deployed to a windows VM on Azure, got this `Login error: EOF` immediately. That server has other (.net and node) services running fine with same database.

**Comment by denisenkom** [comment]
Did you look at this: https://github.com/denisenkom/go-mssqldb#known-issues
?

**Comment by chadkouse** [comment]
yes I don’t think this is the issue though since azure v12 claims to be
closer to sql 2014

https://azure.microsoft.com/en-us/documentation/articles/sql-database-v12-whats-new/

On Fri, Jun 26, 2015, 8:29 PM denisenkom <notifications@github.com> wrote:

> Did you look at this:
> https://github.com/denisenkom/go-mssqldb#known-issues
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/denisenkom/go-mssqldb/issues/103#issuecomment-115924333>
> .
>
-- 

--chad

**Comment by denisenkom** [comment]
Maybe your windows machine has version of go that is older than the version of go on your mac?
If they are the same please enable logging and upload logs here.

**Comment by chadkouse** [comment]
Well I tried turning on logging in the connection string.. but I don't know where the logs go?  (This is running as a service on windows)

**Comment by michaelbironneau** [comment]
Same problem on both Windows 7 and Ubuntu 14.04 running either Go 1.5 or Go 1.6.2. Is there any resolution for this that doesn't involve downgrading the SQL database from v12 to v2?

**Comment by michaelbironneau** [comment]
OK, it seems the problem has somthing to do with ENVCHANGE. In SQL Server Management Studio you get an error when switching database from the dropdown, but it ignores it and moves on. This is probably the same issue. The workaround, it seems it to **not** specify a database name in the connection string - at least this works for me.

**Comment by michaelbironneau** [comment]
Right - think I found the issue. Some code was panicking because of an EOF that could be safely ignored. Sent you a PR.

**Comment by denisenkom** [comment]
Please test latest version and resolve this issue if it works

**Comment by kardianos** [comment]
Timed out.
