### ISSUE TITLE
Custom logger

### ISSUE THREAD

**Issue by polarina** [denisenkom/go-mssqldb#108]
Is it possible to pass a custom logger from the "log" package for the library to use?

I am executing against multiple databases concurrently and I need to capture the logs from each one without mixing them together.

**Comment by dimdin** [comment]
SetLogger driver method can be used to set a custom logger. There is no way to set a different logger for different driver connections.

**Comment by polarina** [comment]
Hah! Forgot to close this issue along with #110. I can set a custom logger per connection by bypassing the `database/sql` abstraction, which is what I'm doing.
