### ISSUE TITLE
Connect to instance

### ISSUE THREAD

**Issue by busterwood** [denisenkom/go-mssqldb#115]
How would I specify the instance name to connect to?  We have a single server with multiple instances of SQL Server on it.

**Comment by BrianActon** [comment]
Still experimenting myself but I think this is what you might be looking for.

dsn := "server=" + "SERVER//INSTANCE_NAME" + ";user id=" + "xxx" + ";password=" + "xnnn" + ";database=" + "db_name"
	db, err := sql.Open("mssql", dsn)

**Comment by denisenkom** [comment]
see https://github.com/denisenkom/go-mssqldb#connection-parameters
