### ISSUE TITLE
Decimal results into an []uint8

### ISSUE THREAD

**Issue by juRiii** [denisenkom/go-mssqldb#116]
hi, i have a question about a mssql column with this type `decimal(18, 6)`

    rows.Scan(vals...)

this results in a value of type `[]uint8`

how should someone deal with this?

**Comment by dimdin** [comment]
You can cast it to a string and use it as a string.

I have a library for handling decimal numbers see https://github.com/dimdin/decimal
just declare something as decimal.Dec and you can scan it.
(the library trick is the Scanner/Value interfaces implementation)
