### ISSUE TITLE
Connection left in bad state after a timeout

### ISSUE THREAD

**Issue by FireArrow** [denisenkom/go-mssqldb#119]
I have an issue where my connection is left in a bad state after a timeout or a very slow answer. 

Here's a paste of my log, with log level set to 63. To explain a little what you see;
One "query" is really two queries, first one to mymeta (called the meta query from now on), and given the response from that one to mydata.response (called the data query from now on). The expected result from mymeta is {string, int}, and expected result from mydata is {timestamp, float}
All the queries below are the same queries over and over.
The server is an MSSQL 2012
The names and conditions are fake, but the log is copied from real executions. There's nothing fancy going on in the real query.

First query. Meta query already executed with no problem. Log left out as this is long as it is:

```
2015/08/19 10:06:59 Querying data from hour
2015/08/19 10:06:59 SELECT ts, col FROM mydata.hour WHERE id = @p1 AND ts BETWEEN @p2 AND @p3
2015/08/19 10:06:59     @p1 10305
2015/08/19 10:06:59     @p2 2015-07-11 00:00:00 +0000 UTC
2015/08/19 10:06:59     @p3 2015-08-12 00:00:00 +0000 UTC
2015/08/19 10:07:29 SELECT ts, col FROM mydata.hour WHERE id = @p1 AND ts BETWEEN @p2 AND @p3
2015/08/19 10:07:29     @p1 10305
2015/08/19 10:07:29     @p2 2015-07-11 00:00:00 +0000 UTC
2015/08/19 10:07:29     @p3 2015-08-12 00:00:00 +0000 UTC
2015/08/19 10:08:25 Error when fetching data: read tcp mymssqlserver:1433: i/o timeout
```

Second query. Fails on meta query:

```
2015/08/19 10:08:53 SELECT f1,f2 FROM mymeta WHERE conditions = 1
2015/08/19 10:08:53 Error when fetching data: Error while finding finest aggregation level: Error when finding finest agg: mssql.StreamError=Invalid TDS stream: Unknown token type: 122
```

Third query. Fails on meta query:

```
2015/08/19 10:10:33 SELECT f1,f2 FROM mymeta WHERE conditions = 1
2015/08/19 10:10:33 Error when fetching data: Error while finding finest aggregation level: Error when finding finest agg: mssql.StreamError=Invalid TDS stream: Unknown token type: 101
```

Forth query. Succeeds with meta query. Notice how the raw results here are the expected results from a meta query, but the query was actually a data query:

```
2015/08/19 10:19:38 Querying data from hour
2015/08/19 10:19:38 SELECT dt, S4517B FROM mydata.hour WHERE id = @p1 AND ts BETWEEN @p2 AND @p3
2015/08/19 10:19:38     @p1 10305
2015/08/19 10:19:38     @p2 2015-07-11 00:00:00 +0000 UTC
2015/08/19 10:19:38     @p3 2015-08-12 00:00:00 +0000 UTC
2015/08/19 10:19:38 (3 row(s) affected)
2015/08/19 10:19:38 Problem while scanning query result: sql: Scan error on column index 0: unsupported driver -> Scan pair: string -> *time.Time
[]string{"15min", "15"}
2015/08/19 10:19:38 Problem while scanning query result: sql: Scan error on column index 0: unsupported driver -> Scan pair: string -> *time.Time
[]string{"day", "<nil>"}
2015/08/19 10:19:38 Problem while scanning query result: sql: Scan error on column index 0: unsupported driver -> Scan pair: string -> *time.Time
[]string{"hour", "40"}
```

Can someone please tell me if I am doing something wrong, or if this is a bug in the library?

**Comment by dimdin** [comment]
Please, ensure that Close is called after each query (see the documentation http://golang.org/pkg/database/sql/#Rows.Close)

**Comment by FireArrow** [comment]
It is. After every Query, there is a defer rows.Close()

**Comment by dimdin** [comment]
With defer Close will be executed at the end of the function. If you have the queries in the same function Close is not called between queries. Call rows.Close() without defer after each query.  (There is a great resource for go sql interface http://go-database-sql.org/retrieving.html)

**Comment by FireArrow** [comment]
I updated my comment to cover that case while you wrote your answer. Sorry!
Anyway, my code effectively follows the example given in http://golang.org/pkg/database/sql/#DB.Query
No queries while having an active query, no recursive calls, always defer a Close().
My issue only arise the query after a query times out.

**Comment by dimdin** [comment]
The connection times out from the client side but the server keep sending data.
We need to cancel the query on timeout (see #29)

**Comment by FireArrow** [comment]
I see. So there is nothing I can do about it on the client side (part from setting a high timeout value) until #29 is fixed?

**Comment by dimdin** [comment]
Yes, setting a higher timeout (default timeout is 30 secs) is a good workaround until the bug is fixed.

**Comment by HeyImAlex** [comment]
Same (?) error showed up in some logs yesterday:

```
read tcp 192.168.100.4:56764->172.24.16.119:1433: i/o timeout
sql: no rows in result set
mssql: The server failed to resume the transaction. Desc:d700000018.
mssql: New request is not allowed to start because it should come with valid transaction descriptor.
sql: no rows in result set
The server failed to resume the transaction. Desc:d700000020.
sql: expected 3 destination arguments in Scan, not 1
sql: expected 1 destination arguments in Scan, not 3
sql: expected 3 destination arguments in Scan, not 1
sql: expected 1 destination arguments in Scan, not 3
```

From that point on, those two `sql: expected...` errors repeat up until I restarted the application, at which point everything went back to normal. The end users found that if they clicked submit a few times it would eventually work, about every three clicks.

In my code I'm only calling scan twice for each request, once with three values and once with one. The code is pretty simple, and I've got unit tests verifying it works. So it looks like... they get switched around? Or something...

**Comment by heyimalex** [comment]
This was closed, but I'm experiencing the same error using the latest version; read timeouts and then failed to resume transaction and then scan errors that appear to just be out of order. It's going to be hard to repro but I'll try.

**Comment by denisenkom** [comment]
try again on latest version, it sets TCP keep alive to 30 seconds by default now
