### ISSUE TITLE
Issue with install commandline "go get github.com/denisenkom/go-mssqldb"

### ISSUE THREAD

**Issue by dcampillo** [denisenkom/go-mssqldb#120]
Hi,

This is probably not code related, but when trying to get go-mssqldb using the command "go get github.com/denisenkom/go-mssqldb" from the homepage, I receive a error message : 

import cycle not allowed
package github.com/denisenkom/go-mssqldb
        imports bytes
        imports errors
        imports runtime
        imports unsafe
        imports runtime

Documentation related to this issue are talking of deps issue within the code, which in my opinion is wrong. But I can't figure out of to fix this issue.

Best regards,

David

**Comment by anchepiece** [comment]
What is your GOPATH and GOROOT set to?

**Comment by dcampillo** [comment]
Shame on me, I am still a newbie with Go setup and my path wasn't setup correctly ! 

Thanks for replying.

David
