### ISSUE TITLE
sql server 2005 encryption fails

### ISSUE THREAD

**Issue by scohen28** [denisenkom/go-mssqldb#121]
This just seemed to have started in the pass few days.

I'm connecting to a remote SQL Server (2005) - I have no ability to update (not my db).

// DBConnection connection to the MS SQL database
type DBConnection struct {
    ConnectionStr string
    DB            *sqlx.DB
}

func (d *DBConnection) ConnectDatabase() {
    // connect to SQL Server
    var err error
    fmt.Println(d.ConnectionStr)
    // open the database
    d.DB, err = sqlx.Open("mssql", d.ConnectionStr)
    ErrorCheck(err, "Open connection failed", true)

```
fmt.Println("Pinging...")
// Make sure that the database is available
err = d.DB.Ping()     <=== Error occurs here at Ping
ErrorCheck(err, "Cannot connect", true)
```

}

Error:    Login error:  EOF

The only difference on my end is that I've upgraded to GO 1.5 from 1.4.2

**Comment by dimdin** [comment]
Please post the result of "select @@version"
 For a workaround try to connect with the option "encrypt=disable;"
(related issue #114)

**Comment by scohen28** [comment]
Not sure how to do a "select @@version" if I can't login :-)

I've deleted the existing cache/pkg of the package and did a new go get.

On my Mac - same error.
Then I run the program in docker as follows:
docker run -it -v $PWD:/go/src/test golang:latest /bin/bash

In the docker container I do a 'go get' followed by a go build - works fine (connects, etc.)

Back in the Mac, the error occurs.

Update:  I added the encrypt=disable; to the connection string as you suggested on the Mac and it now connects - so definitely something going on between OSs.

Thanks!

**Comment by anchepiece** [comment]
This may also apply when upgrading to go1.5.  It worked using go 1.4.1 but failed with:

Cannot connect: Login error: EOF

Appending "encrypt=disable;" to the connection string does allow the connection.

**Comment by dimdin** [comment]
Please, send us your SQL Server version, as returned by "select @@version"

**Comment by anchepiece** [comment]
Microsoft SQL Server 2005 - 9.00.5000.00 (Intel X86) 
Dec 10 2010 10:56:29 
Copyright (c) 1988-2005 Microsoft Corporation
Developer Edition on Windows NT 5.2 (Build 3790: Service Pack 2)

**Comment by dimdin** [comment]
Thank you very much @anchepiece , you have the latest service pack (4) of SQL Server 2005. I will investigate the problem next week.

**Comment by FireArrow** [comment]
Any progress on this issue?

**Comment by coussej** [comment]
Just encountered this same issue on SQL 2005 (9.0.1399). Using `encrypt=disable` indeed works.

**Comment by fisshy** [comment]
I have the same issue and it only occurs when I'm running it inside my docker container, but outside it runs as expected. 

Has anyone solved this issue? Setting encrypt=disable doesn't solve it for Azure.

**Comment by fisshy** [comment]
Ok, it works when I explicit tell it to pull golang:1.6 and not golang:latest.

**Comment by kardianos** [comment]
@fisshy Is golang:latest go1.7 or go1.8? Is there a setup script and code I can run to reproduce this? If so I can spin up an azure database and test.

**Comment by fisshy** [comment]
@kardianos Seems to be 1.7.4

I had a hard time reproduce it, it only occured when I used more then three columns in the select and the other columns where from an inner join / cross apply

Doesn't work
```
SELECT  e.EmployeeId,
        e.EmployeeName,
        isnull(e.IsTemporaryCard, 0) as IsTemporaryCard,
        c.Name as CompanyName
FROM dbo.TEmployee e with(nolock)
  INNER JOIN evoxs.Company c with(nolock) on e.CompanyId = c.Id
  CROSS APPLY (
    SELECT	TOP 1 t.EventType
      FROM [dbo].[TEvent] t WITH(NOLOCK)
      WHERE t.EmployeeID = e.EmployeeId
        AND t.EventType IN ( 11, 10 )
      ORDER BY EventTime DESC
  ) ev
```

This work
```
SELECT  e.EmployeeId,
        e.EmployeeName,
        isnull(e.IsTemporaryCard, 0) as IsTemporaryCard
FROM dbo.TEmployee e with(nolock)
  INNER JOIN evoxs.Company c with(nolock) on e.CompanyId = c.Id
  CROSS APPLY (
    SELECT	TOP 1 t.EventType
      FROM [dbo].[TEvent] t WITH(NOLOCK)
      WHERE t.EmployeeID = e.EmployeeId
        AND t.EventType IN ( 11, 10 )
      ORDER BY EventTime DESC
  ) ev
SELECT  e.EmployeeId,
        e.EmployeeName,
        isnull(e.IsTemporaryCard, 0) as IsTemporaryCard,
        c.Name as CompanyName
FROM dbo.TEmployee e with(nolock)
  INNER JOIN evoxs.Company c with(nolock) on e.CompanyId = c.Id
  CROSS APPLY (
    SELECT	TOP 1 t.EventType
      FROM [dbo].[TEvent] t WITH(NOLOCK)
      WHERE t.EmployeeID = e.EmployeeId
        AND t.EventType IN ( 11, 10 )
      ORDER BY EventTime DESC
  ) ev
```

```
FROM golang:1.6

MAINTAINER Joachim Karlsson <joachim@causam.se>

ADD . /go/src/bitbucket.org/devfishy/evoxs-api
RUN go install bitbucket.org/devfishy/evoxs-api
ENTRYPOINT /go/bin/evoxs-api

EXPOSE 80
```

```
docker build -t donfishy/evoxs-api .

docker run -e EVOXS_PORTAL -p 8000:8000 --name evoxs-api --rm donfishy/evoxs-api
```

**Comment by onehandofLM** [comment]
Thank you very much @anchepiece。 It works

**Comment by anchepiece** [comment]
No problem @onehandofLM, glad you found a solution!

**Comment by slamgundam** [comment]
Thank you very much @anchepiece  It works

**Comment by firesh** [comment]
SQLServer 2005
Disable encrypt by add `&encrypt=disable` works for me.
e.g. `sqlserver://sa:mypass@localhost?database=dbname&encrypt=disable
