### ISSUE TITLE
Login error: EOF on Windows Azure

### ISSUE THREAD

**Issue by kiwih** [denisenkom/go-mssqldb#123]
When running code from managed Azure, connecting to Azure SQL, this driver is unable to connect. It returns 
Login error: EOF

When I try to use "encrypt:disable;" in the connection string, it returns
TLS Handshake failed: Cannot read handshake packet: EOF

(It appears that readPrelogin will always change preloginENCRYPTION to encryptReq, regardless of what you request)

However, when I run the code locally on go 1.5 windows amd64, and on go 1.4.2 windows amd64, with or without "encrypt:disable;", it connects fine.

Any ideas on what might be causing this? The Azure is running go 1.4.2 windows amd64.

**Comment by kiwih** [comment]
This is almost certainly related to #103

**Comment by BrianActon** [comment]
This seems to be a problem related to permissions. Its more an Azure problem than a Go problem.

**Comment by kiwih** [comment]
We resolved the issue by changing from a V12 Azure SQL database to a V2 version, like they mention in #103. You may want to add this problem to your known issues. I guess you can close this issue, although if there is anything I can do to help you resolve the problem just let me know.
