### ISSUE TITLE
QueryRow doesn't work as documented

### ISSUE THREAD

**Issue by mikewilliamson** [denisenkom/go-mssqldb#126]
I'm using this fragment of code, which is taken almost verbatim from the example given in the QueryRow documentation:

    var Id int
    err = db.QueryRow("select max(EventId) from Event").Scan(&Id)
    switch {
    case err == sql.ErrNoRows:
        log.Printf("No EventId.")
    case err != nil:
        log.Fatal(err)
    default:
        fmt.Printf("Max EventId is %v\n", Id
    }

According to the docs, you would expect the message `No EventId`, but what you get is this:

`2015/09/11 10:38:53 sql: Scan error on column index 0: converting string "<nil>" to a int: strconv.ParseInt: parsing "<nil>": invalid syntax`

Is this a bug in the driver, or in the sql package?

**Comment by dimdin** [comment]
@mikewilliamson what is the database type of Event.EventId ?

**Comment by dimdin** [comment]
@mikewilliamson I can reproduce it with the code:

```go
func TestBug126(t *testing.T) {
	conn := open(t)
	defer conn.Close()
	var Id int
	err := conn.QueryRow("select null").Scan(&Id)
	if err != nil {
		t.Fatal("Cannot scan to int: ", err.Error())
	}
}
```

select max(EventId) from Event is going to return null when there are no records in Event.
You can not scan a null value to int, so this is not a bug.
To solve your problem try this query:
```sql
select max(EventId) from Event where exists (select 1 from Event)
```

**Comment by mikewilliamson** [comment]
Ah, got it, thanks.  I was mistakenly thinking that the query would return no rows rather than one row with a null.  My mistake.  Actually what I want is something like:

    select isnull(max(EventId), 0) from Event
