### ISSUE TITLE
Support for Go 1.5.1

### ISSUE THREAD

**Issue by mvbaffa** [denisenkom/go-mssqldb#128]
Does go-mssqldb support Go version 1.5.1

Thanks

**Comment by dimdin** [comment]
1.5.1 is supported. Currently there is a connectivity problem with SQL Server 2005, encrypted connections and go 1.5.x.

The best way to ensure that the driver supports your environment is to run the tests in your environment.
```sh
HOST=localhost SQLUSER=sa SQLPASSWORD=sa DATABASE=test go test
```
