### ISSUE TITLE
Can't connect to db with server name suffix

### ISSUE THREAD

**Issue by johnjelinek** [denisenkom/go-mssqldb#132]
When I pass in a dns where the server name contains a suffix like `/abc,1433`, it fails.

Example:

```
dsn := fmt.Sprintf("server=%s;user id=%s;password=%s;encrypt=disable;connection timeout=90",
    "database.example.com/db,1433", "myuser", "mypassword")

mssql, err := sql.Open("mssql", dsn)
```

This results in this error: `lookup database.example.com/db,1433: no such host` -- however, I can connect with Visual Studio / SSMS using this url.

As a sanity check, server's in this form `database.example.com` work correctly, hitting the same instance.

**Comment by lwdallas** [comment]
Have you tried database.example.com\\db?
