### ISSUE TITLE
Use SCOPE_IDENTITY() instead of @@IDENTITY for LastInsertID

### ISSUE THREAD

**Issue by phillipCouto** [denisenkom/go-mssqldb#133]
I have recently ran into an issue where I am trying to use the LastInsertID function but the ID I am getting does not exist and my foreign key constraint on my next statement fails.

I did some research and found out that the issue is because my table is replicated and when the first insert happens there is more inserts behind the scenes from triggers which sets the @@IDENTITY value to the last ID inserted in the session thus far.

I am only concerned with the Insert ID of the last statement I inserted and not the ID that was created by all the triggers in the background.

[Here is the documentation from Microsoft.](https://msdn.microsoft.com/en-us/library/ms190315.aspx)

I am not sure if there is a valid use case of tracking the last insert id from triggers executed because of a statement but I think the use of SCOPE_IDENTITY will be less confusing to new users in replicated scenarios.

**Comment by phillipCouto** [comment]
I am more than happy to create the PR to change the code to use SCOPE_IDENTITY.

**Comment by dimdin** [comment]
It is ok to use SCOPE_IDENTITY. @phillipCouto please go ahead and change the code

**Comment by phillipCouto** [comment]
Sadly after extensive amounts of testing looks like the scope is lost by the time we call select SCOPE_IDENTITY in the LastInsertID() function.

The only effective way to acquire the correct last insert id that has associated triggers is to change:
```go
result, err := db.Exec("INSERT INTO tbl (col1) VALUES (?)",val)
```

to
```go
row := db.QueryRow("INSERT INTO tbl (col1) VALUES (?); SELECT SCOPE_IDENTITY()",val)
```

and then scan the ID into a variable for later use.

I am closing the issue as it is not an issue with the driver and just an behaviour of SQL Server.

**Comment by phillipCouto** [comment]
Opps didn't mean to delete my comment.

The issue is not with the driver but an odd behaviour with SQL Server. 

To elaborate by the time a user calls LastInsertID() the scope needed by SCOPE_IDENTITY is no longer available and returns nil.

In order for a user to extract the correct ID when triggers are skewing the results of LastInsertID simply appending "SELECT SCOPE_IDENTITY()" to the end of their statement will allow for the proper ID to be retrieved.

**Comment by wangzhijin** [comment]
@phillipCouto 
It's very useful to me. Thanks a lot.
I'm not familiar with SQL Server, and don't know how to get the id by using ` SCOPE_IDENTITY()` 
It's necessary to change the code from ` db.Exec`  to ` db.QueryRow` .
I think these code should be added into sample source for developers.

**Comment by ndjordjevic** [comment]
> Opps didn't mean to delete my comment.
> 
> The issue is not with the driver but an odd behaviour with SQL Server.
> 
> To elaborate by the time a user calls LastInsertID() the scope needed by SCOPE_IDENTITY is no longer available and returns nil.
> 
> In order for a user to extract the correct ID when triggers are skewing the results of LastInsertID simply appending "SELECT SCOPE_IDENTITY()" to the end of their statement will allow for the proper ID to be retrieved.
> 
> So changing code from:
> 
> ```go
> result, err := db.Exec("INSERT INTO tbl (col2) VALUES (?)",val)
> ```
> 
> to
> 
> ```go
> row := db.QueryRow("INSERT INTO tbl (col2) VALUES (?); SELECT SCOPE_IDENTITY()",val)
> ```
> 
> and then scan the value into a variable for later use.

This works when insert goes ok, but if there's and error you can't see what went wrong

**Comment by phillipCouto** [comment]
I use this now:

```go
row := db.QueryRow("INSERT INTO tbl (col2) 
OUTPUT INSERTED.col1
VALUES (?)", val)
```

This way there are no errors hidden and it is a single query instead of multiple.
