### ISSUE TITLE
Issue with named instances, integrated security and maybe IP6

### ISSUE THREAD

**Issue by billgraziano** [denisenkom/go-mssqldb#135]
I've been starting to work a little with this driver on SQL Server 2014.  First off, thank you for this!  Writing a TDS parser doesn't look like it's for the faint of heart.

I'm running on a box that has named instances and SQL Server 2014 and IP6.  I've tried the following connection strings:

```
Server=127.0.0.1;port=51477;user id=gotest;password=P@ssword1;
Server=127.0.0.1;port=51477;
Server=D30\\SQL2014;user id=gotest;password=P@ssword1;
Server=D30\\SQL2014;
```

The first three work fine.  

The fourth one generates a "driver: bad connection" error.  My best guess is that it's related to a combination of integrated security and IP6.  The weird thing about that last query is that setting the log=63 returns three rows that just list the query I'm trying to run and I see three successful logins on the SQL Server -- but no queries.

I'm on Windows 81 with both SQL 2012 and SQL 2014 installed as named instances.

**Comment by judwhite** [comment]
I'm having the same issue with a named instance locally. I disabled Shared Memory and Named Pipes, leaving just TCP/IP, which worked for local server using the default instance name. However when I try to connect to `.\SVR1` or `[host]\SVR1` I get "driver: bad connection".

**Comment by billgraziano** [comment]
I'm still struggling with this issue.  I tried hardcoding "tcp4" and "udp4" in the source but that didn't resolve it.  It still doesn't like a named instance with a trusted connection.  Is anyone else using this combination successfully?

**Comment by denisenkom** [comment]
Can you post logs?

**Comment by billgraziano** [comment]
While I was working on this I stuck LOTS and LOTS of log.Println into the code and generated way too much output.  I tried connecting with machine\instance and IP,port to local instances.  The IP,port works but machine\instance fails.  I haven't had the ability to test anything over the network yet.

The logs are pretty similar through line 31 (works) and 34 (fails).  That's where I'm printing out raw TDS stuff.  I'm hoping that's helpful because I'm out of my depth here.

[works.txt](https://github.com/denisenkom/go-mssqldb/files/244234/works.txt)
[fails.txt](https://github.com/denisenkom/go-mssqldb/files/244235/fails.txt)

**Comment by cihatgenc** [comment]
Same issue here:
Server=MYLAPTOP\SQLEXPRESS;Database=master;port=51704; -> fails
Server=127.0.0.1;Database=master;port=51704; -> works
Server=192.168.1.76;Database=master;port=51704; -> works

BTW, I only tried integrated authentication
