### ISSUE TITLE
lookup server=localhost: getaddrinfow: No such host is known

### ISSUE THREAD

**Issue by haochun** [denisenkom/go-mssqldb#137]
lookup server=localhost: getaddrinfow: No such host is known
but,i can connect it by java.

**Comment by haochun** [comment]
my connect string is:server=localhost;user id=sa;password=123456

**Comment by denisenkom** [comment]
is this working for you:

server=127.0.0.1;user id=sa;password=123456

?

**Comment by haochun** [comment]
@denisenkom i have try it,and i use my ip.but it does not work.

**Comment by dimdin** [comment]
hello @haochun please verify that the server accepts tcp connections.
see: https://msdn.microsoft.com/en-us/library/bb909712(v=vs.90).aspx

**Comment by haochun** [comment]
@dimdin thank you ,i will try it.but,i can connect it by JDBC,i does not know why.

**Comment by BrianActon** [comment]
Try adding encrypt=disable
