### ISSUE TITLE
Question around concurrency

### ISSUE THREAD

**Issue by i0rek** [denisenkom/go-mssqldb#140]
Hello,

thanks for your work, go-mssqldb is great! 
I am inserting data into Azure SQL and even when I spin up multiple go routines to do so, I seem to hit a wall very fast. More than 2 go routines don't help with speed anymore. The database is almost idle, my cpu is idle, bandwidth is not exhausted... Do you have any pointers? I will provide a minimal example in a bit.

Thanks in advance for your time!

**Comment by i0rek** [comment]
Now that I am trying to provide a simple example I seem to prove myself wrong :D.

**Comment by dimdin** [comment]
Hello @i0rek 
- don' t forget that in default sql server isolation level both readers and writers place locks and block each other
- check that you close statements and rows

**Comment by i0rek** [comment]
@dimdin thank for your answer! This is what I am doing: https://gist.github.com/i0rek/a30d37744a8e0f5c38f3. I see improvement with this until ~10 go routines.

**Comment by dimdin** [comment]
try to:
- populate the channel with titles before starting the workers
- change the sql to:
```sql
INSERT INTO somethings WITH (ROWLOCK) (title) VALUES (?)
```

**Comment by i0rek** [comment]
I tested with `WITH (ROWLOCK)` and without it. it doesn't seem to make a difference in my particular case.

**Comment by i0rek** [comment]
I also tested with dedicated connections for each go routine. but that didn't change anything either.

**Comment by i0rek** [comment]
`SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED` doesn't have an impact either. :/

**Comment by dimdin** [comment]
GOMAXPROCS ?

**Comment by i0rek** [comment]
I am using `go version go1.5 darwin/amd64`. no difference. I am importing 500 entries with 10 go routines in 4s.

**Comment by i0rek** [comment]
From inside Azure it is 600ms.

**Comment by i0rek** [comment]
At this speed rowlock and isolation-level are making a difference.

**Comment by i0rek** [comment]
this is the last test I ran: 

```
$ ./simple -amount 50000 -worker 30
Took 10.7826288s
```

5k inserts per second is good enough for now. Latency is a big part it seems. Way bigger than I thought. I might give https://github.com/denisenkom/go-mssqldb/pull/79 a try.

**Comment by kardianos** [comment]
You are inserting into MS SQL server into the same table. Your best bet is to ensure a table lock is taken and use a single session. The bulk load API is critical to help doing this for MS SQL Server.
