### ISSUE TITLE
Prepare failed:Login error: unexpected EOF

### ISSUE THREAD

**Issue by wlfsky** [denisenkom/go-mssqldb#141]
win 10 x64 ,go 1.5.2 x64, sql server 2000 on windows server 2003
E:/GoProject/src/github.com/denisenkom/go-mssqldb/examples/examples.exe  [E:/GoProject/src/github.com/denisenkom/go-mssqldb/examples]
2016/01/19 22:17:12 Prepare failed:Login error: unexpected EOF

**Comment by dimdin** [comment]
Hello @wlfsky 
currently SQL Server 2000 is not supported
see #91

**Comment by wlfsky** [comment]
Thanks  @dimdin

**Comment by admin87** [comment]
how did you ling sql 2000

**Comment by wlfsky** [comment]
I ' m sorry , I forgot ! It ' s too long !
