### ISSUE TITLE
mssql - connect show success, but Prepare failed:InitialBytes InitializeSecurityContext failed 8009030c

### ISSUE THREAD

**Issue by ScottHuangZL** [denisenkom/go-mssqldb#144]
I use windows authentication, so not input user id and password.
I add sentence to detect whether connect success. It seems connect is work, however, 
It show errors like: Prepare failed:InitialBytes InitializeSecurityContext failed 8009030c
Can you help on it? Thanks.

**Setting:**
var debug = flag.Bool("debug", true, "enable debugging")
var password = flag.String("password", "", "the database password")
var port *int = flag.Int("port", 1433, "the database port")
var server = flag.String("server", "AUSASLDATA", "the database server")
var user = flag.String("user", "", "the database user")
...
conn, err := sql.Open("mssql", connString)
    if err != nil {
        log.Fatal("Open connection failed:", err.Error())
    } else {
        fmt.Printf("Connect Success")
    }
...

**Errors:**

 password:
 port:1433
 server:AUSASLDATA
 user:
 connString:server=AUSASLDATA;user id=;password=;port=1433
Connect Success2016/01/23 22:29:18 Prepare failed:InitialBytes InitializeSecurityContext failed 8009030c

**Comment by dimdin** [comment]
Hello @ScottHuangZL 
add in your connections parameters the SQL Server Service Principle Name (SPN)
e.g. connString = "server=AUSASLDATA;ServerSPN=MSSQLSvc/AUSASLDATA:1433"
see also https://technet.microsoft.com/en-us/library/bb735885.aspx

**Comment by ScottHuangZL** [comment]
Thank you @dimdin 
That mssql server at remote site and I do not have sa access right, just able write/read to one of database in that server.

**I use PHP to connect the remote mssql, it is working without any issue.**
 I do not have sufficient access rights to complete execute "setspn -A MSSQLsvc/AUSASLDATA:1433 <my domain account>"
**I am not sure why we need set SPN when use golang??** 

Any hints can help me? Thanks again.

**Comment by dimdin** [comment]
- What connection string do you use to connect from php?
- Is the golang machine on the same windows domain with the sql server?

**Comment by ScottHuangZL** [comment]
As for php, I use Yii2 framework, the connection string as below:
'connectionString' => 'sqlsrv:Server=AUSASLDATA;Database=EOL',
The drivers provided by Microsoft for php, thanks.

That server at USA, I am in China, anyway, should be different domain, however we are in same company and can access that DB. Thanks.

I am switch to ODBC to connect mssql , it is work for my go program now.
And waiting anybody help for go-mssql, thanks.

**Comment by kardianos** [comment]
@ScottHuangZL If you are using windows auth, what versions of NTLM does the server support? I think we only support NTLMv1 at the moment.

**Comment by lrtanner** [comment]
@kardianos - Can you link to the duplicate issues when you close them and mark them like this? It is really helpful when people stumble to these issues through google or outdated links.

**Comment by kardianos** [comment]
See https://github.com/denisenkom/go-mssqldb/issues/146

**Comment by CHN-STUDENT** [comment]
hi @ScottHuangZL @kardianos I get same issue when use gorm with go-mssqldb, could you give me some advice?


**UPDATE**
Finally, i found because my db user is empty. I use viper to get user from file, but my struct value name is wrong,so the user is empty.





```
connectionString := fmt.Sprintf("sqlserver://%s:%s@%s:%d?/database=%s&charset=utf8&parseTime=True&loc=Local&encrypt=disable",
		dbConfigs[index].Username, dbConfigs[index].Password, dbConfigs[index].Host, dbConfigs[index].Port, dbConfigs[index].DBName)


db, err := gorm.Open(sqlserver.Open(connectionString), &gorm.Config{})
```

```
[error] failed to initialize database, got error NextBytes InitializeSecurityContext failed 8009030e
Connect to 172.16.172.218 [] db failed: NextBytes InitializeSecurityContext failed 8009030e
{"level":"ERROR","time":"2023-09-14T11:47:08.100+0800","caller":"mssql/mssql.go:43","msg":"Connect to 172.16.172.218 [] db failed: NextBytes InitializeSecurityContext failed 8009030e\n"}
```

we use `sa` account to conncet to the database,
