### ISSUE TITLE
Question. Create DB query, cannot make it work with Statement Parameters

### ISSUE THREAD

**Issue by partamonov** [denisenkom/go-mssqldb#148]
``conn.Query("CREATE DATABASE [?1]", dbName)`` is giving me error Error creating MSSQL database my_db1: sql: statement expects 0 inputs; got 1, %!s(MISSING)

same but with concat is working:
`` _, err = conn.Query("CREATE DATABASE [" + dbName + "]")``

I made that based on example in ReadME
``db.Query("SELECT * FROM t WHERE a = ?3, b = ?2, c = ?1", "x", "y", "z")``

SELECT is working for me

**Comment by BrianActon** [comment]
Does db.Ping() work?

**Comment by partamonov** [comment]
Yeap, ping is working, and connection is fine. I can create DB if I use string concat ``"CREATE DATABASE [" + dbName + "]"`` but when I try to substitute it with statement parameters it fails.

I have SELECT statement with ``conn.Query("SELECT db_id(?1)", dbName)`` and it works fine.

**Comment by dimdin** [comment]
Hello @partamonov 
SQL Server cannot use parameters for identifiers (such as table names, field names and database names)

The only way is to concatenate the strings. If dbName can be entered by users, replace ']' characters with "]]" (e.g. "test]; drop database [master" must be escaped as "test]]; drop database [master" )

**Comment by partamonov** [comment]
Thank you. I re-read docs and found what I need. once again thank you for clarifying.
