### ISSUE TITLE
local temp tables are not working

### ISSUE THREAD

**Issue by rbucker** [denisenkom/go-mssqldb#149]
Is the driver reconnecting with each execute?

**Comment by dimdin** [comment]
The driver does not control the connections.
The database/sql package keeps a connection pool and can give you a different connection or a new connection for each execute (except for transactions).
See http://go-database-sql.org/connection-pool.html for ways to control the connection pool.

**Comment by TedKnudsen** [comment]
Possibly related: we've also tried to create local temp tables in a transaction.  If we use placeholders whilst creating the temp table, the temp table does not survive for subsequent queries to it in that transaction.  If we do NOT use placeholders, the temp table survives correctly.

db := database.GetDB(clientDatabase)
tx, err := db.Begin()
if err != nil {
	panic(err)
}
defer tx.Rollback()
stmt, err := tx.Prepare("SELECT ? AS 'SomeValue' INTO #tmpResults") // Placeholders break temps

if err != nil {
	panic(err)
}
_, err = stmt.Exec(222)

if err != nil {
	panic(err)
}

stmt2, err := tx.Prepare("SELECT * FROM #tmpResults") 
if err != nil {
	panic(err)
}

rows, err := stmt2.Query() // Fails
if err != nil {
	panic(err)
}

**Comment by dimdin** [comment]
@TedKnudsen from MS documentation:

"Temporary tables are automatically dropped when they go out of scope, unless explicitly dropped using DROP TABLE:
A local temporary table created in a stored procedure is dropped automatically when the stored procedure completes."

The driver is using the same connection in your code, but each Exec is a different batch and the temp ta ble lifespan is limited to that of the batch, i.e. dropped after each exec.

**Comment by TedKnudsen** [comment]
Can you please clarify: Why are the temp tables being generated in a different batch when using placeholders (?), but are working as expected when not using placeholders? 

See below: this works fine.  

db := database.GetDB(clientDatabase)
tx, err := db.Begin()
if err != nil {
panic(err)
}
defer tx.Rollback()
stmt, err := tx.Prepare("SELECT 222 AS 'SomeValue' INTO #tmpResults") 

if err != nil {
panic(err)
}
_, err = stmt.Exec()

if err != nil {
panic(err)
}

stmt2, err := tx.Prepare("SELECT * FROM #tmpResults") 
if err != nil {
panic(err)
}

rows, err := stmt2.Query() // Fails
if err != nil {
panic(err)
}

**Comment by dimdin** [comment]
The driver is using the sp_executesql stored procedure to prepare the sql statements. My guess is that temporary tables created from sp_executessql stored procedure are dropped when the stored procedure ends.

The driver is not using stored procedures when there are no parameters, and in that case it seems that the temporary table persists.

**Comment by dimdin** [comment]
"Prepared statements cannot be used to create temporary objects on SQL Server. Prepared statements cannot reference system stored procedures that create temporary objects, such as temporary tables. These procedures must be executed directly."

https://technet.microsoft.com/en-us/library/ms175528(v=sql.105).aspx

**Comment by TedKnudsen** [comment]
Thanks for clarification, we'll find workarounds.
