### ISSUE TITLE
Ping() not working

### ISSUE THREAD

**Issue by luca-moser** [denisenkom/go-mssqldb#154]
Hi, I am currently facing a problem with the Ping() method in the SQL package, when using this driver. It seems that Ping() suceeds no matter what.

I have some little test code:
```go
package main

import (
	"database/sql"
	"fmt"
    "time"
	_ "github.com/denisenkom/go-mssqldb"
)

func main() {

	connString := fmt.Sprintf("server=%s;user id=%s;password=%s;port=%d;database=%s;log=1",
		"host", "username", "password", 1433, "databasename")
	conn, err := sql.Open("mssql", connString)
	if err != nil {
		panic(err)
	}

	err = conn.Ping()
	if err != nil {
		fmt.Println("ping and reconnect failed:", err.Error())
		return
	}
	fmt.Println("connection to mssql database server ok")

    <-time.After(time.Duration(10) * time.Second)

    fmt.Println("pinging again database server...")
 	err = conn.Ping()
	if err != nil {
		fmt.Println("ping and reconnect failed:", err.Error())
		return
	}
	fmt.Println("connection to mssql database server ok")
}
```

When I run this code and remove the network cable on my laptop when the waiting is going on `<-time.After(time.Duration(10) * time.Second)`, the second pinging still succeeds with: `"connection to mssql database server ok"`, although the database server is physically not reachable (my wireless adapter is deactivated btw).

I am using Ping() to check wether the database server is still online and to automatically re-connect to it. From the godoc of `database/sql` it states: `"Ping verifies a connection to the database is still alive, establishing a connection if necessary."`. My apps crash/throw errors on the first workday each week, because we usually restart our database server on the weekends.

**Note**: If I run this program with no network connection from the beginning it fails up on the first Ping(). It looks like subsquential Ping() don't report correctly.

**Note 2**: If using conn.SetConnMaxLifetime(time.Duration(3) * time.Second) in this code, the second Ping() will fail as it should.

**Comment by dimdin** [comment]
The driver has no control. The golang Ping implementation reuses the last connection from the pool. see: https://golang.org/src/database/sql/sql.go?s=14098:14124#L489

**Comment by luca-moser** [comment]
I see, thanks for the heads up.
