### ISSUE TITLE
Failed to parse certificate from server

### ISSUE THREAD

**Issue by joaquinicolas** [denisenkom/go-mssqldb#155]
TLS Handshake failed: tls: failed to parse certificate from server: asn1: structure error: base 128 integer too large

var debug = flag.Bool("debug", false, "enable debugging")
var password = flag.String("password", "asdasd", "asdasd")
var port *int = flag.Int("port", 1433, "1433")
var server = flag.String("server", "111.72.41.53", "153.72.41.53")
var user = flag.String("user", "dummy", "dummy")

func insertToSqlServer(cliente Clientes)  {
    connString := fmt.Sprintf("server=%s;user id=%s;password=%s;port=%d", *server, *user, *password, *port)
    db,err := sql.Open("mssql",connString)
    checkErr(err)
    stmt,err := db.Prepare("INSERT INTO Clientes(Numero,Nombres,Pais) VALUES (?,?,?)")
    checkErr(err)
    res, err := stmt.Exec(cliente.numero,cliente.nombre,cliente.pais)
    checkErr(err)
....
}

**Comment by kardianos** [comment]
What go version are you using? SQL Server version? Can you reproduce with a non-private certificate?
