### ISSUE TITLE
Isolation level

### ISSUE THREAD

**Issue by itzamna314** [denisenkom/go-mssqldb#156]
It looks like this driver is always setting transaction isolation level to `0`.  Does this imply that all transactions are `READ UNCOMMITTED`, or that they use the server default?  I've been looking for the wire protocol for isolation levels, but I haven't been able to find anything.

Are there any plans to add support for setting isolation level in this driver?

**Comment by bhcleek** [comment]
`0` means to use the current isolation level. The documentation for the wire protocol you're looking for is https://msdn.microsoft.com/en-us/library/dd339887.aspx

**Comment by itzamna314** [comment]
Thanks!
