### ISSUE TITLE
How to set Command Timeout?

### ISSUE THREAD

**Issue by flaviotsf** [denisenkom/go-mssqldb#159]
I have a fairly slow SQL that I'm calling, that puts a lot of data together. I'd like to set the Command Timeout to "0". I believe the command is timing out, and I'm receiving a
`driver: bad connection`

If the query was to be made simpler (i.e. selecting less rows) it would finish.

I did try to set the Keep Alive and Dial Timeouts, but I believe I need a way to set the "Command Timeout" (similar to _net_read_timeout_ session variable in MySQL).

`;keepAlive=0;dial timeout=1000;encrypt=disable`

How would I go about that?

**Comment by vadimi** [comment]
I normally use `connection timeout` property for such cases.
