### ISSUE TITLE
not closing connections

### ISSUE THREAD

**Issue by rbucker** [denisenkom/go-mssqldb#161]
I have production code that loops over my query results and when the loop closes `(rows.Next() == false)` the connection remains open. Reviewing the test cases I do not see any validation of this operation.

**Comment by denisenkom** [comment]
Connection opening and closing is handled by go/sql.  It is using connection pool so it won't close connection after operation is complete but instead it will reuse it for further operations.  That is probably what you see.

**Comment by rbucker** [comment]
In my code I have a for loop that exhausts the resulting rows.  `rows.Next()` however `db.OpenConnections` returns ever increasing numbers of connections as I execute other `Query`. When I set max Open and max idle the application stalls. When I looked at the `database/sql` code they are testing this operation so I hope it's working. When I looked at go-mssqldb tests they did not.

**Comment by denisenkom** [comment]
I added a test and it seems to work correctly.  Please take a look and reopen if you still see a problem.
