### ISSUE TITLE
can not connet mssql with the error

### ISSUE THREAD

**Issue by zhaowolong** [denisenkom/go-mssqldb#164]
the code is:
connString := fmt.Sprintf("server=%s;user id=%s;password=%s;port=%d", *server, *user, *password, *port)
    if *debug {
        logging.Info(" connString:%s\n", connString)
    }
    cnn, err = sql.Open("mssql", connString)
    if err != nil {
        logging.Error("Open connection failed:%s", err.Error())
        return err
    }

```
stmt, err := cnn.Prepare("use QPTreasureDB")
if err != nil {
    logging.Error("Prepare failed:%s", err.Error())
    return err
}
```

return : Prepare failed Login error: EOF but i make user the user port password is right

**Comment by SQLServerIO** [comment]
have you tried just using .Query to execute the statement?

**Comment by melignus** [comment]
What version of mssql? Some versions, I think the express version or older versions error out when you try to connect via an encrypted connection. To test add `encrypt=disable` to the connection string to see if that fixes the error.

If it does, there is a patch to mssql server that addresses this issue. I'll see if I can find the post with the links to the fix.

**Comment by denisenkom** [comment]
closing since there is no response from @zhaowolong
