### ISSUE TITLE
Improper parsing of string identifiers

### ISSUE THREAD

**Issue by lcaballero** [denisenkom/go-mssqldb#170]
I think [#169](https://github.com/denisenkom/go-mssqldb/issues/169) needs to be re-opened.  The parsing in the library won't handle the following:

`User Id={ abc ;}`

Where the `;` is part of the value.  Mainly because of the split in this line: [tds.go@25](https://github.com/denisenkom/go-mssqldb/blob/master/tds.go#L25)

**Comment by denisenkom** [comment]
Duplicate of #169
