### ISSUE TITLE
Consider returning an error in case of a bad connection string

### ISSUE THREAD

**Issue by tartale** [denisenkom/go-mssqldb#171]
The following connection strings are illegal, but silently ignored:

`;;;`
`=foo; user id=bar; password=baz`

Since the `Open()` function allows returning of an error, it seems reasonable to report these as errors.

**Comment by denisenkom** [comment]
Driver already returns error on bad connection string.  The issue is that sql.DB.Open does not call driver's Open method until query is made.  So I don't think this issue can be fixed on driver level.

**Comment by kardianos** [comment]
Users should always call DB.Ping after opening a db pool.
