### ISSUE TITLE
Use of SetQueryNotification function

### ISSUE THREAD

**Issue by chaika2013** [denisenkom/go-mssqldb#173]
I'd like to use MSSQL query notification feature, but I can not find any example of how to get these notification using go-mssqldb. `README` file says that query notifications are supported and I can see `SetQueryNotification` in source code. But how can it be used with `database/sql` package?

**Comment by denisenkom** [comment]
Take a look at this pull request: https://github.com/denisenkom/go-mssqldb/pull/90
