### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by dipbhi** [denisenkom/go-mssqldb#174]
I am getting login failure error with sqlexpress 2016. I did try with encrypt=disable in the connection string but that doesn't seem to help. This user is able to connect fine using the management studio.

Here is the code:

```
db, err := sql.Open("mssql", "server=localhost\\SQLEXPRESS;port=65087;user id=someuser;password:abcd1234;database=finserv-db;encrypt=disable")
if err != nil {
	log.Panic("Open connection failed:", err.Error())
}

err := db.Ping()
if err != nil {
	log.Panic("Ping failed:", err.Error())
}
```

This is the exact error message:

> Ping failed:Login error: mssql: Login failed for user 'someuser'

In the windows event viewer, error is logged as

> Login failed for user 'someuser'. Reason: Password did not match that for the login provided. [CLIENT: 127.0.0.1]

**Comment by dimdin** [comment]
replace the colon after password with =

**Comment by dipbhi** [comment]
Oh wow, I must be blind! I am pretty sure I looked at the connection string 10 times. Thanks for your quick response, and yes it fixed the error.
