### ISSUE TITLE
false Unable to get instances from Sql Server Browser on host

### ISSUE THREAD

**Issue by baimeidaxia** [denisenkom/go-mssqldb#176]
false Unable to get instances from Sql Server Browser on host ***.55.172.1: read udp 192.168.2.110:54118->***.55.172.1:1434: i/o timeout
please help me , thank you

**Comment by dimdin** [comment]
Ensure that the SQL Server Browser windows service is running and there is no firewall blocking UDP port 1434. This service is used by the driver to get the TCP port of the SQL Server instance.

**Comment by baimeidaxia** [comment]
ok, thank you.

**Comment by brydavis** [comment]
I'm experiencing similar error message. 

Connection works fine in SQL Server Management Studio.

However, not so using driver.

Please help (and reopen issue). Thanks!

**Comment by kardianos** [comment]
Please specify the port.
you can use `sqlserver://user:pass@host:1433/instance?database=dbname` as the DSN.

**Comment by brydavis** [comment]
Sorry, that didn't work. :(

**Comment by TheRealGregD** [comment]
kardianos - brydavis is connecting to a SQL Server 2014 SP2 instance; if that makes any difference.

**Comment by brydavis** [comment]
Issue resolved.

Problem was DNS not recognizing the specific `server`.

Solution was to replace with IP address. (Always the simple fixes that haunt us the most.)

Works regardless of either connection string format.

Thanks

**Comment by Yang09701194** [comment]
In Win 10 note that to use ip connect to DB, you need to enable TCP/IP in `SQL Server Configuration Manager` ([see this link](https://stackoverflow.com/questions/17737568/connect-to-sql-server-through-ip-address)) , in the Service set the `SQL Server Browser` Stratup type to Automatic ([see this link](https://technet.microsoft.com/en-us/library/cc755249(v=ws.11).aspx)), and configure Database Engine Access in Windows Firewall ([see this link](https://msdn.microsoft.com/en-us/library/ms175043%28v=sql.120%29.aspx)).
