### ISSUE TITLE
Error: Single-Sign-On not work

### ISSUE THREAD

**Issue by heretic13** [denisenkom/go-mssqldb#177]
Hello.

I have a questions.
I use driver with empty connection string - "". It means that I connect to local database, on default port with **current Windows-user permissions**.

I have result:
sql.Open("mssql", "") - no errors. OK. Behavior of sql.Open() may do not established real connect and may not produce error.

conn.Ping() - no error. OK. Maybe I have established a good connection.

Make a query (something like "SELECT something from some_database"). That return error "driver: bad connection".

1st. What is this? Why I cannot recieve error on Ping() command?

2nd. Why I get error "bad connection"? Current Windows user have permission to connect to MSSQL. I checked it with **osql -E -Q "query text"** command. Additionaly current user is a member of groups that begins with "SQLServer*".

Configuration:
Windows 10 x64
Microsoft SQL Server 2008 R2 (SP2) - 10.50.4042.0 (X64)
go version go1.7.3 windows/amd64

PS: I know about the existence of user "sa" (connect work with it). Also connect work if I set real Windows User/Login in connect string. But I'm interested in login with current user permissions.

**Comment by heretic13** [comment]
Updated error:

write tcp 127.0.0.1:3587->127.0.0.1:1433: wsasend: An existing connection was forcibly closed by the remote host.

**Comment by heretic13** [comment]
FreeTDS binary (tsql) work on this machine on sspi mode.

**Comment by SQLServerIO** [comment]
Hi heretic13 I've been working through this as well #163 is the one I opened a few months back.

**Comment by heretic13** [comment]
Great Thaks!!!
Problem is IPv6.

`server=(local)\SQLEXPRESS`  -  bad connection
`server=127.0.0.1\SQLEXPRESS` - work
`server=[::1]\SQLEXPRESS`  - work (raw IPv6 address)

As you see raw IPv6 working! I think problem to conversion hostname -> IP adress.

**Comment by SQLServerIO** [comment]
This is the code I'm using to work around it for now.

	//look to see if we are trying to connect to the localhost and if so use a valid ip address instead
	//this is here due to a bug in go-mssqldb where you can't connect via windows auth if you are local to the server
	if strings.Contains(strings.ToUpper(serverInstance[0]), strings.ToUpper(hn)) {
		iaddrs, err := net.InterfaceAddrs()
		if err != nil {
			return
		}
		for _, address := range iaddrs {
			if ipnet, ok := address.(*net.IPNet); ok && !ipnet.IP.IsLoopback() {
				//hacky work around trying to connect locally and getting IPv6 local host address instead of IPv4
				if ipnet.IP.To4() != nil {
					if len(serverInstance) > 1 {
						Server = ipnet.IP.String() + "\\" + serverInstance[1]
					} else {
						Server = ipnet.IP.String()
					}
					return "server=" + Server + ";user id=" + User + ";password=" + Password + ";connection timeout=3600;encrypt=disable"
				}
			}
		}
	}
	return "server=" + Server + ";user id=" + User + ";password=" + Password + ";connection timeout=3600;encrypt=disable"

**Comment by heretic13** [comment]
My 5 coin in debugging:

Problem in parameter connectParams.serverSPN.

When use SSPI this parameter pass in auth.InitialBytes() and NextBytes().
Then calls InitializeSecurityContext(,, serverSPN,,,)

If I get connectString = `server=(local)\SQLEXPRESS` then p.serverSPN is "MSSQLSvc/localhost:49878" (in my case) and nothing work.

But if I change p.serverSPN to "MSSQLSvc/127.0.0.1:49878" or p.serverSPN = "MSSQLSvc/[::1]:49878" it's working!

I'm directly insert "MSSQLSvc/127.0.0.1:49878" in InitializeSecurityContext call inside auth.InitialBytes() and it's working (I do not change something in NextBytes() ).

Next Iteration:

connectString = `server=DESKTOP-ILACS5Q\SQLEXPRESS` ,  where DESKTOP-ILACS5Q is my computer name.
Not working. Change p.serverSPN to "MSSQLSvc/127.0.0.1:49878" and it's working!

I think we all do not understand Microsoft **Service principal name**.  :)

**Comment by heretic13** [comment]
gathered from FreeTDS:

/* build SPN */
	server_name = tds_dstr_cstr(&login->server_host_name);
	if (strchr(server_name, '.') == NULL) {
		struct addrinfo hints;
		int res;

		memset(&hints, 0, sizeof(hints));
		hints.ai_family = AF_UNSPEC;
		hints.ai_socktype = SOCK_STREAM;
		hints.ai_flags = AI_V4MAPPED|AI_ADDRCONFIG|AI_CANONNAME|AI_FQDN;
		res = getaddrinfo(server_name, NULL, &hints, &addrs);
		if (res) {
			/* some version of Windows does not support V4MAPPED
			 * and ADDRCONFIG, try without them
			 */
			hints.ai_flags = AI_CANONNAME|AI_FQDN;
			res = getaddrinfo(server_name, NULL, &hints, &addrs);
		}
		if (!res && addrs->ai_canonname && strchr(addrs->ai_canonname, '.') != NULL)
			server_name = addrs->ai_canonname;
	}
	if (strchr(server_name, '.') != NULL) {
		if (asprintf(&auth->sname, "MSSQLSvc/%s:%d", server_name, login->port) < 0) {
			if (addrs)
				freeaddrinfo(addrs);
			sec_fn->FreeCredentialsHandle(&auth->cred);
			free(auth);
			return NULL;
		}
		tdsdump_log(TDS_DBG_NETWORK, "kerberos name %s\n", auth->sname);
	}
	if (addrs)
		freeaddrinfo(addrs);

	status = sec_fn->InitializeSecurityContext(&auth->cred, NULL, auth->sname,
		ISC_REQ_CONFIDENTIALITY | ISC_REQ_REPLAY_DETECT | ISC_REQ_CONNECTION | ISC_REQ_ALLOCATE_MEMORY,
		0, SECURITY_NETWORK_DREP,
		NULL, 0,
		&auth->cred_ctx, &desc,
		&attrs, &ts);

**Comment by heretic13** [comment]
If I understand correctly, FreeTDS generate SPN with IP adresses instead of domain name.
If it is true, then need modify **parseConnectParams(params map[string]string) (*connectParams, error)** to provide correct SPN.

**Comment by bsandhu** [comment]
Hi,
Is this issue Win only? Any pointers on Linux kerberos auth support?

**Comment by heretic13** [comment]
windows specific error.

**Comment by ftjfo** [comment]
Are there any plans to fix this.  I have the same problem, running latest SQL server 2016 and drivers.  I just can't use the hostname on the same machine, however, the ip-address do work just fine.  This is not a big problem, but nonetheless annoying.

**Comment by kardianos** [comment]
This driver only does server name resolution over DNS, not WINS, so if your
server only has a hostname setup, and no DNS entry, then that is expected.
