### ISSUE TITLE
support for sql server 2000?

### ISSUE THREAD

**Issue by huaguoping** [denisenkom/go-mssqldb#180]
Could I use this driver to connect sql server 2000?When I did this, I got an error:

Login error: unexpected EOF 

I used the correct connect information...   :(

**Comment by denisenkom** [comment]
Currently not, oldest supported version is 2005

**Comment by huaguoping** [comment]
Thank you!
Excuse me, could you tell me that how can I connect to sql server 2000.
@denisenkom

**Comment by kardianos** [comment]
I would try a ODBC driver:
https://godoc.org/?q=odbc
