### ISSUE TITLE
proposal: modify logger

### ISSUE THREAD

**Issue by kardianos** [denisenkom/go-mssqldb#181]
Right now the SetLogger takes a *log.Logger, even though the pkg defines a logger interface.
It also logs to the console by default.

I propose the following:
 * Have driver.SetLogger take a `mssql.Logger` interface (the *log.Logger should still satisfy it).
 * Do not log by default.
 * Have the tests log to t.Log and t.Logf (small wrapper needed) so that they don't print unless they are in verbose mode.

**Comment by AlekSi** [comment]
Also you can use Printf-like function instead of interface:
```go
type Printf func(format string, a ...interface{})
```

This will allow one to use fmt.Printf, log.Printf, logrus.Printf, t.Logf, etc.

**Comment by kardianos** [comment]
This has been done.
