### ISSUE TITLE
proposal: support ssrp

### ISSUE THREAD

**Issue by kardianos** [denisenkom/go-mssqldb#185]
I could have missed something, but I don't believe it currently supports ssrp proto (discovers instances and ports used on a host.

I have a current implementation here I could donate over:
https://bitbucket.org/kardianos/rdb/src/9016e187c250331d1c1c35444a69f27b87bdb5e8/ms/ssrp/?at=default

**Comment by denisenkom** [comment]
It is implemented here: https://github.com/denisenkom/go-mssqldb/blob/master/tds.go#L50

**Comment by kardianos** [comment]
Whops! Thanks :)
