### ISSUE TITLE
proposal: driver facility to break up query batches

### ISSUE THREAD

**Issue by kardianos** [denisenkom/go-mssqldb#186]
SQL Server often breaks up queries with a keyword, often "GO".

Offer a parser package that parses a query and returns multiple query texts to run. This would not normally be done on a query, the user would need to separate them out by calling a separate API. I have an implementation I could donate here:

https://bitbucket.org/kardianos/rdb/src/9016e187c250331d1c1c35444a69f27b87bdb5e8/ms/batch/?at=default

**Comment by dimdin** [comment]
@kardianos note that the syntax of the go statement is 
```sql
GO [count]
```
Please see https://docs.microsoft.com/en-us/sql/t-sql/language-elements/sql-server-utilities-statements-go

**Comment by kardianos** [comment]
It is indeed. In that package I took a shortcut because I never personally use the [count]. I will do a more correct parsing before submitting to this repo.

**Comment by dimdin** [comment]
I cannot find the syntax for the isql/osql/sqlcmd scripts. I know the go and \ syntax. Backslash is documented here https://docs.microsoft.com/en-us/sql/t-sql/language-elements/sql-server-utilities-statements-backslash

**Comment by kardianos** [comment]
@dimdin I've fuzzed the associated PR, it should be good to go. Let me know/merge if you think it is good to go.
