### ISSUE TITLE
need ability to escape ":" and "$" characters in query string

### ISSUE THREAD

**Issue by dpurfield** [denisenkom/go-mssqldb#192]
I'm writing a utility to deploy SQL Schema and have ran into a couple issues around not being able to escape the parameter prefixes.  The following are a couple examples that demonstrate valid T-SQL that do not include any parameters.  However the parser is indicating they have parameters which causes errors.

ALTER AUTHORIZATION ON SCHEMA::Audit TO dbo;
GRANT EXECUTE ON SCHEMA::Audit TO MeterServiceRole AS dbo;
SELECT $1.20 MoneyConstant

Either adding a way to escape these or adding an option to the connection string to disable ":" and "$" as parameter prefixing and leaving only "?" to identify query parameters would work.

**Comment by kardianos** [comment]
I'm not seeing the issue right now, but I'd like to provide a way to ensure queries aren't processed at all. To be used in conjunction with go1.8 named parameters.

Would that solve your issue too?

**Comment by dpurfield** [comment]
I'm not completely sure how the named parameters work in 1.8.  But I'm guessing the issue is still there.  Currently the parser is returning the number of parameters it finds in the query.  In any of the statements above the parser is now returning 1 as the count of parameters.  Only there really are not parameters those are just valid parameterless T-SQL statements.  In the first statement for example it thinks ":Audit" is a named parameter.  Only since its not really a parameter I'm not passing one.  So in database/sql.go in method rowsiFromStatement there is a check if the count of parameters found matches the number of arguments supplied and since they don't match it returns and error: "sql: statement expects %d inputs; got %d" instead of running the query.

**Comment by dpurfield** [comment]
Not that this shouldn't be address as others may run into it.  But I've taken a lesson from ADO .NET that actually is working very nicely and addresses a number of issues I had to code around.  I'm wrapping each batch in a call to sp_executeSQL:
	script := ""
	for _, qry := range batches {
		script += "exec sp_executesql N'" + strings.Replace(qry, "'", "''", -1) + "';\n"
	}
	_, err = db.Exec(script)

This is allowing me to send multiple batches that are separated by GO's in one call.  By using sp_executeSQL it also cleans up connection settings and state.  So it removes the need for clean up i was doing to make sure no transaction was left open, the database wasn't changed, or SET options where changed by a script.  It also guarantees all batches from the same file are run together using the same actual connection so any temp procedures created are there, without the need to set maxConnections=1.  The reduced code and round trips to the database has speed up the process considerably, and is much cleaner.

**Comment by calvn** [comment]
@dpurfield We are also encountering this issue with statements like `GRANT SELECT ON SCHEMA::dbo TO [foo]`. This would be the error that sql would return:

```
 sql: expected 1 arguments, got 0
```

**Comment by kardianos** [comment]
I would recommend you migrate your queries to using sqlserver rather the mssql as the driver name.

**Comment by calvn** [comment]
Changing the driver to sqlserver solved the issue, thanks!
