### ISSUE TITLE
proposal: add CI

### ISSUE THREAD

**Issue by AlekSi** [denisenkom/go-mssqldb#194]
It will make contributing easier.

You can use https://www.appveyor.com and this configuration as a basis:
* https://github.com/go-reform/reform/blob/v1-stable/appveyor.yml
* https://github.com/go-reform/reform/blob/v1-stable/.github/appveyor-prepare-mssql.ps1

**Comment by wingyplus** [comment]
I interest this proposal.

**Comment by AlekSi** [comment]
You may also want to use [`microsoft/mssql-server-linux`](https://hub.docker.com/r/microsoft/mssql-server-linux/) Docker image for Linux.

**Comment by gaspardle** [comment]
Here's a configuration for go-mssql : https://github.com/gaspardle/go-mssqldb/blob/ci/appveyor.yml

**Comment by wingyplus** [comment]
@gaspardle Great. I never use appveyor before. Can it run on every pull request?

**Comment by kardianos** [comment]
Yes, it can, it just needs to be configured in the repo to do so.

**Comment by kardianos** [comment]
I've merged the appveyor yaml in. https://ci.appveyor.com/project/kardianos/go-mssqldb/build/1.0.1

At this point we need to:

 * Fix the bulk copy test/code for go1.8
 * Configure the repo to notify appveyor of changes.
 * Probably add a badge to the readme to point to the CI env.

**Comment by AlekSi** [comment]
Why URL contains `kardianos`, not `denisenkom`?

**Comment by kardianos** [comment]
@AlekSi Because I set it up.

@denisenkom : Could we touch bases to finish setting up the CI? It is ready to go if you want to use your own appveyor account as well (free for open source projects).

**Comment by denisenkom** [comment]
@kardianos will take a look, unless you have step-by-step instructions for me.

**Comment by kardianos** [comment]
@denisenkom If you want to setup the CI under your account, go to appveyor.com and setup a free account, then create a CI for the project.

If you just want to use my appveyor account (fine with me), go to this repository's settings, click "Webhooks", and add a appveyor URL: `https://ci.appveyor.com/api/github/webhook?id=ujv21jd241h8o5s7`

**Comment by denisenkom** [comment]
PR: https://github.com/denisenkom/go-mssqldb/pull/278

**Comment by denisenkom** [comment]
How does appveyor know to install SQL server?

**Comment by kardianos** [comment]
https://github.com/denisenkom/go-mssqldb/blob/master/appveyor.yml#L25

**Comment by denisenkom** [comment]
Great, I didn't know that you can run tests on Windows for free!
