### ISSUE TITLE
 undefined: driver.ConnBeginTx

### ISSUE THREAD

**Issue by 756445638** [denisenkom/go-mssqldb#206]
I have this error on my windows10 host

# github.com/denisenkom/go-mssqldb
..\..\denisenkom\go-mssqldb\mssql_go18.go:21: undefined: driver.ConnBeginTx
..\..\denisenkom\go-mssqldb\mssql_go18.go:24: undefined: driver.TxOptions

what should I do to slove this problem!!

**Comment by kardianos** [comment]
What does go version say?

**Comment by kardianos** [comment]
I ask because go1.8 beta 1 won't work. Update to the latest and try again.

**Comment by 756445638** [comment]
My go version is "go1.8beta1 windows/amd64"!
what do you mean "up to latest", you code or go compiler!!
I have executed "git pull" command at your directory and excuted "go test",still I can see this error!!

**Comment by kardianos** [comment]
Update to Go beta2 or master, or use go1.7.x.
