### ISSUE TITLE
Ensure errors return driver.ErrBadConn rather than io.EOF if the connection fails.

### ISSUE THREAD

**Issue by vadimyer** [denisenkom/go-mssqldb#210]
Hey, this is probably just a question.

I'm having a simple database call with gorm like this:

```
rows, err := gorm.Table(tableName).Select("*").Rows()
```

The request takes some time to process (10-20 sec). I got an error from this call, the description is quite simple, only `EOF`. This happened **once**, can't reproduce again. I just wonder, what causes this error? Is it SQL server acting weird and closing the connection while proceeding the request? Or what?

Thank you.

**Comment by kardianos** [comment]
What version of go-mssqldb were you using (revision)?

**Comment by kardianos** [comment]
Regardless, this is unknown. It depends. This is hopefully resolved with a pending pull request, but if you can reproduce, that would also be great.

**Comment by vadimyer** [comment]
I was using `aa91b9def474faafb2406c8b562ae1e0e1f89ea4`.

**Comment by vadimyer** [comment]
It happened again. To replicate it, I just left my app alone for like 12+ hours, it was completely inactive and didn't make any requests to SQL server. Then I ran a command that does the request, and got an `EOF`. Probably the connection was dead/closed on server side.

**Comment by kardianos** [comment]
Thanks! I suspect we need to return `driver.ErrBadConn` somewhere rather than `io.EOF`.

**Comment by vadimyer** [comment]
Yeah no problem, but what can I do to avoid such problem in future?

**Comment by kardianos** [comment]
You either wait till I or someone else fixes it or you can fix it and submit a pull request I suppose. I do want to fix it in the next week or two.

Ideally I would add a test case for this as well that is triggered quicker.

**Comment by vadimyer** [comment]
Oh, I thought you meant this should return `driver.ErrBadConn` instead of `EOF`, no? It would still be an error, so thus I was wondering how you could avoid it. If that's not what you meant, than I can try to look at it, but I'm totally not familiar with how the driver works.

**Comment by kardianos** [comment]
If the driver returns driver.ErrBadConn, the sql layer you use will try again, this time with a good connection. Optionally you could also adjust the sql.DB params, specifically, if you sent `DB.SetConnMaxLifetime` to a shorter time span it may resolve this to you (I'm thinking 5 minutes or less).

**Comment by vadimyer** [comment]
Ok that's clear, thanks!
If I'd have some free time for this, I'll make a PR, not promising anything though =)

**Comment by kardianos** [comment]
This should not be fixed.
