### ISSUE TITLE
Access MSSQL SERVER error

### ISSUE THREAD

**Issue by huangpeizhi** [denisenkom/go-mssqldb#211]
hi, denisenkom 

I access MSSQL SERVER error.
![image](https://cloud.githubusercontent.com/assets/19602075/21843630/ac9c63d0-d826-11e6-8e59-96dff95c29cc.png)

```
func (s *Server) initDb(user, passwd, hostport, db string) (*sql.DB, error) {
	connstr := fmt.Sprintf("sqlserver://%s:%s@%s?database=%s&connection+timeout=30",
		user, passwd, hostport, db)
	dbo, err := sql.Open("sqlserver", connstr)
	if err != nil {
		return nil, fmt.Errorf("Open error %s", err)
	}

	return dbo, nil
}

func (s *Server) LoadData(user, passwd, hostport, db string) error {
	dbo, err := s.initDb(user, passwd, hostport, db)
	if err != nil {
		return fmt.Errorf("LoadData initDb error: %s", err)
	}

	rows, err := dbo.Query(conf.MSSQL.SQL)
	if err != nil {
		return fmt.Errorf("Query error: %s", err)
	}
	defer rows.Close()
	defer dbo.Close()

	var busId string
	var datacount int64
	for rows.Next() {
		err := rows.Scan(&busId, &datacount)
		if err != nil {
			glog.Warningln("LoadData Scan err, %s", err)
			continue
		}

		data := &Rec{
			BusId:     busId,
			DataCount: datacount,
		}

		s.distrCh <- data

		glog.Infof("%s\n", data.String())

	}

	return nil
}

```

I know less about MSQL,, please help!

**Comment by kardianos** [comment]
Hi, to me it looks like it might be a username / password issue.
What happens if you use a URL builder rather then string substitution? Something like this:
```
db, err := sql.Open("sqlserver", (&url.URL{
    Scheme:   "sqlserver",
    User:     url.UserPassword(username, password),
    Host:     fmt.Sprintf("%s:%d", hostname, port),
    // Path:  instance, // if connecting to an instance instead of a port
    RawQuery: query.Encode(),
}).String())
```

**Comment by huangpeizhi** [comment]
Hi, @kardianos 

Run same errors 

![image](https://cloud.githubusercontent.com/assets/19602075/21874726/c4858716-d8b1-11e6-8f56-d513333f9277.png)

- ERROR INFO:
```
I0112 10:21:25.819675    7352 mssqlio.go:30] mssqlio.exe using configuration file mssqlio.yaml
I0112 10:21:25.839676    7352 server.go:181] startup metrics service
I0112 10:21:25.839676    7352 server.go:175] startup Push service
I0112 10:21:25.839676    7352 server.go:166] run Load service 2017-01-12T10:21:25
W0112 10:21:25.854677    7352 server.go:168] LoadData error, LoadData initDb err
or: Ping error Login error: read tcp 172.31.30.179:61350->172.30.231.19:1433: wsarecv: An existing connection was forcibly closed by the remote host.
```

**Comment by adramalech** [comment]
I receive the same error against 2005 SQL Server.  As soon as I targeted against a mirrored version of the database on 2008 version it worked just fine.  I am wondering if 2005 is no longer supported maybe update the readme content and update to say support 2008+? 

I  have my sql.DB* initialization as such:

    query := url.Values{}
    query.Add("database", "<dbNameHere>")
    query.Add("encryption", "disable")
    query.Add("connection timeout", "30")

     db, err := sql.Open("sqlserver", (&url.URL{
  	   Scheme: "sqlserver",
	   User:   url.UserPassword("<username>", "<password>"),
	   Host:   fmt.Sprintf("%s:%d", "<ipAddressHere>", 1433),
	   RawQuery: query.Encode(),
     }).String())

     if err != nil {
	   log.Fatalf("Open: %v", err)
	   return
     }

     if err = db.Ping(); err != nil {
	    log.Println(err)
	    log.Fatalf("Ping: %v", err)
	    return
     }
 
     defer db.Close()

**Comment by kardianos** [comment]
@huangpeizhi What version of SQL Server are you trying to access?

**Comment by liugehao** [comment]
sql server 2008 r2 (10.50.1600.1)

**Comment by denisenkom** [comment]
Can you enable verbose logging and provide logs to me?

**Comment by firesh** [comment]
Disable encrypt by add `&encrypt=disable` works for me.
e.g. `sqlserver://sa:mypass@localhost?database=dbname&encrypt=disable
