### ISSUE TITLE
EOF error on queries with big parameter values and enabled encryption

### ISSUE THREAD

**Issue by fabotronix** [denisenkom/go-mssqldb#214]
Hi,

when I try to execute a query with a larger parameter, the query fails with an EOF error.

But if I disable the encryption the my query succeeds. Also when the length of parameter in my example is decreased from 1636 to 1635 the query succeeds.

I can reproduce this issue with the attached code against a mssql-server-linux running on docker:
```go
func main() {
	dbh, err := Open()
	if err != nil {
		panic(err)
	}
	defer dbh.Close()
	err = insertText(dbh, strings.Repeat("c", 1636))
	if err != nil {
		panic(err)
	}
}

func Open() (*sql.DB, error) {
	hostname := "localhost"
	user := "..."
	password := "..."

	log.Println("Open MS SQL database")
	connStr :=
		"odbc:server=" + hostname + ";" +
			"Database=testdb;" +
			"user id=" + user + ";password=" + password + ";encrypt=true;" +
			"TrustServerCertificate=true;Connection Timeout=30;log=127"
	d, err := sql.Open("mssql", connStr)
	if err != nil {
		return nil, errors.Wrap(err, "Error opening database")
	}
	return d, nil
}


func insertText(dbh *sql.DB, text string) (error) {
	tx, err := dbh.Begin()
	defer tx.Rollback()

	insertSQL := `INSERT INTO test(
		primary_text
	) VALUES(
		?
	)`
	res, err := tx.Exec(
		insertSQL, text,
	)
	if err != nil {
		return errors.Wrap(err, "Failed to execute database insert")
	}
	rowsAffected, err := res.RowsAffected()
	if err != nil {
		return errors.Wrap(err, "Error reading affected rows after database insert")
	}
	if rowsAffected != 1 {
		return errors.New("Database insert did not produce exactly one new row")
	}
	err = tx.Commit()
	if err != nil {
		return errors.Wrap(err, "Error committing transaction")
	}
	return nil
}
```
sample output:

> 2017/01/12 17:02:36 Open MS SQL database
2017/01/12 17:02:36 initiating resonse reading
2017/01/12 17:02:36 got token id 173
2017/01/12 17:02:36 got token id 227
2017/01/12 17:02:36 got token id 253
2017/01/12 17:02:36 got DONE or DONEPROC status=0
2017/01/12 17:02:36 response finished
2017/01/12 17:02:36 initiating resonse reading
2017/01/12 17:02:36 got token id 227
2017/01/12 17:02:36 BEGIN TRANSACTION 3500000001
2017/01/12 17:02:36 got token id 253
2017/01/12 17:02:36 got DONE or DONEPROC status=0
2017/01/12 17:02:36 response finished
2017/01/12 17:02:36 INSERT INTO test(
		primary_text
	) VALUES(
		@p1
	)
2017/01/12 17:02:36 	@p1	{ 1 cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc}
2017/01/12 17:02:36 initiating resonse reading
2017/01/12 17:02:36 ERROR: BeginRead failed EOF
2017/01/12 17:02:36 response finished
2017/01/12 17:02:36 initiating resonse reading
2017/01/12 17:02:36 ERROR: BeginRead failed EOF
2017/01/12 17:02:36 response finished
panic: Failed to execute database insert: EOF
> 
> goroutine 1 [running]:
> panic(0x5cef00, 0xc42043cc20)
>	/home/fabotronix/.opt/go/src/runtime/panic.go:500 +0x1a1
> main.main()
> 	/home/fabotronix/workspace/src/db_tool.go:22 +0xf0
>
> Process finished with exit code 2

**Comment by kardianos** [comment]
What is your `go version` and git revision of this package?

**Comment by fabotronix** [comment]
go version go1.7 linux/amd64

I am using revision 370263e74ba8f78a6a3fa15202e934f1be4eccd4 of your package.

**Comment by kardianos** [comment]
For own ref: could be we are not reading the N bytes returned from read before handling EOF.

**Comment by Ragnaroek** [comment]
It doesn't seem to be a sole issues with big parameters. Some queries seem to result in EOFs.

**Comment by fisshy** [comment]
I end up with EOF when running longer queries. I usually end up creating a stored procedure to handle longer queries.

**Comment by kardianos** [comment]
This has likely been fixed at tip. Please update to latest and re-open or re-file a bug if this continues.
