### ISSUE TITLE
proposal: tag releases

### ISSUE THREAD

**Issue by mjdavies** [denisenkom/go-mssqldb#215]
Hi there

Loving the software!!

Any chance you could create a tag or a release version so we can stipulate what version to install with govendor?

So we could do something like this?

govendor get github.com/denisenkom/go-mssqldb@v=1.0

https://github.com/kardianos/govendor

We're currently pulling down master so at the mercy of any changes to master.

Thanks in advance

Matt

**Comment by kardianos** [comment]
Hi Matt, I don't think we are ready to tag a release yet. I'm also not sure if we will tag a release in the future, but we'll see.

govendor also supports using revisions to specify package version if you'd like.

**Comment by mjdavies** [comment]
Hi Kardianos

Thanks for getting back to me.

I worked out that I could point govendor at a commit point in git just after I added this request :-)  

A release would be even cooler, but as we can use the commit point there's no urgent need.

Thanks again

Matt

**Comment by AlekSi** [comment]
It is still helpful to have a SemVer tag even if `0.y.z`.

**Comment by femiagbabiaka** [comment]
👋 hey @kardianos! wanted to see if this was still on the table, I'd find it quite useful as well.

**Comment by 3t-dev** [comment]
Hi @kardianos, because of Go module is popular now, it better to make a SemVer tag like vX.Y.Z.
If this repository is not ready to release, we could make a release like v0.1.0.

**Comment by kardianos** [comment]
I'm aware of go modules.

Can someone help me understand the benefit of using a v0.x.y release vs using a v0.0.0-datetime-hash?

**Comment by flibustenet** [comment]
I think it's more important to add a `go.mod` and `go.sum`, then v0.1.0 could be "the tag from where the project is module aware".

**Comment by kardianos** [comment]
@flibustenet Oh, you're right, we don't have a go.mod file present yet. Will fix soon.

**Comment by kardianos** [comment]
`go.mod` now in master. Thanks for the note.

**Comment by AlekSi** [comment]
And now we have v0.9.0 tag. Probably that issue can be closed now?
