### ISSUE TITLE
connection reset by peer just after sql.Open and Ping

### ISSUE THREAD

**Issue by rjtsdl** [denisenkom/go-mssqldb#217]
```
if err := si.db.Ping(); err != nil {
	return err
}
/*
	// Workaround: Need to have the following one
	// Seems it helps to keep alive the si.db, db.Ping is not enough
	// db keepalive mechanism. Ref : https://github.com/denisenkom/go-mssqldb/issues/44
	if _, err := si.db.Exec("SELECT @@version"); err != nil {
		return err
	}
*/
```

I got err when i try to use si.db

><*net.OpError | 0xc42050d090>: {
              Op: "read",
              Net: "tcp",
              Source: {
                  IP: [10, 106, 224, 37],
                  Port: 51083,
                  Zone: "",
              },
             Addr: {
                  IP: [13, 66, 226, 202],
                  Port: 1433,
                  Zone: "",
              },
              Err: {Syscall: "read", Err: 0x36},
          }
          read tcp 10.106.224.37:51083->13.66.226.202:1433: read: connection reset by peer

However, if i uncomment the code in /**/ block. Things work well. 

Just wondering if anyone seen the problem ? Any idea ?

**Comment by kardianos** [comment]
What's the driver revision, go version, and SQL Server Version?
What is the platform (Windows, Linux) of server and client?

**Comment by rjtsdl** [comment]
Go version: go version go1.7.4 darwin/amd64
Go-mssqldb version: "revision": "e8c056fef6cc06e6e77319583ca95c7ce5f65e4b"
client platform: macOS
server platform: Azure SQL Database V12

**Comment by kardianos** [comment]
Please update to the latest version of go-mssqldb and try again before we go further.

**Comment by rjtsdl** [comment]
Just update to the latest of go-mssqldb: "revision": "9e40d9d5d325edfaa84d3374bfde6e1adce02d58"

The issue stands

**Comment by kardianos** [comment]
Thanks for testing. I'll look into this though I don't have time right away.

**Comment by Fank** [comment]
Got the same issue:
go version go1.7.4 linux/amd64
Go-mssqldb version: "revision": "9e40d9d5d325edfaa84d3374bfde6e1adce02d58"
client platform: Ubuntu 16.04.1 LTS
server platform: SQL Server 2008 R2
connected via URL format

```
2017/01/24 11:01:06 ERROR: BeginRead failed read tcp 192.168.40.27:37810->192.168.80.27:1433: read: connection reset by peer
2017/01/24 11:01:06 Prepare failed:Login error: read tcp 192.168.40.27:37810->192.168.80.27:1433: read: connection reset by peer
```

**Comment by winsuney** [comment]
Got the same issue:
go version go1.8 darwin/amd64
Go-mssqldb version: latest
client platform: macOS
server platform: SQL Server 2008 R2

**Comment by kardianos** [comment]
Is encryption turned on?

**Comment by winsuney** [comment]
I think the connect error reason is the Sql Server version,because I can connect to another sql server use same method,but the two sql server are all SQL Server 2008 R2. why this one can not?

**Comment by Fank** [comment]
@kardianos I can confirm as @winsuney commented its an issue with the older sql server version, we updated it and it works.

Before update (not working)
```
Microsoft SQL Server 2008 R2 (RTM) - 10.50.1617.0 (X64) 
	Apr 22 2011 19:23:43 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
```

After update (working)
```
Microsoft SQL Server 2008 R2 (SP3) - 10.50.6000.34 (X64) 
	Aug 19 2014 12:21:34 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
```

**Comment by zhensun** [comment]
I got the same error when connecting to SQL Server 2008 R2 (RTM). Works fine with SQL Server 2014 though.

Any plan to add support for SQL Server 2008 R2 (RTM)?

Thanks!

**Comment by rjtsdl** [comment]
I found a way to solve this issue.

Before (not working), i was using 
```
db.SetMaxOpenConns(10)
db.SetMaxIdleConns(10)
```

Now (working), i am using
```
db.SetMaxOpenConns(0)
db.SetMaxIdleConns(10)
```

And my setup about versions, doesn't change.

**Comment by rjtsdl** [comment]
I will close the issue. As i found way to solve the scenario i described.

**Comment by panchengtao** [comment]
> @kardianos I can confirm as @winsuney commented its an issue with the older sql server version, we updated it and it works.
> 
> Before update (not working)
> 
> ```
> Microsoft SQL Server 2008 R2 (RTM) - 10.50.1617.0 (X64) 
> 	Apr 22 2011 19:23:43 
> 	Copyright (c) Microsoft Corporation
> 	Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
> ```
> 
> After update (working)
> 
> ```
> Microsoft SQL Server 2008 R2 (SP3) - 10.50.6000.34 (X64) 
> 	Aug 19 2014 12:21:34 
> 	Copyright (c) Microsoft Corporation
> 	Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
> ```

Hey, I got the same issue, and the remote server version is shown as the following
```
Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64) 
	Apr  2 2010 15:48:46 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) (Hypervisor)
```

However, I can't upgrade the sqlserver, could you plz give some advice?

**Comment by eugenefoxx** [comment]
> > @kardianos I can confirm as @winsuney commented its an issue with the older sql server version, we updated it and it works.
> > Before update (not working)
> > ```
> > Microsoft SQL Server 2008 R2 (RTM) - 10.50.1617.0 (X64) 
> > 	Apr 22 2011 19:23:43 
> > 	Copyright (c) Microsoft Corporation
> > 	Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After update (working)
> > ```
> > Microsoft SQL Server 2008 R2 (SP3) - 10.50.6000.34 (X64) 
> > 	Aug 19 2014 12:21:34 
> > 	Copyright (c) Microsoft Corporation
> > 	Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
> > ```
> 
> Hey, I got the same issue, and the remote server version is shown as the following
> 
> ```
> Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64) 
> 	Apr  2 2010 15:48:46 
> 	Copyright (c) Microsoft Corporation
> 	Enterprise Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) (Hypervisor)
> ```
> 
> However, I can't upgrade the sqlserver, could you plz give some advice?

Add parameter "encrypt=disable".
