### ISSUE TITLE
When the database does not exist when the connection should be established to fail, rather than using the default database.

### ISSUE THREAD

**Issue by GameXG** [denisenkom/go-mssqldb#218]
Just met a fault, sql database failure to restart, go after all the procedures sql operation has been thrown table does not exist error, restart the program after the normal.

Check found that the cause of the failure is:
1.sql database failure to restart
2.go program re-establish the connection, and according to the connection string database set the current database
3. But the target database is not available at this time (may be abnormal restart automatic repair), go program set the current database failed.
4. Set the current database error is ignored, after all the sql operation in the default database implementation, the table does not exist error.

I think this logic needs to be revised, when the database does not exist when the connection should be established directly to the failure, rather than using the default database.

Using the default database is a dangerous operation, the go program will sql operation in the wrong database, if the default database exists important information is likely to damage the default database.

And even if the table name does not change the default database, go after the sql operation will fail unless the re-establishment of the connection to the database.

**Comment by GameXG** [comment]
Sorry, my English is not good.

The current database settings are login and account password provided to the mssq server (login package), but in the specified database does not exist when the database does not prevent the landing, but provides an error. Landing as usual success, but the current database to the default database.

The problem lies in the mssqldb landing in the judge whether the success did not check whether there is an error, ignoring the default database settings failed this error.

Login code:

Https://github.com/denisenkom/go-mssqldb/blob/master/token.go#L586
Received an error message

Https://github.com/denisenkom/go-mssqldb/blob/master/token.go#L553
Token done to add an error message to tokenDone.


Https://github.com/denisenkom/go-mssqldb/pull/224/files#diff-8de67d024b2f5b1f1434eb5f7d8f4361R1300
Ignore the check for err.



Other locations of the code performed this check:

Https://github.com/denisenkom/go-mssqldb/blob/2d2afc3cb635276d25ae5ac75a9c883efea7058e/mssql.go#L345

Https://github.com/denisenkom/go-mssqldb/blob/78a11f640437e0807f8bf101411762c8adbe7574/bulkcopy.go#L228

**Comment by kardianos** [comment]
Sweet! Thanks for the detailed steps!
