### ISSUE TITLE
Connection drop by remote server, Windows 7

### ISSUE THREAD

**Issue by VimalKumarS** [denisenkom/go-mssqldb#220]
hi

I am getting error, connection drop by remote server when using db.query (..) , when trying to connect from windows machine to sql server 2012.
Any possible hint ? what could be the issue.

thanks
Vimal

**Comment by kardianos** [comment]
Are you using encryption? SQL auth or Windows authentication?

**Comment by VimalKumarS** [comment]
Yes using Windows Authentication.
Though in the connection string i have to provide user name and password to connect to DB and ping it.
Encryption i have set to disable.
This happen when connect to to remote DB, but local host it work perfectly.

**Comment by kardianos** [comment]
@VimalKumarS For me to pursue this I would need more information. Does the server connection drop right away, after auth, or sometime in the middle? How reliable is your network connection? How far apart are the client and server physically?

**Comment by kardianos** [comment]
We have updated the default timeout to not be 30 sec. Also other improvements have been made. Maybe try again at tip if still an issue.
