### ISSUE TITLE
Invalid object name dbo.table

### ISSUE THREAD

**Issue by joseluisbsa** [denisenkom/go-mssqldb#223]
Hi everybody.

I don't know more what I can do. 

What's wrong with my code?

`   
        package main

    import (
	_ "github.com/denisenkom/go-mssqldb"
	"database/sql"
 	"log"
 	"fmt"
    )

    func main() {
	connectionDB() 
    }

    func connectionDB() {

    log.Println("Main:")

    log.Println("Opening")

    db, err := sql.Open("mssql", "server=pwbt.database.windows.net;Initial Catalog=dbo;user id=admin-jose;password=password")

    if err != nil {
        log.Println("Open Failed: ", err.Error())
    }

    log.Println("Opened")

    log.Println("Pinging")
    
    err = db.Ping();
    if err != nil {
        log.Println("Failed to ping: ", err.Error())
    }

    log.Println("Pinged")
    
	x := 2
	rows, err := db.Query("select Nome from dbo.tbPessoa where Id=?", x)
	if err != nil {
	        log.Fatal(err)
	}

	defer rows.Close()
	defer db.Close()	
	fmt.Println(rows)
	fmt.Printf("bye\n")
        }
`

It can connect but can't select.  

Return:
C:\Go\bin\go.exe run B:\go\gocode\src\main\connect-bd.go
2017/02/25 15:52:47 Main:
2017/02/25 15:52:47 Opening
2017/02/25 15:52:47 Opened
2017/02/25 15:52:47 Pinging
2017/02/25 15:52:48 Pinged
2017/02/25 15:52:48 mssql: Invalid object name 'dbo.tbPessoa'.
exit status 1

![select-golang](https://cloud.githubusercontent.com/assets/26029170/23333897/eee8c5de-fb72-11e6-9f3f-e5552f3f8ea8.PNG)

**Comment by joseluisbsa** [comment]
![select-golang](https://cloud.githubusercontent.com/assets/26029170/23333889/c8589840-fb72-11e6-9928-4be832a623c3.PNG)

**Comment by kardianos** [comment]
Looks like you aren't setting the database name correctly and it is
defaulting to the master database. That would be my guess.

**Comment by joseluisbsa** [comment]
@kardianos thanks so much!

You're right! I add the "database=PWBT" on connect string and it works!

It look like this way: 
`db, err := sql.Open("mssql", "server=pwbt.database.windows.net;user id=admin-jose;password=password;database=PWBT;port=1433")`
