### ISSUE TITLE
Probably strange connection leak when Query and Exec

### ISSUE THREAD

**Issue by AntonKrutikov** [denisenkom/go-mssqldb#237]
I have strange issue with golang sql and probably your driver.

My code part:

    func Auth(username string, password string, remote_ip string, user_agent string) (string, User, error) {
    var token string
    var user = User{}

    query := `exec dbo.sp_get_user ?,?`

    rows, err := DB.Query(query, username, password)
    if err != nil {
        return token, user, err
    }
    defer rows.Close()

    rows.Next()
    if err = rows.Scan(&user.Id, &user.Username, &user.Description); err != nil {
        log.Printf("SQL SCAN: Failed scan User in Auth. %v \n", err)
        return token, user, err
    }

    hashFunc := md5.New()
    hashFunc.Write([]byte(username + time.Now().String()))

    token = hex.EncodeToString(hashFunc.Sum(nil))

    query = `exec dbo.sp_set_session ?,?,?,?`

    _, err = DB.Exec(query, user.Id, token, remote_ip, user_agent)
    if err != nil {
        return token, user, err
    }

    return token, user, nil
    }

Problem: `defer rows.Close()` - not working properly

After this with `DB.Connection.Stats().OpenConnections` I always have 2 connection opened (also after repeat User login is still 2 connection for whole app lifecycle)

But if I rewrite func as:

    ...
    query := `exec dbo.sp_get_user ?,?`

    rows, err := DB.Query(query, username, password)
    if err != nil {
        return token, user, err
    }
    defer rows.Close()

    rows.Next()
    if err = rows.Scan(&user.Id, &user.Username, &user.Description); err != nil {
        log.Printf("SQL SCAN: Failed scan User in Auth. %v \n", err)
        return token, user, err
    }

    rows.Close()
    ...
Then rows underline stmt is closed and next `DB.Connection.Stats().OpenConnections` always will be 1 connection open.

DB in my app is simply return underlying connection from sql.Open

Problem is only in this part where two query executions with Query and Exec in one functions.

Maybe Query and Exec defines different connections, but i don't find this in driver source or database/sql source.

Thank you! (sorry for english if it's so bad)

PS:

`exec dbo.sp_get_user ?,?` - is simple select from user table, not more.

`exec dbo.sp_set_session ?,?,?,?` - is simple insert to user table, not more

In MSSQL - `DBCC INPUTBUFFER` shows me query = 'cast(@@identity as bigint)' which executes in your mssql.go on line 593

**Comment by kardianos** [comment]
Unsure if you have a problem.

A connection leak means connection to the database grows the more you use it. What you are seeing looks like connection pooling, which is what database/sql is designed to do; keep connections alive so they can be reused quickly later.

Can you confirm one way or another?

**Comment by AntonKrutikov** [comment]
@kardianos Thank you for reply. I think it's some kind of pooling, but I don't understand why it different for `Exec` and `Query`.

For example in this app I have more queries like `exec dbo.sp_cards @id=?` and `exec dbo.sp_cards_detail @id=?` which by logic must create prepared stmt for reusing, but they not create separate connections (in my app without `Auth` which only using Exec not Query - same connection is reusing for all statements).

All my func same like this:

    func GetCard(id int) (Card, error) {

	var card Card

	query := `exec dbo.sp_card @id=?`

	rows, err := DB.Query(query, id)
	if err != nil {
		return card, err
	}
	defer rows.Close()

	rows.Next()
	if card, err = cardRowScan(rows); err != nil {
		return card, err
	}

	return card, nil
    }

And problem gone away then I `Close()` rows not in defer, but just after first `Scan()` (before `Exec` in same func).

Sorry if I not understand some concepts, but I want to know why it's happens.
Thank you.

**Comment by kardianos** [comment]
If you `defer rows.Close` the rows will be closed *after* the end of the function. Does that help at all? Sorry, shooting in the dark here.

**Comment by eliveikis** [comment]
@AntonKrutikov did you ever get to the bottom of this? I seem to be observing a similar leak, but with the postgres driver. It appears to be rare and inconsistent, but I have the same scenario - I have observed it only in cases where I am first fetching rows and then following with an exec query in the same function.
