### ISSUE TITLE
Enable download count for go package?

### ISSUE THREAD

**Issue by LuisBosquez** [denisenkom/go-mssqldb#239]
Is there any way to get the download numbers for this connector? 

I believe there is a setting to enable keeping track of the downloads from github. Would it be possible to enable it?

**Comment by kardianos** [comment]
Not that I'm aware of. Internally there is a github clone count, right now I think this driver is around 1.4k unique clones per months. But many people will also simply clone once, then keep the source code in the needed repo or in GOPATH. Other people won't store the source locally and count a clone for just the CI build and each dev. So while it isn't without merit, I wouldn't put too much stock in it.

Why are you asking for it?
