### ISSUE TITLE
NamedArg @ notation

### ISSUE THREAD

**Issue by TaylorBarrick** [denisenkom/go-mssqldb#242]
The package sql.NamedArg docs show the use of the @param1 style of NamedArgs, and the go-mssqldb readme also mentions the @ notation , but it is not accepted as an input to a query.

It seems that the parser.go parseNormal func is skipping the '@' character.  When adding it as an option, it solves certain conditions, but gets picked up when testing queries with T-SQL local variables using the @ prefix. (i.e. DECLARE @tblVar TABLE...)

Is there a preferred way to  distinguish these T-SQL variables from the driver supplied args?  If not, should they be avoided, and rather use the $ and : notations only?  And should the readme indicate such?

**Comment by kardianos** [comment]
I don't fully understand your question. But does this example help?
```
db, err := sql.Open("sqlserver", "...")
sqltext := "select * from Invoice where ID = @ID;"
rows, err := db.QueryContext(ctx, sqltext, sql.Named("ID", 998))
```

**Comment by TaylorBarrick** [comment]
So given these examples:

	if _, err = db.QueryContext(ctx, "Select [name] from sys.tables where max_column_id_used > $val;", sql.Named("val", 9)); err != nil {
		panic(err)
	}
	fmt.Println("$ OK")

	if _, err = db.QueryContext(ctx, "Select [name] from sys.tables where max_column_id_used > :val;", sql.Named("val", 9)); err != nil {
		panic(err)
	}
	fmt.Println(": OK")

	if _, err = db.QueryContext(ctx, "Select [name] from sys.tables where max_column_id_used > @val;", sql.Named("val", 9)); err != nil {
		panic(err)
	}
	fmt.Println("@ OK")

I am always getting the following:

	$ OK
	: OK
	panic: sql: statement expects 0 inputs; got 1

**Comment by dimdin** [comment]
You can use "sqlserver" or "mssql" for driver name, but there is a difference:
"mssql" expects positional parameters and translates the ? ?n $n :n parameters to @p1, @p2, etc.
"sqlserver" does not translate parameters, so you can use named parameters as @name

**Comment by kardianos** [comment]
```
db, err := sql.Open("sqlserver", "...") // Not "mssql"
```

**Comment by TaylorBarrick** [comment]
Ah excellent, that works.  My mistake, thanks!
