### ISSUE TITLE
odbc sqlserver connect error No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by xkeyideal** [denisenkom/go-mssqldb#248]
odbc & sqlserver Error Info : 
Unable to open tcp connection with host 'localhost:1433': dial tcp [::1]:1433: connectex: No connection could be made because the target machine actively refused it.

ado just add encrypt=disable can connect success

windows 10 OS
golang 1.7.4

**Comment by kardianos** [comment]
Does the server support encryption? What does the sql server logs say? What version of SQL server are you using?

**Comment by xkeyideal** [comment]
sql server version is 2008 R2.

this my code
`
package main

import (
	"database/sql"
	"fmt"
	"net/url"

	_ "github.com/denisenkom/go-mssqldb"
)

func main_mssql() {
	query := url.Values{}
	query.Add("database", "test")
	u := &url.URL{
		Scheme: "sqlserver",
		User:   url.UserPassword("sa", "123qwe!@#"),
		Host:   fmt.Sprintf("%s", "10.101.22.65"),
		// Path:  instance, // if connecting to an instance instead of a port
		RawQuery: query.Encode(),
	}
	dsn := u.String()
	fmt.Println(dsn)

	//dsn3 := "sqlserver://gotest:gotest@10.100.41.15?database=gotest"
	//dsn3 := "server=10.100.41.15;user id=gotest;password=gotest;database=gotest;port=1433"
	dsn3 := "server=10.101.22.65;user id=sa;password=123qwe!@#;database=test"
	db, err := sql.Open("mssql", dsn3)
	if err != nil {
		fmt.Println(err)
	} else {
		err = db.Ping()
		if err != nil {
			fmt.Println(2, err)
		} else {
			fmt.Println("Ok")
		}
		//		rows, _ := db.Query("select * from test")
		//		fmt.Println(helpers.Rows2Strings(rows))
	}

}
`

**Comment by xkeyideal** [comment]
It's been too long, I had solve the problem by using ADO.

I remember support encryption, but I must set the encrypt = true.
