### ISSUE TITLE
Can't use temporary tables

### ISSUE THREAD

**Issue by dnp1** [denisenkom/go-mssqldb#249]
Consider the following code:
```go
// ...
func main ()  {
// ....
     tx, _ := db.Begin() 
     tx.Exec(`select * from a into #b;`)
     if rows, err := tx.Query(`select * from #b;`); err != nil {
         log.Print(err)
     }
//...
}
```
I'm getting the error **mssql: Invalid object name '#fah_transaction_installments'** 

Is this really the expected?

**Comment by kardianos** [comment]
Can you check for errors?

**Comment by daniloanp** [comment]
Actually the code below works: 

```go
func test0 (db *sql.DB) {
    if tx, err := db.Begin(); err != nil {
        log.Print("0:", err)
        return
    } else if _,err :=  tx.Exec(`select name from a into #b WHERE name LIKE '%foo%';`); err != nil {
        log.Print("1:", err)
        return
    } else if rows, err := tx.Query(`select * from #b;`); err != nil {
        log.Print("2:", err)
    } else {
        var name string
        for rows.Next() {
            rows.Scan(&name)
            fmt.Println("Name:", name)
        }
    }
}
```

But this other code ends with:  "mssql: Invalid object name '#b'.":

```go
func test1 (db *sql.DB) {
    if tx, err := db.Begin(); err != nil {
        log.Print("0:", err)
        return
    } else if _,err :=  tx.Exec(`select name from a into #b WHERE name LIKE :named ;` , sql.Named("named", '%foo%')); err != nil {
        log.Print("1:", err)
        return
    } else if rows, err := tx.Query(`select * from #b;`); err != nil {
        log.Print("2:", err)
    } else {
        var name string
        for rows.Next() {
            rows.Scan(&name)
            fmt.Println("Name:", name)
        }
    }
}

Looks like a issue related to sql.Named...
When I run both "selects" with one db.Query everything works.

But in my real code I need pagination;

**Comment by kardianos** [comment]
I don't think that will compile... in the Named, you probably want a string as a value, see below:
`sql.Named("named", "'%foo%'")`

Also, If you do early returns you can drop the else.

**Comment by dimdin** [comment]
In the SQL statement use `@named` instead of `:named`

**Comment by daniloanp** [comment]
@kardianos Now it compiled.

@dimdin When I replace :named to @named I get "sql: statement expects 0 inputs; got 1"

**Comment by dimdin** [comment]
To use named parameters you must have "sqlserver" for the driver name instead of "mssql"

**Comment by daniloanp** [comment]
Ok, now the named parameter using @ works (before It was working with ":")

Again, the "mssql: Invalid object name '#b'." occurs when I use parameters.

**Comment by dimdin** [comment]
The driver is using the sp_executesql to execute SQL statements with parameters, without parameters the SQL statement is executed directly. Perhaps the temporary table #b is dropped after sp_executesql finishes.

**Comment by daniloanp** [comment]
You're right, @dimdin.

But  about the driver, what should be the expected behaviour?

http://stackoverflow.com/questions/8040105/execute-sp-executesql-for-select-into-table-but-cant-select-out-temp-table-da
