### ISSUE TITLE
read: connection reset by peer

### ISSUE THREAD

**Issue by viney** [denisenkom/go-mssqldb#253]
go run simple.go

password:123456
 port:1433
 server:192.168.1.68
 user:sa
 connString:server=192.168.1.68;user id=sa;password=123456;port=1433
2017/04/17 10:02:42 Prepare failed:Login error: read tcp 192.168.1.63:49462->192.168.1.68:1433: read: connection reset by peer
exit status 1

use Navicat Premium is success

**Comment by viney** [comment]
Add "encrypt=disable" parameter to fix this issue.

close

**Comment by brapastor** [comment]
example please :) @viney
