### ISSUE TITLE
Execute Multiple queries

### ISSUE THREAD

**Issue by casamm** [denisenkom/go-mssqldb#254]
Is it possible to execute multiple sql queries in a single execution? 

Passing auto generated Id to the referenced table in the following example. 

```
query := "INSERT INTO ChatMessage(Message) VALUES(?);
INSERT INTO CHAT(TO, FROM, MESSAGE_ID) VALUES(?, ?, SELECT SCOPE_IDENTITY())"

statement, err := conn.Prepare(query)
_, err = statement.Exec("Hi", 1, 2)
```

Connection String is as follows

`var ConnectionString = fmt.Sprintf("server=%s;user id=%s;password=%s;database=%s;port=%d", "host, "username", "pass", "database", 1433)`

**Comment by kardianos** [comment]
Try it. yes.
With go1.8 you can even select multiple queries in a single query text.

**Comment by casamm** [comment]
actually I should have been clear, it's throwing an error, so wondering if there's something wrong with the code. I'm using v 1.8.

**Comment by kardianos** [comment]
Okay, what's the error?

**Comment by casamm** [comment]
Sorry for delay on this... The error is 

    mssql: Incorrect syntax near ')'.

**Comment by kardianos** [comment]
You have a syntax error. 

You could try
`INSERT INTO CHAT(TO, FROM, MESSAGE_ID) VALUES(?, ?, (SELECT SCOPE_IDENTITY()))`
or declare a temp var or similar.

Not a bug in this driver.

**Comment by casamm** [comment]
Thanks @kardianos, not only that I had to quote To and From since they are reserved words. For reference.

`INSERT` INTO CHAT([TO], [FROM], MESSAGE_ID) VALUES(?, ?, (SELECT SCOPE_IDENTITY()))

Thanks again for your help.
