### ISSUE TITLE
Executing a T-SQL file from Go?

### ISSUE THREAD

**Issue by LuisBosquez** [denisenkom/go-mssqldb#256]
Is there any way to run a .sql file from Go and execute using go-mssqldb?

I am looking for something like a function that will receive a path to a file and execute the T-SQL on an existing connection.

**Comment by kardianos** [comment]
Sure, read a file with ioutil, and execute the content.

If the file contains GO statements, you might need something like: https://godoc.org/bitbucket.org/kardianos/rdb/ms/batch#BatchSplitSql (in the future plan to have a similar function in this package).

**Comment by LuisBosquez** [comment]
thanks @kardianos!

**Comment by kardianos** [comment]
Actually, let me get those into this driver sooner than later. Please watch https://github.com/denisenkom/go-mssqldb/issues/186 for more details.

**Comment by LuisBosquez** [comment]
What function would you recommend to execute the TSQL? The file would contain multiple lines of non-query statements (no result sets will be read from them).

**Comment by kardianos** [comment]
There is a new sub package called batch with a Split function that will split on GO and escape newlines with backslash in strings.

There is no helper function to read the file so wote a short helper function using io/ioutil
