### ISSUE TITLE
$action keyword in MERGE OUTPUT clause broken

### ISSUE THREAD

**Issue by johnweldon** [denisenkom/go-mssqldb#258]
`$action` is treated as a named parameter and thus doesn't work in an `OUTPUT` clause of a `MERGE` statement.

At the end of this section is the documentation for `$action`:

https://docs.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql#arguments

**Comment by kardianos** [comment]
I'm assuming you're using sql.Open("mssql", "DSN").
What you want is sql.Open("sqlserver", "DSN"). This will not do parameter replacement at all.

**Comment by johnweldon** [comment]
Ah, interesting. Wouldn't this still be a bug with "mssql" though?

**Comment by kardianos** [comment]
Yes. The question is, is mssql supported? I've opened an issue (linked above) to decide that. Probably a question for @dimdin or @denisenkom .

**Comment by kardianos** [comment]
@johnweldon The consensus is to drop support for the mssql version that processed queries. If it worked for you in the past, use that. If you're writing new queries, use "sqlserver" driver.
