### ISSUE TITLE
proposal: remove almost all mention of "mssql" driver name

### ISSUE THREAD

**Issue by kardianos** [denisenkom/go-mssqldb#260]
Processing the query correctly and replacing parameters is tough. We previously decided against a PR to improve matching for "::" if memory serves. There is a new request and another issue with matching $action.
https://github.com/denisenkom/go-mssqldb/issues/258

Let's update the README and docs and remove almost all mention of "mssql" as a driver name.
In the one place we mention it, we should include a section that it should no longer be used / supported.

**Comment by dimdin** [comment]
I agree to update the README leaving only "sqlserver" and examples with @ parameters only. Let's also add an upgrade note with a reference to a wiki page or a new md file that contains howto instructions for converting "mssql" style to "sqlserver" style sql and parameters; move there the old "mssql" documentation mentioning to use the new style, the problems with old style (:: and $ conflict with money constants) and the decision to end support for "mssql" driver name.
@denisenkom do you agree?

**Comment by denisenkom** [comment]
Agree

**Comment by Omortis** [comment]
Wow. Can anyone provide some sample code that does a Query or a QueryRow with 2 (or more) positional parameters and the sqlserver driver? Not QueryContext?  This is brain-dead simple in pg or mysql but after 2 hours with the sqlserver driver I can't get it to work at all. Note that plain selects work just fine, the connection is good.

**Comment by kardianos** [comment]
In the query text, use `@p1 and @p2`. SQL Server doesn't use positional parameters, just named parameters. But we generate names for positional parameters.

**Comment by Omortis** [comment]
Oh, ok. Excellent - thanks. I can't try it out from home but will do so first thing in the morning. Also, sorry for the over-caffeinated post...

**Comment by Omortis** [comment]
Was afk yesterday but back in action this morning. Still not working, though I'm not sure upon re-reading your post how to do it.

This code:

`rows, err := db.QueryContext(context.TODO(), "select SigCode from @P1 where LRUEmu=@P2;",sql.Named("@P1", string1), sql.Named("@P2", string2))`

generates this error:

fn() rows.Query() failed:name "@P1" does not begin with a letter

and this code: 

`rows, err := db.QueryContext(context.TODO(), "select SigCode from @P1 where LRUEmu=@P2;" , string1, string2)`

generates this error:

fn() rows.Query() failed:mssql: Must declare the table variable "@p1"

If I can sort this out I'll edit the README and commit it.
