### ISSUE TITLE
Any way to declare and use a T-SQL variable between to db calls?

### ISSUE THREAD

**Issue by LuisBosquez** [denisenkom/go-mssqldb#261]
I'm trying to achieve the following:

- I want to declare a Table Type variable that I can insert values into by using the following syntax:
```
DECLARE @table dbo.my_table_type; 
INSERT @table VALUES ("test1"), ("test2");
```
This is easy to do with go-mssqldb:
```
tsql := fmt.Sprintf("DECLARE @table dbo.my_table_type; INSERT @table VALUES ("test1"), ("test2");"
_, err := db.Exec(tsql)
```
- Then afterwards, I'd like to use that declared variable to send it to a stored procedure.
```
EXEC table_storedproc @table;
```
I tried using the following:
```
stmt, err := db.Prepare("EXEC table_storedproc @table, ?, ?;")
if err != nil {
	fmt.Println("Error preparing the procedure: " + err.Error())
	return -1, err
} 
rows, err := stmt.Query(modelName, fraudProbability)
[...]
```

But then I get an error saying that the scalar variable `@table` isn't declared. Is a new session started when I call the Prepare statement? How can I ensure that I can see the variable I declared between calls?

Thanks,
Luis

**Comment by kardianos** [comment]
There are a few issues here. One is that "@" vars are batch scoped. That means that they are limited to the scope of your current SQL text, within the bounds of "GO" statements. The second is that until go1.9 (next release) there is no way to pull a single connection from the driver and use it to preserve session. This was just merged this morning into the go1.9 tree, but that won't be available for another 4 months.

You want a global temp table `##varname` I think.

**Comment by LuisBosquez** [comment]
Thanks @kardianos
