### ISSUE TITLE
Need example writing to DateTime

### ISSUE THREAD

**Issue by jivasoft** [denisenkom/go-mssqldb#262]
Getting a conversion error when writing a time.Time value to MSSQL DateTime column. Would greatly appreciate an example showing what needs to be done to make it work.

**Comment by dimdin** [comment]
```go
import (
    "time"
)

var now time.Time
now = time.Now()
_, err := db.Exec("update Table set DateTimeField = ?", now)
```

**Comment by jivasoft** [comment]
Thank you. I was focused on a date time field I was populating but the error was caused by another field that had a zero value. I really appreciate the quick turnaround.

Daniel Ryan
Jivasoft Corporation
(956) 723-8200
danryan@jivasoft.com
www.jivasoft.com
