### ISSUE TITLE
azure read: connection reset by peer

### ISSUE THREAD

**Issue by regevbr** [denisenkom/go-mssqldb#266]
Hi,

I know there are a lot of azure related bugs in here but none of them gives a solution.
I'm trying to connect to my auzre db:
```
select @@Version
Microsoft SQL Azure (RTM) - 12.0.2000.8   Mar 21 2017 02:11:40   Copyright (C) 2016 Microsoft Corporation. All rights reserved. 
```
with connection string
```
Server=*;Port=1433;User Id=*@8;Password=*;Encrypt=True;TrustServerCertificate=True;log=51;connection timeout=90;dial timeout=60;keepAlive=60;"
```
And all I see in the log is:
```
2017-05-28T21:44:00Z E! Error in plugin [inputs.sqlserver]: read tcp 10.0.0.8:59260-><ip>:11210: read: connection reset by peer
2017-05-28T21:44:00Z E! Error in plugin [inputs.sqlserver]: driver: bad connection
```
The azure firewall is configured properly and the credentials are ok. When I try to use Encrypt=False or Encrypt=disable it failes misserably as well...

Can you please help?

**Comment by kardianos** [comment]
I'm assuming same parameters work on a different client. Your Reed port
looks odd. Can you specify the port on the host colon separated.

**Comment by regevbr** [comment]
Actually, running this connection string directly on your module works fine. Somehow the issue is with the telegraf sqlserver input. I opened a bug there...
https://github.com/influxdata/telegraf/issues/2861
