### ISSUE TITLE
connection reset by peer 

### ISSUE THREAD

**Issue by rbucker** [denisenkom/go-mssqldb#267]
I've been staring at #217 but it offers no real help. My configuration is basically the same.... GOlang version, I'm using the latest go-mssqldb version... but I'll get BeginRead errors like "EOF" or "reset by peer." I tried the "select @@version" but that did not help. 

My difference might be SQL Server (SP1-GDR) 13.0.4202.2
DEC 13 2016

**Comment by rbucker** [comment]
the problem seems to be VERY long SQL strings. No proof yet.

**Comment by kardianos** [comment]
Yes, this does indeed to seem the case. Any long reads, strings or otherwise, seem to trigger this.

I assume we have a bug with the netlib implementation esp under encryption. Looking into this.

**Comment by kardianos** [comment]
See #166 for more details.

**Comment by gabrielclima** [comment]
i was forced `packet size=2048;` in my connection string and works

**Comment by rbucker** [comment]
yep; did the same here. trying to be patient.

**Comment by kardianos** [comment]
I think this has been fixed in tip.
