### ISSUE TITLE
Add support for SSL encryption

### ISSUE THREAD

**Issue by denisenkom** [denisenkom/go-mssqldb#27]
Reference: http://msdn.microsoft.com/en-us/library/dd357559.aspx

**Comment by magmax** [comment]
Hello.

I have this same error: "Login error: EOF"

My scenario is a little different: I'm connecting to Azure SQL from my laptop, and it works (Windows 7), but when I try to connect from a VM in Azure (Windows 2012 R2), it fails. Same binary.

Could you help me with this?

**Comment by denisenkom** [comment]
Do you use same version of Go on both machines?

**Comment by magmax** [comment]
I thought that, so I compiled it and tested it from one of my mates' laptop (without Go installation), and it worked, but in Azure's VM (without Go installation too) it doesn't.

**Comment by perseo-dev** [comment]
I have tha same problem of magmax. I compiled in Windows 8.1 Pro 64bit and I successfully connect to SQL Azure. When I copy the working binary on a new Azure Virtual Machine with Windows Server 2012 R2 the login fail with "Login error: EOF".

**Comment by denisenkom** [comment]
Please enable logging on client and server and upload here

**Comment by srgrn** [comment]
how do i enable logging on the client? i seem to have the same error only in my case it works on my mac and on a windows machine but not on an azure linux vm.

**Comment by denisenkom** [comment]
In connection parameters: https://github.com/denisenkom/go-mssqldb#connection-parameters
see log
