### ISSUE TITLE
Issue on named parameters parsing

### ISSUE THREAD

**Issue by delmorof** [denisenkom/go-mssqldb#273]
After introduction of the named parameters, queries that use static functions fails during parsing of parameters.

## Reproducer code:
```
func TestGeometryFunction(t *testing.T) {
	conn, err := sql.Open("mssql", "server=host\\SQLEXPRESS;database=db;user id=user;password=psw")
	if err != nil {
		t.Error("Open connection failed:", err.Error())
		return
	}
	defer conn.Close()

	_, err = conn.Query("SELECT Geometry::STGeomFromText('LINESTRING(11.086682 43.776442, 11.133341 43.759097)', 4326)")
	if err != nil {
		t.Fatal("Query failed with", err)
	}
}
```

## Failure Message:
`--- FAIL: TestGeometryFunction (0.06s)
        queries_test.go:344: Query failed with sql: statement expects 1 inputs; got 0`

**Comment by kardianos** [comment]
Please use driver name "sqlserver" `conn, err := sql.Open("sqlserver", "...")`
