### ISSUE TITLE
doc: this driver is NOT an ODBC driver

### ISSUE THREAD

**Issue by mickelsonm** [denisenkom/go-mssqldb#276]
Hello. I am trying to setup an ODBC connection using this great library. I have been struggling to get the connection established and have been getting a rather vague message:

>> Login error: driver: bad connection

The connection string I am using looks like this:

```go
	conn, err := sql.Open("sqlserver", `odbc:server=owmsrvdb1\Altaris;database=Altaris;trusted_connection=yes;`)
```
>> Note: When I change the server name to just owmsrvdb1 it seems to go a little farther. Perhaps a bug is revealing itself?

I was able to connect to my database using a python library  (I am hoping to bring Go to the company I work for the very first time, so it would be nice to be able to get going again!), which looked like this:

```python
conn = pypyodbc.connect(
  'Driver={SQL Server};'
  'Server=owmsrvdb1\Altaris;'
  'Database=Altaris;'
  'Trusted_Connection=yes;'
  )
```
Am I missing something? Any and all help appreciated, thanks!

**Comment by ybenjolin** [comment]
I am having the same issue.
`Driver={SQL Server};Server=cdc-edb2;Database=CostarReports;Trusted_Connection=yes;`
This connection string works for me using vba, vbscript, and go using github.com/alexbrainman/odbc.

**Comment by kardianos** [comment]
It is possible that your databases aren't configured to support TCP/IP.
Also, this driver does NOT speak ODBC, it speaks TDS which is what MS SQL Server nativity speaks. 

A better comparison would be to try the connection with an ADO.NET driver to see if you can connect. We won't be able to use an ODBC data source with this driver.
