### ISSUE TITLE
types.go error

### ISSUE THREAD

**Issue by suiyunonghen** [denisenkom/go-mssqldb#279]
The **makeGoLangScanType** function in types.go, sometimes Ti parameters of the TypeId is 61, is a type of time, but the function is not handling and throws an exception, I think this should be in the 927 line 
**case typeDateTimeN** increased for typeDateTime identification, as follows

**Case typeDateTimeN, typeDateTime:**

At the same time, the corresponding **makeDecl** and other functions need to be modified

**Comment by denisenkom** [comment]
Can you provide an example query that fails?  Also what is your version of SQL server?

**Comment by suiyunonghen** [comment]
Not every time Has the problem,Only some times，but No laws have been found yet，i'm use Sqlserver22008R2，when use rows.Columns() get All Select Fields while be panic the error

**Comment by denisenkom** [comment]
I added DATETIME case into makeGoLangScanType function.  That should solve your issue.  If you find a way to reproduce this issue let me know, I would want to add a test for it.
