### ISSUE TITLE
Support for MARS maybe

### ISSUE THREAD

**Issue by denisenkom** [denisenkom/go-mssqldb#28]
Specs: http://msdn.microsoft.com/en-us/library/cc219643.aspx

**Comment by kardianos** [comment]
I've never had a use for multiple active result sets. Normally multiple sequential result sets work just fine. What use cases would require this, and would it benefit the database/sql driver?

**Comment by denisenkom** [comment]
Probably not, I think database/sql manages connections seamlessly enough.
