### ISSUE TITLE
Connectionstring issues

### ISSUE THREAD

**Issue by rajeevb2** [denisenkom/go-mssqldb#283]
I am getting an error for the following connection string
connectstring := "sqlserver://sa:password@localhost:1401?database=testdb&connection+timeout=30"
 
I get the error "no db name provided", when I do

DBengine, err = xorm.NewEngine(dbtype, connectstring)

This is on SQLServer 2017. I can connect to this DB using sqlcmd on the same port

Any ideas?

When I switched to 
connectstring := odbc:server=localhost;user id=sa;password=password;port=1401;database=testdb;connection timeout=30

it worked

**Comment by kardianos** [comment]
No idea. Maybe your database name needs to be URL encoded for the first method?

**Comment by matriphe** [comment]
I just encountered with this same issue.

**Comment by kardianos** [comment]
Can you replicate this issue without xorm? Are you sure this is a driver issue?

**Comment by matriphe** [comment]
I had SQL Server 2017 Running via Docker, and mapped to port 1401. I used the same DSN string on Gorm and running well, but it didn't work in Xorm.

```go
type DbConfig struct {
	Host     string
	User     string
	Password string
	Database string
	Port     uint64
}

func (c *DbConfig) encodePassword() {
	c.Password = url.QueryEscape(c.Password)
	c.Port = uint64(c.Port)
}

c := DbConfig{
	Host: "127.0.0.1"
	User: "sa"
	Password: "4wesomep4ssword"
	Database: "MY_DATABASE"
	Port: 1401
}

// return error `no db name provided`
conn := fmt.Sprintf("sqlserver://%s:%s@%s:%d?database=%s", c.User, c.Password, c.Host, c.Port, c.Database)
engine, err := xorm.NewEngine("mssql", conn)

// this worked
conn := fmt.Sprintf("odbc:server=%s;user id=%s;password=%s;port=%d;database=%s", c.Host, c.User, c.Password, c.Port, c.Database)
engine, err := xorm.NewEngine("mssql", conn)
```
I use official SQL Server Docker from Microsoft.

I came here from googling `no db name provided`. If you're thinking this is a Xorm issue, I'll open issue there.

**Comment by kardianos** [comment]
Unless you can reproduce it without xorm I'm not going to consider this driver's issue.
