### ISSUE TITLE
Kerberos access to SQL failing with Login error: mssql: Login failed for user ''.

### ISSUE THREAD

**Issue by gawth** [denisenkom/go-mssqldb#285]
Hi,

not sure if this is a bug or a miss-configuration on my part but I could do with some help.

I have a Centos 7 desktop that I am trying to connect SQL with using Kerberos.

I am using the following very noddy test to check connectivity.  This works fine if I specify my user and password but fails (complains about blank user) if I omit them and rely on my Kerberos ticket (which is valid).  This test works if I use the gofreetds lib (which I don't really want to have to use due to need for freetds install).

So, I am happy my computer is in the domain, that I can connect to the DB and that my Kerberos config is correct...suggestions?

```

func main() {
    connString := "server=SERVERNAME;database=DB"

    conn, err := sql.Open("mssql", connString)
    if err != nil {
        panic(err)
    }
    defer conn.Close()
    fmt.Println("Connected :-)")

    rows, err := conn.Query(`SELECT 'Test'`)
    if err != nil {
        panic(err)
    }

    defer rows.Close()

    fmt.Println("Got some data :-)")

}

```

Thanks,
Alan

**Comment by maxzerbini** [comment]
I've a similar issue. Using a connection string like @gawth but putting also the "user id=<myuser>" parameter and using a keytab file for that user, I obtain this error message "Login error: mssql: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication." 

Also setting the ServerSPN DSN parameter nothing changes.

Does this driver support Kerberos auth ?

Thanks & Regards,
Massimo

**Comment by kardianos** [comment]
kerberos v1 only

**Comment by maxzerbini** [comment]
Hi @kardianos,

can you provide an example or explane how to use kerberos v1 auth with this driver on a Linux host?

Thanks,
Massimo

**Comment by kardianos** [comment]
Ah, looks like "windows auth" is Windows only at this time https://github.com/denisenkom/go-mssqldb/blob/master/sspi_windows.go

I was mistaken. I haven't read that part of the driver much.
Maybe in the future we can support go native kerberos.

**Comment by kardianos** [comment]
Would like to support it in the future: https://github.com/denisenkom/go-mssqldb/issues/383

**Comment by keith6014** [comment]
seem like this is a very important feature for enterprises.
