### ISSUE TITLE
Do you use sp_reset_connection before reusing a connection in the connection pool ?

### ISSUE THREAD

**Issue by Tkanos** [denisenkom/go-mssqldb#286]
Hello ,

Do you use sp_reset_connection before reusing a connection in the connection pool ?

Thanks,

links : 
- http://sqlmag.com/sql-server/spresetconnection-procedure
- https://stackoverflow.com/a/2924456

**Comment by Tkanos** [comment]
Let me be more specific on my question.
When we reuse a connection sql server has a mechanism to call an internal procedure sp_reset_connection, that will "clean" the connection to be reuse. (cf https://stackoverflow.com/a/2924456)

In order to call this internal procedure, When the client reuses the connection again, instead of logging on, the first batch of sQL executed causes a RESETCONNECTION bit to be set on the first TDS packet to the sent (there is also a related RESETCONNECTIONSKIPTRANSACTION bit, but that's not relevent for this discussion). This causes SQL Server to run the system stored procedure sp_reset_connection on the server's session.

- https://www.sqlskills.com/blogs/bobb/sql-server-and-pooled-vs-non-pooled-connections/
- https://www.red-gate.com/simple-talk/sql/learn-sql-server/improving-the-quality-of-sql-server-database-connections-in-the-cloud/

I don't think it's implemented. I will check what we can do, and i will create a PR, for this case.

**Comment by kardianos** [comment]
Thank you for pointing this out. To do this correctly I think we will need database/sql to provide it with a little more information. Let me look into that.

**Comment by kardianos** [comment]
Yes.

**Comment by kardianos** [comment]
This is in Go1.10. Closed in favor of #329 .
