### ISSUE TITLE
Question: Query Parameters MS SQL Server 

### ISSUE THREAD

**Issue by gsigler** [denisenkom/go-mssqldb#287]
I can't seem to get statement parameters to work no matter which way I try. 

This code works 
`row := d.conn.QueryRow(fmt.Sprintf("SELECT * FROM Media WHERE MediaId='%s'", mediaID))`

but all of these throw different errors. 
`row := d.conn.QueryRow("SELECT * FROM Media WHERE MediaId=@mediaID", sql.Named("@mediaID", mediaID))` = name "@mediaID" does not begin with a letter

`row := d.conn.QueryRow("SELECT * FROM Media WHERE MediaId=?", mediaID)` = mssql: Incorrect syntax near '?'.

`row := d.conn.QueryRow("SELECT * FROM Media WHERE MediaId=@mediaID", mediaID)` = mssql: Must declare the scalar variable "@mediaID".

 `row := d.conn.QueryRow("SELECT * FROM Media WHERE MediaId=$mediaID", mediaID)` = mssql: Invalid pseudocolumn "$mediaID".

`row := d.conn.QueryRow("SELECT * FROM Media WHERE MediaId=$mediaID", sql.Named("$mediaID", mediaID))` = name "$mediaID" does not begin with a letter

Could someone please provide me with some clarity as to how I should use QueryRow with parameters?

**Comment by gillescpp** [comment]
This works for me (windows, sql express 2016, go 1.8.1).

    //with "?"
    name := ""
    row := dbCfg.QueryRow("select top 1 name from sys.tables where type_desc=? ", "USER_TABLE")
    err = row.Scan(&name)
    if err != nil {
    	panic(err)
    }
    fmt.Println("name1=", name)
    
    //with ":"
    row = dbCfg.QueryRow("select top 1 name from sys.tables where type_desc= :typedesc ",
    	sql.NamedArg{
    		Name:  "typedesc",
    		Value: "USER_TABLE",
    	})
	//or sql.Named("typedesc", "USER_TABLE")
    err = row.Scan(&name)
    if err != nil {
    	panic(err)
    }
    fmt.Println("name2=", name)

**Comment by kardianos** [comment]
```
row := d.conn.QueryRow("SELECT * FROM Media WHERE MediaId=@mediaID", sql.Named("mediaID", mediaID))
```
