### ISSUE TITLE
"Scan error on column" when scanning DATETIME values

### ISSUE THREAD

**Issue by luistm** [denisenkom/go-mssqldb#297]
Hi,
I'm having this error while scanning an mssql server table:

`Scan error on column index 8: unsupported Scan, storing driver.Value type time.Time into type *sql.RawBytes`

Is it common? Does anyone knows of a solution for this? 

The MSSQL server is in a container, [https://hub.docker.com/r/microsoft/mssql-server-linux/](url) and the version is Microsoft SQL Server 2017 (RC2) - 14.0.900.75 (X64)

The table field is a DATETIME. 
The code I'm using to scan:

    vals := make([]interface{}, len(cols))
	for i := range cols {
		vals[i] = new(sql.RawBytes)
	}

	for rows.Next() {
		err := rows.Scan(vals...)
		if err != nil {
			return nil, fmt.Errorf("Scan failed: %s", err.Error())
		}
     }

Thanks

**Comment by luistm** [comment]
Found a solution, looks like in order to read a DATETIME field I need to use a time.Time field. 

Thanks

**Comment by kardianos** [comment]
This will be possible in go1.10 FYI.
