### ISSUE TITLE
How to specify the type of Named Parameter

### ISSUE THREAD

**Issue by VenuMeda** [denisenkom/go-mssqldb#306]
For instance, I have employee ID defined as NVARCHAR(20) in data model on the server, but when I used the select query, for example. i.e select employee_id, depot from emp where employee_id = @employee_id, then if 'E1234567' is passed, then query get's translated into @employee_id to 
 be NVARCHAR(8) rather than NVARCHAR(20). 

If employee_id is primary key, the input to the server is of type NVARCHAR(8), query results in full table scan rather than seek as NVARCHAR(8)  & NVARCHAR(20) are differnt type, there'd be implicit conversion . Is there anyway to specify the type length for the NamedValue parameters.

something like db.Query(query, sql.Named("EMPID", "E1234567", 20 /* len of NVARCHAR*/) so that EMPID will be VARCHAR(20) rather than NVARCHAR(8). As of now, NVARCHAR(length of the string param) is the type of the Named Value Parameter.

**Comment by denisenkom** [comment]
This should work:
select * from tbl where employee_id = cast(@employee_id as nvarchar(20))
