### ISSUE TITLE
Is it possible mssql procedure?

### ISSUE THREAD

**Issue by jjkim0816** [denisenkom/go-mssqldb#311]
Hi, My name is Kim Jeong Jin in South Korea~
I want to use procedure when it process CRUD.
So, is it possible to support in library?
Do you mind if you provide me example source code?
I appreciate you take your time~
Have a nice day~

**Comment by kardianos** [comment]
Hello,

Which part are you having trouble with?

You'll need to import this package like:
```
import (
    "database/sql"
   _ "github.com/denisenkom/go-mssqldb"
)
```
to provide the actual driver.

Then use the `db, err := sql.Open("sqlserver", "sqlserver://u:p@hostname/instance?database=dbname")`. Once "open" you can run a proc by just providing the name, like: `rows, err := db.QueryContext(ctx, "MyProcName", sql.Named("P1", "value"), sql.Named("AnotherParam", 1234))`

**Comment by jjkim0816** [comment]
Thank you Kardianos~^^

**Comment by zhaohansprt** [comment]
i  write my proc call   code like above you teach  but  get  the panic 
 

>  sql: statement expects 0 inputs; got 5
