### ISSUE TITLE
Stored Procedure Input Parameters Won't Work

### ISSUE THREAD

**Issue by Invictus321** [denisenkom/go-mssqldb#315]
I'm trying to provide an input parameter to a stored procedure, like so:

`rows, err := db.QueryContext(
		ctx,
		"STORED_PROCEDURE_NAME",
		sql.Named("PARAM_NAME", 123),
	)`

But I get this error:

`sql: expected 0 arguments, got 1`

I am connecting to a mssql server.

How is this supposed to work?

**Comment by kardianos** [comment]
I've got to fix the docs. That's been on my list.
Please use the "sqlserver" driver name (not the "mssql" driver name")

`sql.Open("sqlserver", dsn)`

**Comment by Invictus321** [comment]
Ah, that fixed it! Thanks
