### ISSUE TITLE
Failure when restoring database

### ISSUE THREAD

**Issue by matthewswain** [denisenkom/go-mssqldb#317]
I've been writing a small utility that restores databases but have run into an issue.

For example:
```
query := "restore database [test] from disk = 'C:\test.bak'"
_, err := db.Exec(query)
if err != nil {
    panic(err)
}
```
Here, no panic occurs but the restore is not completed and the database is left in the `Restoring...` state. 

I suspect this might have something to do with the messages returned by SQL Server towards the end of the restore, e.g. `Processed 158327 pages for database 'test', [...]` being interpreted by the client as "query complete" because:
- the db.Exec call takes roughly the length of time that I'd expect for a few different backup sizes and
- the database being left in the `Restoring...` state is normal behaviour if the client disconnects prematurely

**Comment by matthewswain** [comment]
This occurs with SQL Server 2016. Setting `SET NOCOUNT ON` doesn't help, but that does not prevent SQL Server returning messages for restores.

**Comment by matthewswain** [comment]
In odbc/odbcstmt.go, making the following change (while obviously a hack) prevents the issue from occurring. 
```
	ret := api.SQLExecute(s.h)
	if ret == api.SQL_NO_DATA {
		// success but no data to report
		return nil
	}
	if IsError(ret) {
		return NewError("SQLExecute", s.h)
	}
+	if ret == api.SQL_SUCCESS_WITH_INFO {
+		time.Sleep(10 * time.Second)
+	}
	return nil
```
This allows time for the restore to complete before returning, suggesting it could indeed be a premature closing of the connection.

**Comment by kardianos** [comment]
Thank you for the information. We'll need to look into it.

**Comment by matthewswain** [comment]
Opened in error.
