### ISSUE TITLE
unsupported type from server string=xxxx

### ISSUE THREAD

**Issue by zhaohansprt** [denisenkom/go-mssqldb#318]
What version of Go are you using (go version)?

1.9.2

**I used go/database/sql and "github.com/denisenkom/go-mssqldb" called a sql server 2012sp3 's proc with output param as the sql.Out example shows as below:**

 ```
 var strErrorDescribe string
        _, err = db.GetmyssqlDB().ExecContext(context.Background(), "NET_PW_InsureIn",
            sql.Named("dwUserID", m.UserId),
            sql.Named("dwScore", m.MoneyAmount),
            sql.Named("strErrorDescribe", sql.Out{Dest: &strErrorDescribe}))
```
strErrorDescribe is the NVARCHAR(127) OUTPUT param
but i got err as

> unsupported type from server string=充值成功

and the strErrorDescribe returned value is ""

What did you expect to see?

strErrorDescribe should contain "charge successed" as returned value

What did you see instead?

the strErrorDescribe returned value is ""

**Comment by zhaohansprt** [comment]
@kardianos So now it support the uvarchar output ?  should i close the issue?

**Comment by kardianos** [comment]
Maybe test, confirm, and close.

**Comment by zhaohansprt** [comment]
tested it worked

**Comment by zhaohansprt** [comment]
@kardianos   by the way how to get the sp's return code

**Comment by kardianos** [comment]
I don't know of a great way in SQL server. I've looked, ended up using
something else.

**Comment by zhaohansprt** [comment]
thanks anyway
