### ISSUE TITLE
Executing Procedure

### ISSUE THREAD

**Issue by jorgelub12** [denisenkom/go-mssqldb#322]
Hello, so what I'm trying to do is executing a stored procedure in MSSQL2016. The procedure returns a JSON with the new function "FOR JSON PATH". The issue is that I can't bind input parameters like this.

```
var result string
	results, err := db.Query("EXEC CLIENT_GET ?", "CC")
	if err != nil {
		fmt.Println("Procedured failed..")
		fmt.Println(err)
	} else {
		fmt.Println("Procedured executed successfully")
	}
```

It keeps me returning this error:

Procedured failed..
mssql: Incorrect syntax near '?'.
2017/12/06 12:57:53 http: panic serving [::1]:55382: runtime error: invalid memory address or nil pointer dereference

**Comment by syklevin** [comment]
i suggest you use 'sqlserver' scheme, and pass named parameter based on your store procedure parameters' name  , assuming your sp first input parameter named 'ID':
```
db, err := sql.Open("sqlserver", connectionString)

results, err := db.Query("CLIENT_GET", sql.Named("ID", 6))
```

**Comment by kylechadha** [comment]
Unfortunately for us named parameters aren't an option as we have to support an older version of go. Is there an alternative solution? Many thanks

**Comment by kylechadha** [comment]
When using `?` syntax, I was seeing the following:
```2018/02/27 15:44:18 exec dbo.PR_Retrieve_Details @XMLParam = ?
2018/02/27 15:44:18 	@p1	{ 1 <RetrieveDetailRequest>
	<Users StartTime="2017-12-12T00:00:00.000Z" EndTime="2017-12-13T00:00:00.000Z">
		<User Email="xxxuser17@stest.com"></User>
		<User Email="xxxuser21@stest.com"></User>
	</Users>
</RetrieveDetailRequest>}
2018/02/27 15:44:18 Incorrect syntax near '?'.```

As such, I was able to make it work with the following:

```
	query := "exec dbo.PR_Retrieve_Data @XMLParam = @p1"
	rows, err := db.Query(query, string(xmlParam))
```

Any feedback on the validity of my solution? Should I expect this to work another way?

**Comment by kardianos** [comment]
Yes, using `@pN` syntax is valid.
