### ISSUE TITLE
Cannot get out parameter from stored procedure

### ISSUE THREAD

**Issue by kvknyazev** [denisenkom/go-mssqldb#323]
Hi!
I'm trying to execure sp and get output value like this
...
	res, err := db.Exec("exec Config_GetParamValue @Name=:Name, @Default='', @Value=:Value output", sql.Named("Name", "LastUpdateTime"), sql.Named("Value", sql.Out{Dest: &prmValue}))
but get error from MSSQL: mssql: The formal parameter "@Value" was not declared as an OUTPUT parameter, but the actual parameter passed in requested output.
i have found place to fix this bug - func makeRPCParams at mssql.go. After line
decls[i] = fmt.Sprintf("%s %s", name, makeDecl(params[i+offset].ti))
add
		 if params[i+offset].Flags&fByRevValue == fByRevValue {
		 	decls[i] += " output"
		 }

**Comment by kardianos** [comment]
Your SQL got mangled somewhere along the line.

You want `db.Exec("Config_GetParamValue",<parameters>)`

**Comment by kardianos** [comment]
I've updated the example for running stored procs that include how to get a value from an OUT parameter.
