### ISSUE TITLE
Context included in Go 1.7

### ISSUE THREAD

**Issue by dm-logv** [denisenkom/go-mssqldb#325]
There is a problem while project building in Go 1.7:
```
go build
bulkcopy.go:13:2: cannot find package "golang.org/x/net/context" in any of:
        %userprofile%\Documents\apps\go\src\golang.org\x\net\context (from $GOROOT)
        %userprofile%\go\src\golang.org\x\net\context (from $GOPATH)
```
Now in 1.7 "context" included in standard library: https://godoc.org/golang.org/x/net/context

**Comment by kardianos** [comment]
go get -u golang.org/x/net/context

The soonest we could switch to an internal.context is after go 1.10  comes out. Even then  doing so will raise the minimum go version to go 1.8.

**Comment by dm-logv** [comment]
Fixed in https://github.com/denisenkom/go-mssqldb/pull/326
