### ISSUE TITLE
go-mssqldb forcing NVARCHAR instead of column's VARCHAR on SELECT

### ISSUE THREAD

**Issue by vadimyer** [denisenkom/go-mssqldb#334]
Hello.

I'm calling a function with query and arguments that's being translated on SQL Server as follow:

```
exec sp_executesql N' select count(distinct(GoodsID)) from Goods with(nolock) where GoodsTitle = @p1 and GoodsDescription = @p2  AND GoodsId = @p3 AND CreationDate > dateadd(hour, -@p4, GetDate())',N'@p1 nvarchar(5),@p2 nvarchar(88),@p3 bigint,@p4 bigint',@p1=N'Test Good',@p2=N'Test Description',@p3=11,@p4=24
```

The function is:

```
gormDB.Model(&Goods{}).Table("Goods").Select("distinct(GoodsId)").Where(&Goods{GoodsID: gid, GoodsTitle: gtitle, GoodsDescription: val.(string)}).Where("Date > dateadd(hour, -?, GetDate())", timeFrameInt).Count(&r)
```

What's wrong with this query is that I got a table of around 100m rows and this query takes a few seconds to run (and I got indexes set on those columns). I've checked the query manually and it really seems the overhead is on query itself. So I've tried to change nvarchar(5) and nvarchar(88) to varchar(5) and varchar(88) accordingly. Surprisingly, the query executed much faster - like a few milliseconds.

The column types I got in table are of varchar type as well, so this is unclear for me:

```
type Goods struct {
    GoodsID int `gorm:"column:GoodsID"`
    GoodsTitle string `sql:"type:VARCHAR(50)" gorm:"column:GoodsTitle;type:VARCHAR(50)"`
    GoodsDescription string `sql:"type:VARCHAR(100)" gorm:"column:GoodsDescription;type:VARCHAR(100)"`
}
```

(yes, I've tried different ways of type declaration)

I've found that modifying makeDecl() function in types.go of go-mssqldb solves the issue, so the problem is *as I guess* in wrong type definition from my side or probably Gorm/go-mssqldb.

Using latest Gorm + go-mssqldb and Go 1.9.3.

**Comment by vadimyer** [comment]
So far I've discovered that in mssql.go there are two functions makeParam and makeStrParam, the latter forces typeNVarChar so I don't quite get how would makeDecl ever got some other string type? 

That applies for other definitions in makeParam, as they seem to be hard-coded never looking at struct's fields type definition, though I may certainly miss something as I see these internals for the first time.

**Comment by kardianos** [comment]
We could add a varchar type that doesn't do Unicode to the driver.

**Comment by davewo** [comment]
@kardianos we noticed the need for a non-Unicode varchar type for insert use case we have as well. We would be interested helping out with a PR for this, if the project is interested in adding this support.

**Comment by kardianos** [comment]
@vadimyer I think I understood that you need to pass varchar and not nvarchar as input parameters. Is this correct?
