### ISSUE TITLE
installation problem or am I missing something?

### ISSUE THREAD

**Issue by RonaldCole** [denisenkom/go-mssqldb#336]
I downloaded go1.9.3.windows-amd64.msi and installed it on my Windows 10 which has a working installation of SQL Server 2014 Express Edition which I can attach to with Windows Authentication:

...>sqlcmd -S RAMEN\SQL2014 -d Audio
1> SELECT COUNT(*) FROM Collections
2> GO

-----------
         14

(1 rows affected)
1> EXIT

I then installed go-mssqldb as instructed:

...>go get github.com/denisenkom/go-mssqldb

and wrote a quick test, fubar.go, to see if I can connect to my database:

package main

import (
	"database/sql"
	"fmt"

	_ "github.com/denisenkom/go-mssqldb"
)

func main() {
	db, err := sql.Open("mssql", "Server=RAMEN\\SQL2014;Database=Audio;Integrated Security=SSPI")
	if err != nil {
		fmt.Println("Cannot connect: ", err.Error())
		return
	}
	err = db.Ping()
	if err != nil {
		fmt.Println("Cannot connect: ", err.Error())
		return
	}
}

This is what I get:

...>go run fubar.go
Cannot connect:  No instance matching 'SQL2014' returned from host 'RAMEN'

What am I missing?  Your connection string notes suggests that this should work as advertised.

**Comment by kardianos** [comment]
We don't currently support named pipes, but require TCP/IP to be enabled at the moment. That could be the problem.
