### ISSUE TITLE
Failed to send SQL Batch: write tcp 127.0.0.1:54417->127.0.0.1:1433: wsasend: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by KeplerIO** [denisenkom/go-mssqldb#339]
I set up MSSQL instance on my local machine. I can sign in using windows credentials and SQL users just fine... I can query my DB just fine.. But whenever I run my code to connect and execute the "SELECT @@VERSION" query, I get the error in the title. I'm using SQL Server 2014 Express talking on port 1433..

Machine:
Windows 7 Home Premium
GoLang ver 1.10
go-mssqldb Ver: most current 3/2/2018 (isn't documented anywhere *sigh*)
MS SQL Server 2014 Express

My code is below, please let me know if you need more detail. 
```
//Query - Performs the provided query against the DB
func Query(query string) {
	flag.Parse()

	connString := fmt.Sprintf("server=%s;Initial Catalog=DuTodayDB;userid=%s;password=%s;port=%d", *server, *user, *password, *port)
	fmt.Println(connString)

	conn, err := sql.Open("mssql", connString)
	handleFatalError("Error connecting to SQL. . .", err)
	defer conn.Close()

	stmt, err := conn.Prepare(query)
	handleFatalError("Prepare failed. . .", err)
	defer stmt.Close()

	row := stmt.QueryRow()
	var num int
	var char string
	err = row.Scan(&num, &char)
	handleFatalError("Scan failed. . .", err)

	fmt.Printf("num:%d\n", num)
	fmt.Printf("char:%s\n", char)
}

func handleFatalError(msg string, err error) {
	if err != nil {
		log.Fatal(msg, err.Error())
	}
}
```

**Comment by jryd** [comment]
@devKepler did you ever solve this? Getting the same error in Go 1.10.1.

**Comment by devKepler** [comment]
Nope.

**Comment by chngr-mp** [comment]
I also got this message with the following setup:
Win 10 Pro 
local SQL-Server 2017 Express 
go1.10.3 windows/amd64
latest go-mssqldb as of 2018-07-04

In the connection string I used "(local)" or "localhost" as the servername but got 127.0.0.1 in the errormessage.

The problem was gone when I used 127.0.0.1 instead.

**Comment by HemantVallabh** [comment]
I'm also experiencing this error. It seems that this error is returned before the reconnect to the SQL Server instance is tried. The next query is successful. 

I can replicate the results using the following steps;

1. Start application and connect to DB. 
2. Query DB. This will be successful 
3. Restart the SQL Server service. This will drop all connections 
4. Run another query. This will fail with error :  wsasend: An existing connection was forcibly closed by the remote host.
5. Run another query. This will be successful 

**Remote SQL Server instance** : Microsoft SQL Server 2016 (RTM) - 13.0.1601.5 (X64)   Apr 29 2016 23:23:58   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 6.3 <X64> (Build 14393: ) 

**Go version**: go version go1.11 windows/amd64

**Local machine**: Windows 10 Pro 

**Test program that will replicate the error**

`package main

import (
	"database/sql"
	"fmt"
	"log"
	"net/http"
	"strconv"

	_ "github.com/denisenkom/go-mssqldb" // MS-SQL Server driver
)

// SQL ...
var SQL *sql.DB

func main() {

	listenIP := "127.0.0.1"
	listenPort := 8081

	// Connect to database
	if err := connectToDB(); err != nil {
		log.Fatalln(err)
	}
	log.Println("DB connection successful")

	// initialize http server
	http.HandleFunc("/", index)
	if err := http.ListenAndServe(fmt.Sprintf("%s:%d", listenIP, listenPort), nil); err != nil {
		log.Fatalln(err)
	}
}

func connectToDB() error {

	var err error
	connStr := fmt.Sprintf("server=%s;Port=%d;User id=%s;Password=%s;database=%s;app name=%s;timeout=30",
		"sql_ip_address", 1433, "sql_user_name", "sql_password", "master", "TestApp")

	SQL, err = sql.Open("sqlserver", connStr)
	if err != nil {
		return err
	}

	if err = SQL.Ping(); err != nil {
		return err
	}

	return nil
}

func index(w http.ResponseWriter, r *http.Request) {

	var magicNumber int

	row := SQL.QueryRow("select 1 as MagicNumber")
	if err := row.Scan(&magicNumber); err != nil {
		log.Println(err)
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Write([]byte("Success - Magic Number = " + strconv.Itoa(magicNumber)))
	return
}`

**Comment by kakugiki** [comment]
I am new to GoLang. I tried examples/simple/simple.go and the following code failed me and return the same error as this issue reported.

 ```
connStr := fmt.Sprintf("server=%s;Port=%d;User id=%s;Password=%s;database=%s",
	*server, 1433, *user, *password, *db)
```

However, if I write the connection string explicitly without any pointer, it works every single time. Why?

```
connStr := fmt.Sprintf("server=%s;Port=%d;User id=%s;Password=%s;database=%s",
	"server name", 1433, "user", "password", "db")
```

**Comment by kakugiki** [comment]
Thank you for taking time to explain this to me. I misunderstood the syntax of flags. It should be no connection at all, but the error message shows "An existing connection was forcibly closed by the remote host", which is misleading.

**Comment by lrtanner** [comment]
I am not seeing a solution in this thread. I am trying to connect to a DB via its hostname *and* using the parameter `SSPI=Integrated Security`, but get the error shown in the title of this thread. Connecting to the DB via a hostname and a user/pass combo works. Connecting via an IPv4 and `SSPI=Integrated Security` works. But doing them together does not.

@chngr-mp mentioned a very similar issue to mine.
@acsellers also mentioned this.

**Comment by lrtanner** [comment]
@kardianos - I am not seeing a solution in this thread. I am trying to connect to a DB via its hostname _and_ using the parameter `SSPI=Integrated Security`, but get the error shown in the title of this thread. Connecting to the DB via a hostname and a user/pass combo (without SSPI) works. Connecting via an IPv4 and `SSPI=Integrated Security` works. But doing them together does not.

@chngr-mp mentioned a very similar issue to mine.
@acsellers also mentioned this.

Something funky is going on with hostname resolution for sql connections.
