### ISSUE TITLE
unknown token type 110 / 49 errors?

### ISSUE THREAD

**Issue by rbastic2** [denisenkom/go-mssqldb#341]
hi,

our client recently upgraded SQL Server and now we see some strange unknown token type protocol errors:

unknown token type 110 ( happens after 30 to 60 secs of our batch data import running)
unknown token type 49 (happens after about 90 seconds of the batch running. )

we can't reproduce this anywhere else, like in our AWS environment. we suspect it is due to a poor network. do you know if these are new network-level errors, or are there some other resources we could look at to maybe help solve this?

cheers,

**Comment by kardianos** [comment]
What SQL server version are you upgrading from and to?

**Comment by rbastic2** [comment]
Hi,

We believe the from-version is 13.0.10xx. (Sorry, trying to confirm this)
The to-version is 13.0.4466

Thanks,

**Comment by kardianos** [comment]
Do you have encryption turned on when these errors occur?

**Comment by rbastic2** [comment]
Nope

**Comment by kardianos** [comment]
If you turn on encryption (if possible, maybe with self-signed cert), that would ensure integrity as well. Then if it is a bad connection then it would abort at the TLS level and not the TDS level.

I looked up the token types, and token 110 and 49 aren't valid tokens in the spec, so I suspect something odd is happening (this isn't a case of the driver not supporting some feature it looks like).

**Comment by rbastic2** [comment]
tysm! it required increasing our connection timeout and switching from Prepare() to PrepareContext(). i appreciated your other issue that you filed also about the context situation. cheers!
