### ISSUE TITLE
Question: does this driver have a size limitations on stored procedure parameters?

### ISSUE THREAD

**Issue by MarkSonghurst** [denisenkom/go-mssqldb#352]
Hello.
I heavily use [gofreetds](https://github.com/minus5/gofreetds) in my code, which wraps the FreeTDS library. 
When uploading to a stored proc that used a varchar(max) input parameter, we hit a FreeTDS limitation of [8000 bytes](https://github.com/minus5/gofreetds/issues/25).

I'm researching go-mssqldb and initial testing has shown I can exec a stored proc with a varchar(max) input parameter successfully when using a 128MB test file. 
This suggests that go-mssqldb doesn't have the same limitations of FreeTDS - which is good news! 

Has anyone tested size limitations on output parameters and results sets columns please?
Do you have any documented (or otherwise) size limitations for parameters and results sets?
Many thanks.

**Comment by kardianos** [comment]
There is no package limit for parameters, in or out, or select values. Feel free to test though.
