### ISSUE TITLE
LastInsertId errors with There is no generated identity value

### ISSUE THREAD

**Issue by guoguojin** [denisenkom/go-mssqldb#353]
Hi,

Something happened with commit 9340cdc, when I try to get LastInsertId I keep getting back an error: **There is no generated identity value**,
but if I revert to 6a30f4e, the same code gives me the LastInsertId:

What I'm doing in the code:

I create a prepared statement that is an straightforward insert command e.g.:

```go
stmt, _ := db.Prepare("Insert into sometable (somecolumn) values (?)")
res, err := stmt.Exec(somevalue)

if err != nil {
  fmt.Error(err)
}

id, err := res.LastInsertId()

if err != nil {
  fmt.Error(err)
}
```

The insert happens, I can see the data in the database, but the res.LastInsertId() gives me an error.

**Comment by kardianos** [comment]
I should update docs. In SQL server you should select scope_identity() and manual return it.

**Comment by guoguojin** [comment]
Hi,

Thanks for updating so quickly. Unfortunately I've now got a few questions
1. The functionality for the LastInsertId() has been removed? Or changed? 
2. Do I need to return the scope_identity() as part of the prepared statement? Or do I need to make execute a second query and parse the result set? 
3. What if I'm not using a prepared statement and just executing pure SQL, will I still need to get it from the scope_identity() function?

Thanks for the assist, very much appreciated.

**Comment by kardianos** [comment]
Preparing stmts has zero benefits for SQL server. You must execute in same SQL batch.
 Just an aspect of how SQL server works.

**Comment by guoguojin** [comment]
Okay, thanks for the assist. Great work. Much appreciated.

**Comment by reidrac** [comment]
I was affected by this, but I can only reproduce it with Go 1.10; with Go 1.9.4 it behaves as expected.

This report looks like it shouldn't have been closed:

 - The code proposed by @guoguojin looks fine to me
 - It currently works with Go 1.9.4 and not with Go 1.10

So either it doesn't work and then I'd like to understand the use cases of `LastInsertId()`, or there's something not quite right here.

**Comment by kardianos** [comment]
The Go 1.10 version is the first Go version to support the session reset interface. The above stated version of this driver is the first version to support the session reset interface. 

I should document this in the README. Some systems return a last ID inserted from queries. SQL Server does not. This means to try to support the interface we attempt to send another query to the database. `select cast(@@identity as bigint);` This sometimes works depending on the query, but you should not rely on it!

With the addition of the session reset interface this becomes impossible as the session will reset when the connection is sent again. Maybe we can make something work again, but I''m not convinced this is a good idea. In SQL Server your inserted IDs should be an explicit part of your query. You can use the OUTPUT clause or SCOPE_IDENTITY() to help here.

**Comment by petrogdev** [comment]
I am using OUTPUT within the query with db.Exec(stmt) with same result, result being `There is no generated identity value` .

**Comment by kbateman-we** [comment]
This may be gimmicky... BUT I found that using `err = db.QueryRow("INSERT INTO [TABLE] ([COLUMN]) VALUES (?); select SCOPE_IDENTITY()", colValue}).Scan(&id)` will run multiple queries and just return the last row. 

As long as `select SCOPE_IDENTITY()` is the last row returned then this _essentially_ does what I I would have expected `result.LastInsertId()` to do.
