### ISSUE TITLE
Request for Help: prepared statement syntax with an output parameter

### ISSUE THREAD

**Issue by MarkSonghurst** [denisenkom/go-mssqldb#361]
Hi. My DBA has gone on holiday leaving me with this stored proc specification:

PROCEDURE [dbo].[UP_SYS_GetValidationResults]
   @biResultSetId          int     = 0,
   @vcSYSLanuageCode       char(2) = 'en',
   @iSuccess               int   OUTPUT

Please could someone show me how to use it in a prepared statement?
I'm struggling with how the OUTPUT parameter should be represented. I'm using the "sqlserver" driver name as opposed to "mssql" - I think this is preferred driver name?

I've got this:
```
DB.Prepare(`EXEC dbo.UP_SYS_GetValidationResults @biResultSetId, @vcSYSLanuageCode, @iSuccess`)
```
I'm trying to test it using go-sqlmock but that's proving tricky, so I'd be grateful if someone could confirm my prepared statement is ok.
Many thanks.

**Comment by kardianos** [comment]
You don't need to use prepare with this driver.

Doc https://github.com/denisenkom/go-mssqldb/blob/master/README.md#executing-stored-procedures

**Comment by MarkSonghurst** [comment]
Thanks, that helps.
In the docs, there is a opening curly after Dest, which should be a colon:
```
var account = "abc"
_, err := db.ExecContext(ctx, "sp_RunMe",
	sql.Named("ID", 123),
	sql.Out{Dest{sql.Named("Account", &account)}
)
```

Should be:
```
sql.Out{Dest:sql.Named("Account", &account)}
```
