### ISSUE TITLE
connection to msssql 2014 

### ISSUE THREAD

**Issue by zulusbg** [denisenkom/go-mssqldb#362]
Hello 
i have problem to connnect  to mssql 2014 enterprise in Always on group
 Error in plugin [inputs.sqlserver]: read tcp x.x.x.200:44787->x.x.x.41:34001: read: connection reset by peer
server is with SSL certificate 
connection string looks like that
 "Server=x.x.x.x.41;Port=34001;User Id=telegraf;Password=telegraf;app name=telegraf;log=32;certificate=ca-chain.crt;",
Server force encryption and i try with encrypt=true and  TrustServerCertificate=true  and is same problem

**Comment by denisenkom** [comment]
try installing latest service pack

**Comment by zulusbg** [comment]
we try it .. 
but is same
is this driver works on Always on group ? i check alot of setups but no one talks about always on

**Comment by mikewilliamson** [comment]
Yes,  we use it with an Always On Availability Group in a mission-critical, high-volume, production  environment.  However, we don't use SSL certificates.  So I think the problem must be with your certificate-based authentication rather than the AG functionality.

**Comment by mikewilliamson** [comment]
Ah, wait, one important thing to note:

AG's work by having a multiple-IP DNS name, with the addresses of all the servers in the cluster.  The driver tries to connect simultaneously to all of them.  The current master will accept a connection and all the others wont.  Therefore, _you cannot use a fixed IP address to connect to an AG cluster_.

**Comment by mikewilliamson** [comment]
Have you tried it with a DNS name for the AG cluster rather than an IP address?

**Comment by zulusbg** [comment]
we use DNS name
    "Server=hostname.domain.com;Port=25001;User Id=telegraf;Password=telegraf;app name=telegraf;log=2;TrustServerCertificate=true;encrypt=true;",
anything else that im missing ?

**Comment by mikewilliamson** [comment]
If the DNS name in question resolves to all of the IP addresses in the cluster, that's all that you should need from an AG standpoint.  We don't use encryption so possibly that is causing some problems, but I wouldn't expect so.
