### ISSUE TITLE
Prepared statement for CREATE

### ISSUE THREAD

**Issue by AmbicaY** [denisenkom/go-mssqldb#363]
I am not able to run a create database statement using prepared statement:

Code:
stmt, err := sqlconn.Prepare(`create database @p1`)
_, err = stmt.Query("DBNAME")

Error:
mssql: Incorrect syntax near '@p1'.

Am I missing something?

**Comment by kardianos** [comment]
You can't use parameters for identifiers, including database names, table names, and column names.
