### ISSUE TITLE
Question: Issue with secure parameterized queries

### ISSUE THREAD

**Issue by obedmr** [denisenkom/go-mssqldb#364]
I'm having a trouble with integer parameterized values in queries. I want to make my query secure and I found that this was an approach instead of using `fmt.Sprintf` to contruct my query string

I have something like this:

```
    createDatabaseQuery = `
CREATE DATABASE N?
ON PRIMARY ( NAME=N?, FILENAME=N?, SIZE=?, MAXSIZE=?, FILEGROWTH=? )
LOG ON ( NAME=N?, FILENAME=N?, SIZE=?, MAXSIZE=?, FILEGROWTH=? );

// more DB connection code here.

    _, err = d.conn.Exec(createDatabaseQuery, 
            "dbName", 
            "dbFileName", 
            "dbPath" 
            1024, 
            2048, 
            100, 
            "logFile", 
            "logPath", 
            1024, 
            2048, 
            100
    )
    if err != nil {
        return err
    }
```

I'm getting an error like below with the first integer value `SIZE`:
```
Database error: mssql: Incorrect syntax near '@p4'.
``` 

Does anyone have an idea how integer values should be handled?

**Comment by kardianos** [comment]
In T-SQL, identifiers can't be parameters. Also, use "sqlserver" driver, not mssql and replace your ? with "@name" variables.

I don't think this has anything to do with integer parameters. SQL Server error messages are sometimes... incorrect.

**Comment by obedmr** [comment]
@kardianos I have a couple of questions:
1. what's the difference between drivers `mssql` and `sqlserver`? I didnt know about the `sqlserver` driver, I followed the example at: https://github.com/denisenkom/go-mssqldb/blob/master/examples/tsql/tsql.go#L25
2. If I replaces the `?` where I would set those tags like `@name`, are they auto-generated?

**Comment by kardianos** [comment]
I'll make a note to update the examples.

Please read the readme where it refers to the parameter names.

**Comment by obedmr** [comment]
@kardianos, I didnt checked the named parameters, that's pretty cool, I can send a PR tomorrow to update the examples. Thanks a lot for your help.
