### ISSUE TITLE
Unexpected error when restoring a database

### ISSUE THREAD

**Issue by MBonell** [denisenkom/go-mssqldb#367]
I created a simple call to restore a database but even when the restore is done without any error in the MSSQL server, I'm getting this error from the driver:
`mssql: RESTORE DATABASE is terminating abnormally`

This is how I implemented the function:
```
query := `RESTORE DATABASE mydb FROM DISK = 'mybackup.bak' WITH RECOVERY`
_, err := d.conn.Exec(query)
return err
```

**Comment by kardianos** [comment]
Connect to master DB in connection string, not restoring DB?

**Comment by MBonell** [comment]
I tried that approach but again it only works fine when the restore is forced with replace

**Comment by kardianos** [comment]
I have no idea. Looks like SQL Server is aborting the connection for some reason. The only thing I can think of is if SET ENV TDS command is not being processed correctly.  Please re-open if have a suggestion or if we can document a different client behaving differently.
