### ISSUE TITLE
Example of a stored procedure that returns a value AND a result set?

### ISSUE THREAD

**Issue by thebitguru** [denisenkom/go-mssqldb#369]
I am working on an app that has stored procedures which return both a value and a result set.  How can I account for both using this package?  I feel like putting more examples of stored procedure calls would be helpful and I will be happy to submit PRs with more examples.

Thanks!

**Comment by kardianos** [comment]
Can you post a minimal example of such a sproc?
Are you talking return values or OUT params?

**Comment by thebitguru** [comment]
Thanks for the quick response.  Here is an example.

```
CREATE PROCEDURE

[dbo].[return_and_result_set]
(
	@inputParam1	INT = 0,
	@inputParam2 	VARCHAR(100) = NULL,
	@outputParam1	INT = 0 OUTPUT,
	@outputParam2	VARCHAR(100) = NULL OUTPUT
)
AS 
BEGIN
    SELECT @inputParam1 as input1, @inputParam2 as input2;
    SET @outputParam1 = 99
    SET @outputParam2 = 'Testing'

    RETURN 12
END
GO
```

You can execute this as...


```
DECLARE @input1 INT = 123;
DECLARE @input2 VARCHAR(100) = 'i2';
DECLARE @output1 INT = 0;
DECLARE @output2 VARCHAR(100) = NULL;
DECLARE @retval INT;

EXEC @retval = [dbo].[return_and_result_set] @inputParam1=@input1, @inputParam2=@input2, @outputParam1=@output1 OUTPUT, @outputParam2=@output2 OUTPUT;

SELECT @output1 as output1, @output2 as output2, @retval as retval
```

As you can see in the above examples, it's both output param and return value.

**Comment by kardianos** [comment]
database/sql doesn't support return values at this time. Let me think about how to support this. Don't hold your breath as I'm a bit busy, but in the next week or so I can probably support this.

**Comment by thebitguru** [comment]
No worries.  That would be awesome.  Thanks for the quick responses!

**Comment by ecc256** [comment]
>database/sql doesn't support return values at this time. Let me think about how to support this. Don't hold your breath as I'm a bit busy, but in the next week or so I can probably support this.
Was about to ask about same thing!
Looking forward to test it!

**Comment by sql-sith** [comment]
I work at GoDaddy, and this is a real shortcoming for us right now. Not griping, just saying that even though others aren't commenting, there may be others of us stuck on this right now. Thanks!

**Comment by kardianos** [comment]
I've determined how this driver can support this feature. We'll pass in a special parameter value to the QueryContext call and fill in the values there. It should be relatively painless to do.
