### ISSUE TITLE
QueryContext  call issue with Datetime type on SQL Server 12

### ISSUE THREAD

**Issue by MarkSonghurst** [denisenkom/go-mssqldb#371]
Hi
I'm stuggling with passing a time.Time through as a datetime. Please can anyone help?

I'm calling QueryContext on a stored procedure which takes a datetime (`@dtEffectiveDateTime`) as an input parameter.
```
PROCEDURE [dbo].[UP_SC_GetCountryCodes]
      @iNumbericCode    int     	= 0, -- GET ALL  
      @vcSYSLanguageCode    char(2) 	= 'en',
      @dtEffectiveDateTime   datetime	= '9999-12-31 23:59:59.997',
      @iFirstCode     int   = 0, 
      @iSuccess      bigint  OUTPUT,
      @dtAPIForceCacheRefreshDtTm datetime	OUTPUT
```
My Go (1.10.2) code sets the parameter like this:

```
sql.Named("dtEffectiveDateTime", time.Now().UTC()),
```

However, SQL Server 12 () is returning this error:

```
"mssql: Error converting data type datetimeoffset to datetime."
```

I have tried setting the parameter using a non-inline variable of type Time, being set to either UTC() or with no timezone specifically set (my local timezone is EET), I have also tried using an zero time.Time{} - but all result in the same error message.

A trace off the DB, when using a variable set to time.Time{} gave this information:
```
declare @p5 bigint
set @p5=0
declare @p6 datetimeoffset(7)
set @p6='0001-01-01 00:00:00 +00:00'
exec dbo.UP_SC_GetCountryCodes @iNumbericCode=0,@vcSYSLanguageCode=N'en',@dtEffectiveDateTime='0001-01-01 00:00:00 +00:00',@iFirstCode=0,@iSuccess=@p5 output,@dtAPIForceCacheRefreshDtTm=@p6 output
select @p5, @p6
```

My DBA says the error message is because the time.Time value for the `@dtEffectiveDateTime` parameter is not coming through as a datetime - which makes sense as the offset is present in the trace. 
Is there a way to tell the go-mssqldb driver to convert time.Time into datetime rather than (I think) datetimeoffset ?

I'm using the driver as "sqlserver" 

Many thanks for your time.
Mark.

**Comment by kardianos** [comment]
We need overrides for parameter types. No promises on timeline but let me
see what I can do today.

**Comment by MarkSonghurst** [comment]
Thank you for the fast response. We're also seeing this issue for the `@dtAPIForceCacheRefreshDtTm' Output parameter as well, inevitably its all related.

**Comment by MarkSonghurst** [comment]
Thank you for the fast response. 
We're also seeing a similar issue for the `@dtAPIForceCacheRefreshDtTm` Output parameter as well, inevitably its all related.

We updated the proc so `@dtAPIForceCacheRefreshDtTm` is a datetimeoffset Output parameter but we get this error message:
```
scan error unsupported type from server time.Time=2015-11-24 18:42:18.74 +0000 +0000
```
When keeping it as a datetime output parameter we get the same error message as with the input parameter
```
"mssql: Error converting data type datetimeoffset to datetime."
```

Here's the QueryContext call in my Go code:
```
	var success int64
	var updated time.Time
	rows, err := db.DB.QueryContext(context.TODO(), "dbo.UP_SC_GetCountryCodes",
		sql.Named("iNumbericCode", 0),
		sql.Named("vcSYSLanguageCode", langcode),
		sql.Named("dtEffectiveDateTime", when),
		sql.Named("iFirstCode", priorityCountry),
		sql.Named("iSuccess", sql.Out{Dest: &success}),
		sql.Named("dtAPIForceCacheRefreshDtTm", sql.Out{Dest: &updated}),
	)
```

Hope this helps!
Thanks again, Mark.

**Comment by MarkSonghurst** [comment]
@kardianos As a workaround (on input parameters at least) I tried commenting out the if block between lines 748-768 in mssql.go, so it would have no choice but to use typeDateTimeN for time.Time

```
	case time.Time:
		if s.c.sess.loginAck.TDSVersion >= verTDS73 {
			res.ti.TypeId = typeDateTimeOffsetN
			res.ti.Scale = 7
			res.ti.Size = 10
			buf := make([]byte, 10)
			res.buffer = buf
			days, ns := dateTime2(val)
			ns /= 100
			buf[0] = byte(ns)
			buf[1] = byte(ns >> 8)
			buf[2] = byte(ns >> 16)
			buf[3] = byte(ns >> 24)
			buf[4] = byte(ns >> 32)
			buf[5] = byte(days)
			buf[6] = byte(days >> 8)
			buf[7] = byte(days >> 16)
			_, offset := val.Zone()
			offset /= 60
			buf[8] = byte(offset)
			buf[9] = byte(offset >> 8)
		} else {
			res.ti.TypeId = typeDateTimeN
			res.ti.Size = 8
			res.buffer = make([]byte, 8)
			ref := time.Date(1900, 1, 1, 0, 0, 0, 0, time.UTC)
			dur := val.Sub(ref)
			days := dur / (24 * time.Hour)
			tm := (300 * (dur % (24 * time.Hour))) / time.Second
			binary.LittleEndian.PutUint32(res.buffer[0:4], uint32(days))
			binary.LittleEndian.PutUint32(res.buffer[4:8], uint32(tm))
		}
```

However, this didn't work with the error message:

```
"mssql: The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 6 (\"@dtAPIForceCacheRefreshDtTm\"): The supplied value is not a valid instance of data type datetime. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision."
```

Are you able to make any workaround suggestions please so I can temporarily use a fork of this package but with all dates being forced to the datetime type? We're not using datetimeoffset or datetime2 types in our database at all - only datetime. 
Or perhaps there is an alternative way I can Exec and Query stored procs with input and output parameters of type datetime, without using the sql.Named approach?
Many thanks.

**Comment by kardianos** [comment]
There is a similar issue with varchar vs nvarchar. Here is my PR for varchar. I'll see if I can do the date/time/datetime/datetime2 types next.

https://github.com/denisenkom/go-mssqldb/pull/375

**Comment by MarkSonghurst** [comment]
@kardianos Thanks, a fix would be awesome.

**Comment by MarkSonghurst** [comment]
@denisenkom 
Will this fix work with Output parameters please?
I'm struggling to get it to work, possibly due to my Go syntax. My understanding is that output parameters need to be passed by address (please see parameter dtAPIForceCacheRefreshDtTm)

```
	var success int64
	var updated time.Time
	rows, err := db.DB.QueryContext(context.TODO(), "dbo.UP_SC_GetEUCountryCodes",
		sql.Named("iCountryCode", 0),
		sql.Named("cSYSLanguageCode", langcode),
		sql.Named("dtEffectiveDateTime", when),
		sql.Named("iFirstCode", priorityCountry),
		sql.Named("iSuccess", sql.Out{Dest: &success}),
		sql.Named("dtAPIForceCacheRefreshDtTm", sql.Out{Dest: (*mssql.DateTime1)(&updated)}),
	)
```

However, I get this error back:
```
"sql: converting argument with name \"dtAPIForceCacheRefreshDtTm\" type: unsupported type mssql.DateTime1, a struct"
```

Any advice very welcome, thanks.

**Comment by kardianos** [comment]
You may be interested in #381.
Good point, I need to make output parameter support more robust.

**Comment by MarkSonghurst** [comment]
@kardianos Thanks for replying, and for the effort in making the datetime input parameter fix. 
I can't get my head around #381 I'm guessing it's foundation work for #382 
Thanks again, much appreciated - Mark.
