### ISSUE TITLE
define type for sql parameter

### ISSUE THREAD

**Issue by Fank** [denisenkom/go-mssqldb#386]
We have a problem that using parameters in sql statements causing a huge re-/compilations in T-SQL, which decreased performance (mostly in larger sql plans).
Here are examples why:
Example 1:
```go
	err := n.MSSQL.SelectContext(
		ctx,
		&asd,
		`
			SELECT
				bin = 1
			FROM
				foobar
			WHERE
				baz = @p1;
		`,
		"myString",
	)
```

Example 2:
```go
	err := n.MSSQL.SelectContext(
		ctx,
		&asd,
		`
			DECLARE @myparam AS VARCHAR(MAX) = @p1;
			SELECT
				bin = 1
			FROM
				foobar
			WHERE
				baz = @myparam;
		`,
		"myString",
	)
```

Here a little example about what happens on the T-SQL server (query plans) (top: Example 1, bottom: Example 2):
![image](https://user-images.githubusercontent.com/1900106/40840610-ba2da058-65a7-11e8-8b6d-aa9697d01d43.jpg)

And from the performance chart (red marker is where we deployed the code changes):
![image](https://user-images.githubusercontent.com/1900106/40840677-faeda8c2-65a7-11e8-8172-2b51ad882433.png)
This was a massive performance increase in our application.

It should be possible to define the sql parameter type like in `sql.Named`, e.g. `sql.NamedTyped("myVar", "VARCHAR(MAX)", "foo")`.

**Comment by kardianos** [comment]
This is already fixed in master. Cast parameter string to mssql.VarChar. See readme for details.

**Comment by denisenkom** [comment]
Try NVarCharMax parameter

**Comment by Fank** [comment]
@denisenkom could i have also a varcharmax? because i need a varchar instead of a nvarchar.

**Comment by denisenkom** [comment]
done
