### ISSUE TITLE
connection timeout

### ISSUE THREAD

**Issue by zyfjfj** [denisenkom/go-mssqldb#387]
why I set connection+timeout=0 ，the database immediately  closed? thanks
go 1.10 ,mssql 2008r2,window 10

**Comment by kardianos** [comment]
what git revision are you using for this driver?

**Comment by onlyLeoll** [comment]
first ,restart your service ,second ,set DSN added connection timeout = 0,you can use heart beat test or keep alive to prove

**Comment by onlyLeoll** [comment]
set DSN Pooling=true;Max Pool Size=40000;Min Pool Size=0;
