### ISSUE TITLE
`Prepare failed:Login error: EOF` when to connect sql server 2005

### ISSUE THREAD

**Issue by arstercz** [denisenkom/go-mssqldb#399]
error occurs when I use the `github.com/denisenkom/go-mssqldb/examples/simple/simple.go` to connect my sql server 2005 whether the password is correct or not:
```
# on the centos6.8 system, go-1.10
# ./simple -port 11433 -server 10.0.10.2 -user test -password xxxxx
2018/06/29 20:41:21 Prepare failed:Login error: EOF
```

the env on my sql server:
```
Windows Server 2003 Enterprise Edition Service Pack 2
Microsoft SQL Server 2005 - 9.00.5000.00 (Intel X86)  Copyright (c) 1988-2005 Microsoft Corporation  Enterprise Edition on Windows NT 5.2 (Build 3790: Service Pack 2) 
```
and also print error when I use usql connect the sql server:
```
# usql --username test --password  'mssql://10.0.10.2:1433/test'
Enter password: 
error: mssql: Login error: EOF
```

anyone can help with this?  thanks!

**Comment by denisenkom** [comment]
Please enable verbose logging on driver and send me driver logs and also SQL server logs.

**Comment by arstercz** [comment]
hi @denisenkom , I read the link https://github.com/denisenkom/go-mssqldb/issues/27 and it's  ok when I disabled the encryt option:
```
# ./simple -port 1433 -server 10.0.10.2 -user test -password xxxxx --debug
 password:xxxxx
 port:1433
 server:10.0.10.2
 user:test
 connString:server=10.0.10.2;user id=test;password=xxxxx;port=1433;encrypt=disable
somenumber:1
somechars:abc
bye
```
but I don't known why does the `encrpt` option affect the connect?
