### ISSUE TITLE
Bulk Load

### ISSUE THREAD

**Issue by dimdin** [denisenkom/go-mssqldb#40]
When an INSERT BULK statement is prepared use the bulk load message to transfer data efficiently.
Bulk load messages documentation: http://msdn.microsoft.com/en-us/library/dd358082.aspx
A similar feature is implemented by postgresql driver: http://godoc.org/github.com/lib/pq#hdr-Bulk_imports

**Comment by gaspardle** [comment]
Hi,
i've got a semi-working code for bulk loading. But one problem I see is that there is no explicit API in the Go SQL interface to support bulk loading. 

Any ideas on the best way to implement it?

**Comment by denisenkom** [comment]
I don't have any particular ideas.  It has to be some kind of custom interface.  Look around for other sql drivers on the ways they support this functionality (if there are such). Propose some kind of interface for us to discuss.

**Comment by gaspardle** [comment]
You can check my current code here
https://github.com/gaspardle/go-mssqldb/tree/bulkload

examples/bulk.go contains a working example

There are some datatypes currently not supported like money, decimal and datetimeoffset.

**Comment by denisenkom** [comment]
Can you create a pull request?  It would be easier to look at it that way.

**Comment by lukewilliamboswell** [comment]
+1
