### ISSUE TITLE
Use of internal package not allowed

### ISSUE THREAD

**Issue by timabell** [denisenkom/go-mssqldb#406]
Just tried to do a build from source and I'm getting an error `types.go:13:2: use of internal package not allowed`

```
$ git log --oneline -n 1
242fa5a Add varchar(max) parameter support
$ go build
types.go:13:2: use of internal package not allowed
$ grep internal types.go 
        "github.com/denisenkom/go-mssqldb/internal/cp"
$ go version
go version go1.9.5 linux/amd64
$ cat /etc/issue
Linux Mint 18.3 Sylvia \n \l
$ which go
/home/tim/.gvm/gos/go1.9.5/bin/go
```

Seems there's a folder in this project called `internal/` and go doesn't approve for some reason.

https://stackoverflow.com/questions/41060764/golang-disable-use-of-internal-package-not-allowed

It would be good to be able to check out and build the project.

**Comment by timabell** [comment]
Ah it's because I forked, and now I'm not using your repo path any more.

`github.com/timabell/go-mssqldb` != `github.com/denisenkom/go-mssqldb`

**Comment by jpmckearin** [comment]
@timabell can you close the issue if its resolved?

**Comment by timabell** [comment]
It seems it's a quirk of go rather than anything to do with this repo https://stackoverflow.com/questions/14323872/using-forked-package-import-in-go

**Comment by timabell** [comment]
Found a better solution: https://stackoverflow.com/a/51882990/10245
