### ISSUE TITLE
Anyone every been successful with calling stored procedures?

### ISSUE THREAD

**Issue by PeterNierop** [denisenkom/go-mssqldb#408]
I tried to build the most simple of demos. The connectionstring is accurate. It does work with SQL statements. The issue is that I get this error:

C:\Users\peter\go\planday>go build main.go && main.exe
Whatever:  sql: expected 0 arguments, got 2

I tried reinstalling both mssqldb as well as go (version 1.10.3)

Looking at SQL trace shows that the connection is made, but there is never a call to the proc.

Code:
package main

import (
	"context"
	"database/sql"
	"fmt"

	_ "github.com/denisenkom/go-mssqldb"
)

var (
	db  *sql.DB
	err error
)

func main() {
	connString := "server=localhost;User Id=dpweb;Password=dpweb;database=DayPlan;app name=dpweb;connection timeout=5;dial timeout:10"

	db, err = sql.Open("mssql", connString)
	if err != nil {
		fmt.Println("Open connection failed: %s", err.Error())
	}
	defer db.Close()
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	var account = "abc"
	_, err4 := db.ExecContext(ctx, "sp_RunMe",
		sql.Named("ID", 123),
		sql.Named("Account", sql.Out{Dest: &account}),
	)
	if err4 != nil {
		fmt.Println("Whatever: ", err4.Error())
		return
	}
}

**Comment by MarkSonghurst** [comment]
What does proc sp_RunMe look like?
I would expect something along the lines of
```
PROCEDURE sp_RunMe
@ID int,
@Account nvarchar(3) OUTPUT
```

The error messages suggests that sp_RunMe has no parameters (neither Input or Output).
You're unlikely to see any trace on the database side if your Go proc call does not match the actual SQL Server proc specification.

**Comment by PeterNierop** [comment]
Thanks for your reply. The proc was taken from standard documentation on this git. 
I hail from SQL and have slowly moved to frontend/middleware, hence my religious zeal to protect my relics: stored procedures, from which I have many.
As suspected the error indeed is that the mssqldb does not connect after the login. Turns out it is in the open statement:
so this does NOT work: 

db, err = sql.Open("mssql", connString)

this DOES: 

db, err = sql.Open("sqlserver", connString)

**Comment by svtarasov** [comment]
God bless you Peter for your investigation! thanks a lot!
