### ISSUE TITLE
unable to install this package / unable to download / civil package dep download issue

### ISSUE THREAD

**Issue by Muthamizh-ilakkiya** [denisenkom/go-mssqldb#409]
@denisenkom 
When i tried to install the MS SQL server specific driver using the command **"go get github.com/denisenkom/go-mssqldb**" in cmd prompt, got the error as "package cloud.google.com/go/civil: unrecognized import path "cloud.google.com/go/civil" (https fetch: Get https://cloud.google.com/go/civil?go-get=1: dial tcp 172.217.167.14:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)". Anyone face this issue already

**Comment by Melaninneal** [comment]
yes im facing it as well

**Comment by elliots** [comment]
If you click that link in your browser, does it work? Could it be possible your internet connection is blocking google?

**Comment by kardianos** [comment]
@denisenkom This is likely Google enforcing export restrictions to certain countries, or a country's firewall blocking this.  I could revive the branch made user types opt-in. Opinions?

**Comment by denisenkom** [comment]
Yeah, that issue is a good argument for making this dependency optional.

**Comment by Muthamizh-ilakkiya** [comment]
@elliots I could be able to open the link in browser

**Comment by Blitzbat** [comment]
@denisenkom Why are you not using the google cloud go git repository? 
https://github.com/GoogleCloudPlatform/google-cloud-go

This will fix the current problems.

**Comment by kardianos** [comment]
This will be resolved with #380 .
