### ISSUE TITLE
Secure connection to MS SQL Server

### ISSUE THREAD

**Issue by sfmarques** [denisenkom/go-mssqldb#410]
Hello,

I can login to MS SQL Server but my password is in plaintext, i think. When I add encrypt = true I get this error:

> error query: TLS Handshake failed: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs

How can I secure my connection to MS SQL Server?

Thanks

**Comment by kardianos** [comment]
Either use the hostn

**Comment by sfmarques** [comment]
Using hostname I get this error:

> error query: TLS Handshake failed: x509: certificate signed by unknown authority

allow insecure is what i don't want

**Comment by kardianos** [comment]
Then you must install a valid server certificate that is trusted by the client.

**Comment by sfmarques** [comment]
Do you know a good tutorial for that?

**Comment by kardianos** [comment]
Not really. Do a Google search. Maybe look into mkcert on GitHub. I always have to look up the steps each time via Google or msdn.
