### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by tharun-d** [denisenkom/go-mssqldb#415]
C:\Users\hpadmin\Desktop\pracise go>git config --global http.proxy http://16.153.99.11:8088

C:\Users\hpadmin\Desktop\pracise go>go get github.com/denisenkom/go-mssqldb
package cloud.google.com/go/civil: unrecognized import path "cloud.google.com/go/civil" (https fetch: Get https://cloud.google.com/go/civil?go-get=1: dial tcp 172.217.12.78:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

**Comment by kardianos** [comment]
dup of #409
