### ISSUE TITLE
Execute multiple queries in a stateful way

### ISSUE THREAD

**Issue by heyimalex** [denisenkom/go-mssqldb#416]
Hello, I just wanted to double check something. I need to execute multiple queries in a stateful way so that statements like `USE [DATABASE]` work across batches. That's impossible with this package right? Even if I went around the `database/sql` interface to keep a single connection, everything is ultimately executed with `sp_executesql`, which doesn't maintain state by design.

For context, I'm trying to write something that can run batch scripts like sqlcmd.

**Comment by kardianos** [comment]
What you want is the sub package batch.

**Comment by heyimalex** [comment]
My question was more would that even work? Splitting up batches isn't the issue, running them statefully like batch scripts expect is. Maybe I'm not understanding though.

**Comment by kardianos** [comment]
Yes. First grab a connection from db, then run each in the same connection.

**Comment by denisenkom** [comment]
Queries without parameters will be executed as raw batch.  Driver would only use sp_executesql for queries with parameters.

**Comment by heyimalex** [comment]
Thanks! I'm not sure how I didn't see that 😅
