### ISSUE TITLE
Unrecognized import path on install

### ISSUE THREAD

**Issue by jfcarr** [denisenkom/go-mssqldb#419]
When I attempt to install using `go get github.com/denisenkom/go-mssqldb`, I see the following message:

> package cloud.google.com/go/civil: unrecognized import path "cloud.google.com/go/civil" (parsing cloud.google.com/go/civil: XML syntax error on line 67: expected element name after <)

I think this _might_ be a duplicate of #409, although the message is different.

**Comment by kardianos** [comment]
This will be resolved with #380 .
