### ISSUE TITLE
Login Error：EOF or An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by starchou** [denisenkom/go-mssqldb#42]
I use Mac OSX Develop my project,it work very good !
today I copy my project to my colleague , He is Can't run it 
he use Windows 8  coding
the error is WSARecv tcp 172.16.xx.xx:4559:An existing connection was forcibly closed by the remote host,
sometimes the error is Login error : EOF 
so I write a demo to test (https://gist.github.com/starchou/8f81ed7d08771416ed5d) in my computer it can work.but in my colleague's computer it can't work.
Meanwhile  I tested with CentOS, the error is Login error:read tcp 172.xx.xx.xx:1433:connection reset by peer

but in my online server(Debian) ,it can run well！

the MSSQL version is SQL Server 10.50.1600
the golang version is 1.2

**Comment by tanvt** [comment]
@denisenkom Thanks. You saved my week!!!
