### ISSUE TITLE
Support for Multi-subnet Failover Clusters

### ISSUE THREAD

**Issue by m82labs** [denisenkom/go-mssqldb#420]
Currently there does not seem to be support for the MultisubnetFailover connection string option. 

https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder.multisubnetfailover?view=netframework-4.7.2

This behavior is 100% client side, so should be able to be implemented here. To summarize what this does:

- If you are using a multi-subnet failover cluster (the only option in AWS) the AG listener will have two IP addresses
- One of the addresses is active, the other is not
- When attempting to connect from a windows client it will try both addresses (serially)
- With this connection string option set it will try both addresses in parallel and use the connection that is successful

I can attempt to implement this behavior, but as I am only a hobbist when it comes to Go, it might take me some time.

**Comment by mikewilliamson** [comment]
This is already supported in the driver automatically if the DNS name resolves to multiple IP addresses.  No connection string parameter is required.

**Comment by m82labs** [comment]
Awesome, my mistake!

Thanks
