### ISSUE TITLE
How do I get metadata about the sqlserver's built-in functins

### ISSUE THREAD

**Issue by wcn00** [denisenkom/go-mssqldb#425]
I have a need to do this pragmatically.  There are metadata tables for user contributed functions and stored procedures, but I cannot find it for the built-in functions.  Is it possible to do this?
Thanks in advance.
wcn

**Comment by kardianos** [comment]
I don't actually know. SSMS get's it, so there is probably a way. Loading up a program that does this and monitoring queries may be the best bet.
