### ISSUE TITLE
Is slice supported as params?

### ISSUE THREAD

**Issue by diegobernardes** [denisenkom/go-mssqldb#432]
With a query like this: 

```sql
...
AND sku NOT IN (@SKU)
```

I'm getting this error:

```
sql: converting argument with name "SKU" type: unsupported type []string, a slice of string
```

So, the question is, the string slice is supported by the driver?

**Comment by kardianos** [comment]
Arrays are not supported by SQL server.

**Comment by diegobernardes** [comment]
But the thing is, I don't want to use it like Postgres where it have native array support. 
With other golang sql drivers, when you pass a slice it make a list of elements like this:

```golang
skus := []string{"1", "2", "3"}
```

And a query like this:
```sql
AND sku NOT IN (@SKU)
```

Would generate:
```slq
AND sku NOT IN ('1', '2', '3')
```

**Comment by kardianos** [comment]
@diegobernardes I'm glad that's something you want to do. I do similar things all the time (but not how to describe).

SQL Server Parameters don't work like that. The SQL Query text and each parameters are sent to the server as-is, without any inspection or modification. Thus this would involve parsing T-SQL accurately. This driver used to attempt to do this before `database/sql` supported named parameters, but it was buggy and hard to do correctly.

So, one thing I do to get around this, especially if I have a number of IDs I want to match (like you describe), is to template the SQL and join the IDs together prior to sending the SQL to the driver. Do escape your inputs and tend to use N'' esp if using nvarchar. Or if that sounds too scary, you can have your template expand a list of identifiers `NOT IN (@SKU_1, @SKU_2, ...)` and then generate the parameters separately you append to the prams.

Lastly, another way to do this is to join the strings together with a dilimitar then define a table valued function (using CLR) to split the string of values.

```
select
    p.*
from
    product p
where
    sku not in (select list.Item from dbo.Split(@SKU, N'|') list)
;
```

This is the most convenient assuming you are joining either numbers or an identifier that is known to never contain a certain character.

Hope this helps.

**Comment by diegobernardes** [comment]
Thanks @kardianos, helped alot. It's the first time using mssql, sorry my ignorance.
