### ISSUE TITLE
Question: does the driver utilize cursors for "rows.Next"?

### ISSUE THREAD

**Issue by x1unix** [denisenkom/go-mssqldb#434]
Hello, I have a question.

There is `rows.Next()` method that provides next result from the query.
In official docs says that it should utilize cursors, but it depends on driver implementation:

> Rows is the result of a query. Its cursor starts before the first row of the result set. Use Next to advance from row to row.

Does the drives use cursor under-the-hood?

If yes, will cursor work with such join queries? e.g:

```sql
SELECT * FROM foo AS A WITH(NOLOCK) 
INNER JOIN bar AS B WITH(Nolock) 
ON foo.Client = B.Code 
Where B.Name=@p1 and B.Age=@p2 Order by Id desc
```

Thank you for the feedback.

**Comment by kardianos** [comment]
No SQL cursors are used. That query will work.
