### ISSUE TITLE
Web service goes down often when max connection is set

### ISSUE THREAD

**Issue by LynkLogistics** [denisenkom/go-mssqldb#445]
We have a web service connecting to mssql using go-mssqldb package. We have noticed that when the max connection count is set, the service goes down often. 
When the config is removed the service does not go down, but we see a very high increase in database connections (7k+). Connection snippet:

ConnPool, err = sql.Open("sqlserver", url)
if err != nil {
	log.Println("Err:", err)
}
ConnPool.SetMaxOpenConns(100)

**Comment by roxtar7** [comment]
Hey @denisenkom, we have tried closing all the SQL statement objects once done reading from them but still, the connections are not being reused and our microservices are going down. I am using Rows.Close() operation to close the statements. We execute stored procedures where we get multiple data sets for a single execution in the database. We are not able to develop further on our microservices as we aren't able to fix this issue. Is it something we are doing wrong? Please help me out here.

Thanks,
Rakesh.

**Comment by kardianos** [comment]
I would highly encurage you to encapsulate your select logic in https://bitbucket.org/kardianos/table or some other method, or if you don't, ensure you also include a `defer rows.Close`, even if you have another `rows.Close()` (no defer) because this ensures it is executed.
