### ISSUE TITLE
Need help formatting a connection string for Windows Auth

### ISSUE THREAD

**Issue by lrtanner** [denisenkom/go-mssqldb#450]
I cannot get a successful connection using Windows Auth and the go-mssqldb library. I *can* get a Windows Auth login to work through Microsoft SQL Server Management Studio

here are two different formats for the connection string that seem to be the closest to working:

Leave the user out completely and stick with the `user id` parameter:

(note: the sql server machine's hostname is `CB-W12R2-S16-PM`)

`sqlserver://CB-W12R2-S16-PM?Connection+Timeout=30&Database=DBName&Integrated+Security=SSPI&TrustServerCertificate=true&encrypt=true&log=0&packet+size=2048&user+id=MYDOMAIN%5Cmyfirstname.mylastname`

Result:
`InitialBytes InitializeSecurityContext failed 8009030c`

Put the Windows domain account as a user with no password:
`sqlserver://MYDOMAIN%5Cmyfirstname.mylastname:@CB-W12R2-S16-PM?Connection+Timeout=30&Database=DBName&Integrated+Security=SSPI&TrustServerCertificate=true&encrypt=true&log=0&packet+size=2048`

Result: 
`InitialBytes InitializeSecurityContext failed 8009030c`

**Comment by Lercher** [comment]
Just having the same trouble with the local SQL Server 2016. Additionally with `sqlserver://localhost?app+name=...` I get

````
failed to send SQL Batch: write tcp 127.0.0.1:64433->127.0.0.1:1433: wsasend: An existing connection was forcibly closed by the remote host.
````

Connecting with `sa` plus password is possible. However, I don't want to manage passwords in the app.

**Comment by Lercher** [comment]
I had a debug-look at the code and I'm not at all familiar with Schannel. In my case (I have a slow remote DC) it's item 4b unter "client" in https://docs.microsoft.com/en-us/windows/desktop/secauthn/creating-an-schannel-security-context, i.e. `InitializeSecurityContext` returns `SEC_I_CONTINUE_NEEDED` and the driver just returns the buffer. That means I can't find the loop back to call `InitializeSecurityContext` again near this line: https://github.com/denisenkom/go-mssqldb/blob/master/sspi_windows.go#L195

Quoted from the webpage:
````
If the function returns SEC_I_CONTINUE_NEEDED, the client must wait
for the server to send it a token. When the client has the token from 
the server, it must call the InitializeSecurityContext (General) function 
again. (Return to step 2.)
````

I have no idea how to `wait for the server to send it a token` so I'm afraid I can't offer a suggestion or even a fix. Maybe the maintainers have a good guess what to do?

However, irtanner, I guess leaving out the `user:pass@` phrase completely seems to be the proper way to use integrated security (aka SSO).

**Comment by lrtanner** [comment]
@Lercher - Leaving out the `user:pass@` prefix and also leaving out the `user id` parameter worked for me. I was in a tricky spot due to a bad domain/AD setup causing every connection string to seem bad when really my network auth was going to fail no matter what.
