### ISSUE TITLE
TVP: simplify?

### ISSUE THREAD

**Issue by kardianos** [denisenkom/go-mssqldb#458]
Table valued parameters has been contributed and in master. Yay and Thank you!

One nit that I'd like us to consider prior to v1 release: Could we define TVP as: 

```
type TVP struct {
    Schema string // Optional, may omit if in default schema.
    Type string // Required, type of TVP.

    // Value of the Tabled Valued Parameter.
    Value interface{}
}
```

The current struct definition stutters quite a bit.

---

Also, what would you think about combining Schema with Type and removing Schema? It would require parsing the field before it could be used in the protocol, but that doesn't seem too hard. Would that be a usability win?

/cc @NikitaDef @denisenkom

**Comment by NikitaDef** [comment]
Of course, I agree about combining Schema with Type. I'll change it.
Sorry about current definition.
@kardianos @denisenkom can you give your definition?

**Comment by kardianos** [comment]
Maybe something like:

```
type TVP struct {
    Type string // Required, type of TVP. Optionally prefix with the schema name.

    // Value of the Tabled Valued Parameter.
    Value interface{}
}
```

However, we should probably parse the "[" and "]" correctly if we do that rather then doing a blind split on "." (period).  I think we have code that exists that does this already. Though for a first pass doing a `strings.SplitN(t.Type, ".", 2)` would probably be fine.

**Comment by NikitaDef** [comment]
@kardianos @denisenkom I added support only slice type as TVP type. 
Should we add support array type as TVP type?
I think we should

**Comment by kardianos** [comment]
Up to you at this point :). This issue just thinking about API facing issues prior to v1. But adding supported types can happen gradually over time, even after v1 .

**Comment by NikitaDef** [comment]
@denisenkom @kardianos I think you can close the issue.

**Comment by kardianos** [comment]
I'd like to do one more thing: could we rename a few fields? What do you think of this?
```
type TVP struct {
    //TVP param name, mustn't be default value
    TypeName string
    //TVP Value Param must be the slice, mustn't be nil
    Value interface{}
}
```

And update the error message in:
```
    ErrorEmptyTVPTypeName = errors.New("TVPTypeName must not be empty")
    ErrorTypeSlice        = errors.New("TVPType must be slice type")
    ErrorTypeSliceIsEmpty = errors.New("TVPType mustn't be null value")
```

**Comment by NikitaDef** [comment]
I agree.
