### ISSUE TITLE
The commands like "GRANT CONNECT ON ENDPOINT::SqlEndpoint TO DbAgent" fails to execute. 

### ISSUE THREAD

**Issue by shuoyang2016** [denisenkom/go-mssqldb#462]
Whenever the parser see's a ':', it thinks that the subsequent token is a parameter. Hence it interprets SqlEndpoint as a parameter and 
a command like db.Exec("GRANT CONNECT ON ENDPOINT::Endpoint TO DbAgent") fails with error message "mssql: expecting arguments=1, but passed 0"
The issue is in ParseNormal function of parser.go file when encounters ':' character, it changes the state to parse agrument. Could you fix the logic to avoid it for two '::' ?

**Comment by kardianos** [comment]
Use the "sqlserver" driver NOT the "mssql" driver. "mssql" will be removed prior to a v1 release.

**Comment by shuoyang2016** [comment]
Never mind. We just found we could do "GRANT CONNECT ON ENDPOINT::[Endpoint] " and it just worked.

**Comment by shuoyang2016** [comment]
Thank you for the quick response!
