### ISSUE TITLE
Ability to call stored procedures without parameter names

### ISSUE THREAD

**Issue by StevenJUpton** [denisenkom/go-mssqldb#469]
Hi,

I have the need to call stored procedures by passing the values without using parameter names. (the values are passed using the correct parameter order).

This seems possible with this driver but I had to alter 1 line of code in order to do it.

in the mssql.go file the function makeRPCParams adds a parameter name to parameters which do not have 1 already. 

if len(val.Name) > 0 {
			name = "@" + val.Name
		} else {
			name = fmt.Sprintf("@p%d", val.Ordinal)
		}

If I change this to just set the parameter name to an empty string this gives me the functionality I am looking for.

if len(val.Name) > 0 {
			name = "@" + val.Name
		} else {
			name = ""
		}
 
Is there a way to call into this driver and allow this without the above change or can this be included as new functionality moving forward ?

Thanks

**Comment by kardianos** [comment]
Is this possible in other SQL Server drivers, like ADO.NET?

**Comment by v-kaywon** [comment]
Some drivers support it (e.g., Microsoft drivers for PHP and OLE DB driver) and some don't (e.g., .NET Framework (see [SqlCommand.Parameters](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.parameters?redirectedfrom=MSDN&view=netframework-4.8#System_Data_SqlClient_SqlCommand_Parameters)))

**Comment by kardianos** [comment]
@v-kaywon Oh, I bet they do so by appending the build named parameters (@p1) to the parameter list on the named proc. I don't think we support doing so now, but I'd be open to a PR that add such support.

**Comment by v-kaywon** [comment]
@kardianos Yes you're right. I inspected the tds packet sent from the OLEDB driver and it did replace the `?` parameter placeholder with `@p1`. I'll add this issue to our backlog for now and hopefully will get to it soon.

**Comment by v-kaywon** [comment]
I just realized the `?` parameter placeholder is already supported in the `mssql` driver, although it is not recommended to use that driver.

I've made a fix in PR #495 to solve @StevenJUpton's issue, which is to NOT name the parameters to p1, p2, etc if the query being executed is a stored procedure.

**Comment by v-kaywon** [comment]
@StevenJUpton Can you try the fix in the latest driver?

**Comment by StevenJUpton** [comment]
@v-kaywon I have tried the latest version of the driver and can confirm that making RPC calls without named parameters is now working. Thanks
