### ISSUE TITLE
Can't use TVP with more than one period in the name

### ISSUE THREAD

**Issue by James-McPherson** [denisenkom/go-mssqldb#473]
When I try to use the following code:

`tvp := mssql.TVP{
	TypeName:	"Mydatabase.example.MyTVPType",
	Value:		data,
}
	
result, err := conn.Exec("EXEC Mydatabase.example.MyTVPProcedure ?;", tvp)
if err != nil {
	fmt.Println(err)
}`

I get the error:
wrong tvp name

This is because the getSchemeAndName method in tvp_go19.go returns an error if there's more than two period-separated terms in the TypeName. I tried hacking it by using the extra term as part of the schema and as part of the type name, but sql didn't like that.

The same issue does not happen with stored procedure names.

Edit: One workaround is to include "database=Mydatabase" in the connection string and just not include "Mydatabase." in the procedure/TVP names.

**Comment by NikitaDef** [comment]
@James-McPherson By [documentation](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/0dfc5367-a388-4c92-9ba4-4d28e775acbc)
""DbName is required to be zero-length, only OwningSchema and TypeName can be specified.
