### ISSUE TITLE
Trouble connecting with Active Directory authentication

### ISSUE THREAD

**Issue by danielnelson** [denisenkom/go-mssqldb#475]
I am trying to help a influxdata/telegraf user connect to SQL Server using Active Directory authentication, but the connection is being closed.  I've read through several existing/past issues but I'm far from a Windows expert so I wasn't able to determine if any were the same issue.

We are using MS 2016 SQL Version 13.0.4001, SQL Server authentication is working but would like to use Windows authentication.

I wrote a small test program:
```go
package main

import (
	"database/sql"
	"log"
	"os"

	_ "github.com/denisenkom/go-mssqldb"
)

func main() {
	if len(os.Args) != 2 {
		log.Fatalf("usage: %s <connstring>", os.Args[0])
	}

	connString := os.Args[1]
	conn, err := sql.Open("mssql", connString)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	err = conn.Ping()
	if err != nil {
		log.Fatal(err)
	}
}
```

We have tried a variety of connection strings, but our best guess for what we should be using is this one:
```
Server=localhost;Port=1433;User Id=;log=63;
```

Here are the results of running the above program:
```
C:\>sqlserver-test.exe "Server=localhost;Port=1433;User Id=;log=63;"
select 1;
Failed to send SqlBatch with write tcp [::1]:64337->[::1]:1433: wsasend: An existing connection was forcibly closed by the remote host.
failed to send SQL Batch: write tcp [::1]:64337->[::1]:1433: wsasend: An existing connection was forcibly closed by the remote host.
```

In the SQL Server logs it reports that the connection has succeeded:
```
2019-05-20 15:13:00.14 Logon       Login succeeded for user 'XXXXXXXX\yyyyyy'. Connection made using Windows authentication. [CLIENT: ::1]
```

**Comment by kardianos** [comment]
Ths is issue may be https://github.com/denisenkom/go-mssqldb/issues/383 .

**Comment by danielnelson** [comment]
Thanks for the information @kardianos, the authentication picture is a bit hazy for me, can you help me understanding the pieces in play and what support we would need?

I read some issues which indicate AD authentication should be working in at least some situations, and searching other sites indicates that AD can use Kerberos or NTLMv2 auth.  I have been told that this system supports NTLMv2 (not v1), do you think it would be possible to make this connection using this method without adding Kerberos support?

**Comment by danielnelson** [comment]
So far we have been unable to make any real progress debugging this issue.  We noticed that sometimes when connecting we are not receiving the `wsasend` error, so I updated the test program to allow custom queries:

```go
func main() {
	if len(os.Args) != 3 {
		log.Fatalf("usage: %s <connstring> <query>", os.Args[0])
	}

	connString := os.Args[1]
	conn, err := sql.Open("mssql", connString)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	rows, err := conn.Query(os.Args[2])
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()

	columns, err := rows.Columns()
	if err != nil {
		log.Fatal(err)
	}

	i := 0
	for rows.Next() {
		i++
		var columnVars []interface{}

		columnMap := make(map[string]*interface{})
		for _, column := range columns {
			columnMap[column] = new(interface{})
		}

		for i := 0; i < len(columnMap); i++ {
			columnVars = append(columnVars, columnMap[columns[i]])
		}

		err := rows.Scan(columnVars...)
		if err != nil {
			log.Fatal(err)
		}

		fmt.Printf("-[ RECORD %d ]--------------------------\n", i)
		for k, v := range columnMap {
			fmt.Printf("%s:\t%v\n", k, *v)
		}
	}
}
```

It seems that sometimes the program sends without error and sometimes it returns an error, but never retrieves the actual table contents (shell session copied from screen shot):
```
C:\>sqlserver-test.exe "Server=localhost;Port=1433;User Id=;log=63;" "select * from sys.databases:"
2019/05/30  14:01:53 select * from sys.databases;
C:\>
C:\>sqlserver-test.exe "Server=localhost;Port=1433;User Id=;log=63;" "select * from sys.databases:"
2019/05/30  14:01:53 select * from sys.databases;
2019/05/30  14:01:53 Failed to send SqlBatch with write tcp [::1]:64337->[::1]:1433: wsasend: An existing connection was forcibly closed by the remote host.
2019/05/30  14:01:53 failed to send SQL Batch: write tcp [::1]:64337->[::1]:1433: wsasend: An existing connection was forcibly closed by the remote host.
C:\>
```

**Comment by denisenkom** [comment]
Looks like fix has been merged.  Reopen if this is not fixed.

**Comment by danielnelson** [comment]
I can confirm this is working now, thanks everyone!
