### ISSUE TITLE
how to handle multiple results

### ISSUE THREAD

**Issue by Clago** [denisenkom/go-mssqldb#477]
procedure return multiple result，i dont't how to get result2's result?

```
        var testSql = `
select 1;
select 2;
`
	rows,err:=sqlServer.Query(testSql)
	if err!=nil{
		log.Fatal(err)
	}

	var id int
	for rows.Next(){
		rows.Scan(&id)
		log.Println(id)
	}
```

**Comment by kardianos** [comment]
https://godoc.org/database/sql#Rows.NextResultSet

**Comment by kardianos** [comment]
Or for table buffers: https://godoc.org/bitbucket.org/kardianos/table

**Comment by Clago** [comment]
3q。Because I don't know how to use NexResultSet,so create an issue,but I have found the official sql example.
https://golang.org/src/database/sql/example_test.go.
I already know how to use.
