### ISSUE TITLE
tcp connection for failoverpartner

### ISSUE THREAD

**Issue by DimaBelov** [denisenkom/go-mssqldb#478]
Why this 'server=tcp:server1;failoverpartner=server2' works,
and this 'server=tcp:server1;failoverpartner=tcp:server2' not working?

Error is 'lookup tcp:server2: no such host'

**Comment by v-kaywon** [comment]
Looks like SQL Server not accept protocol prefix in the failoverpartner attribute. According to [this documentation](https://docs.microsoft.com/en-us/sql/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client?view=sql-server-2017), the failoverpartner attribute only accept the name of the failover partner server. While the server attribute accepts the protocol prefix.
