### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by duc-nguyen-locm** [denisenkom/go-mssqldb#48]
I am getting failure when trying to login.  I have 2008 R2 SP2.
Using Go 1.3.
Thanks!

**Comment by bradleyankrom** [comment]
I've been running into that "connection reset by peer" error as well (running SQL Server 2008 SP3 X64); any ideas? I tried disabling encryption, but I still received the error.

**Comment by denisenkom** [comment]
Did you do this: you need to install SP2. See https://github.com/denisenkom/go-mssqldb#known-issues
?

**Comment by dkolli** [comment]
adding "encrypt=disable"  at the end of the connection string solved the issue. thanks @ZhenchongLi for the suggestion.
