### ISSUE TITLE
How to use tvp tag

### ISSUE THREAD

**Issue by jwenz723** [denisenkom/go-mssqldb#484]
I am a little lost on how to properly use the `tvp` tag on my struct fields.

I see in the tvp example the use of the `-` value [here](https://github.com/denisenkom/go-mssqldb/blob/eb9f6a1743f30383c8168cc520ca5db1f744d6f4/examples/tvp/tvp.go#L23) to indicate that the field should not be used in the tvp.

However, it doesn't seem like any value other than `-` is used for anything? 

For example:

I changed the createTVP command to (changed the type of message4 to BIGINT):
```
createTVP = `
		CREATE TYPE TestTVPSchema.exampleTVP AS TABLE
		(
			message1	NVARCHAR(100),
			message2	NVARCHAR(100),
			message3	NVARCHAR(100),
			message4	BIGINT
		)`
```

I changed the TvpExample struct to (I moved `MessageWithTVPTag` to come after  `MessageJSONSkipWithTVPTag` and put `tvp` tags on each to try to force them into the correct columns):
```
type TvpExample struct {
	MessageWithoutAnyTag      string
	MessageWithJSONTag        string `json:"message"`
	MessageJSONSkipWithTVPTag int `tvp:"message4"`
	MessageWithTVPTag         string `tvp:"message3"`

	OmitFieldJSONTag string `json:"-"`
	OmitFieldTVPTag  string `json:"any" tvp:"-"`
	OmitFieldTVPTag2 string `tvp:"-"`
}
```

Then when I execute the app, the stored proc fails to execute with the error: `mssql: Error converting data type nvarchar to bigint.`

It looks like the `tvp` tags are not being used to correlate the struct fields with the proper columns in the tvp and it is instead going off of the position of the field within the struct.

Is this correct behavior? Is there a way to use the `tvp` tags to force the values into the proper column?

Thanks!

**Comment by NikitaDef** [comment]
@jwenz723 by [documention ](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/0dfc5367-a388-4c92-9ba4-4d28e775acbc)
`ColName MUST be a zero-length string in the TVP`
Do other drivers allow setting fields ordering?

**Comment by jwenz723** [comment]
I am new to TVP, so my question may be invalid.

From the link you sent, I understand it as saying that when using TVP you must pass the column values in the same order as they exist in the user defined table type unless you use `TVP_COLUMN_ORDERING`. However, I don't see a way to make use of `TVP_COLUMN_ORDERING` in this package. Can you tell me if there is a way to do this?

In tvp_go19.go I see the code below which makes me believe that specifying `TVP_COLUMN_ORDERING` is not possible with this packge because the ordering is always being set to a value of `i` (`tvpFieldIndexes = append(tvpFieldIndexes, i)`):
```
func (tvp TVP) columnTypes() ([]columnStruct, []int, error) {
...
...
	tvpFieldIndexes := make([]int, 0, columnCount)
	for i := 0; i < columnCount; i++ {
		field := tvpRow.Field(i)
		tvpTagValue, isTvpTag := field.Tag.Lookup(tvpTag)
		jsonTagValue, isJsonTag := field.Tag.Lookup(jsonTag)
		if IsSkipField(tvpTagValue, isTvpTag, jsonTagValue, isJsonTag) {
			continue
		}
		tvpFieldIndexes = append(tvpFieldIndexes, i)
...
...
```

**Comment by NikitaDef** [comment]
Sorry, for wrong information.
I wanted tell you `TVP_COLUMN_ORDERING` isn't defined in tvp_go19.go.
And `tvpFieldIndexes` uses only for skip the fields in current realisation.

Then I've made the TVP. I've not thought about fields ordering.
I don't sure how to make fields ordering.
I don't know TVP_COLUMN_ORDERING  or tvpFieldIndexes.

But I think `tvp:"isskip,position"`
Also fields ordering uses, all other fields must have `tvp` tag with order number.
```
type TvpExample struct {
	MessageWithoutAnyTag      string `tvp:"any,1"`
	MessageWithJSONTag        string `json:"message" tvp:"any2,2"`
	MessageJSONSkipWithTVPTag int `tvp:"message4,4"`
	MessageWithTVPTag         string `tvp:"message3,3"`

	OmitFieldJSONTag string `json:"-"`
	OmitFieldTVPTag  string `json:"any" tvp:"-"`
	OmitFieldTVPTag2 string `tvp:"-"`
}
```

**Comment by jwenz723** [comment]
It looks like that does not work. The only value that is used in the `tvp` tag is `-`. All other values just evaluate to NOT `-`.

I just found the documentation [here](https://github.com/denisenkom/go-mssqldb/blob/master/doc/how-to-use-table-valued-parameters.md), don't know why I didn't see it before. In the documentation it does not mention anything about column order, and from what I can see it is accurate according to the current capabilities of the go-mssqldb package.

I think it would be nice to be able to specify ordering like you suggested in your comment (`tvp:"any,1"`). So maybe this could go in as a feature request. But I am ok with closing this issue if that is not desired behavior.
