### ISSUE TITLE
Dependency broken in last gitea version

### ISSUE THREAD

**Issue by manalejandro** [denisenkom/go-mssqldb#491]
```
go: github.com/denisenkom/go-mssqldb@v0.0.0-20180314172330-6a30f4e59a44:
reading https://proxy.golang.org/github.com/denisenkom/go-mssqldb/@v/v0.0.0-20180314172330-6a30f4e59a44.mod: 400 Bad Request
```

**Comment by manalejandro** [comment]
This is my [Dockerfile](https://gist.github.com/manalejandro/cce2ff9eee0db9e713df21c141a994d9) which follow installation with `make generate all` but still appears that warning

**Comment by v-kaywon** [comment]
@manalejandro I'm not that familiar with gitea, but do you know where the version `v0.0.0-20180314172330-6a30f4e59a44` comes from? It seems to be an invalid version (you'll see if you go to https://proxy.golang.org/github.com/denisenkom/go-mssqldb/@v/v0.0.0-20180314172330-6a30f4e59a44.mod in a regular browser).

**Comment by manalejandro** [comment]
Sorry, will debug and open one issue to gitea. Thanks
