### ISSUE TITLE
Error loading module requirement

### ISSUE THREAD

**Issue by parikhkunalb** [denisenkom/go-mssqldb#494]
When I try to run below command 
go get github.com/denisenkom/go-mssqldb

I am seeing following errors:

go: finding github.com/denisenkom/go-mssqldb latest
go: honnef.co/go/tools@v0.0.0-20180728063816-88497007e858: unrecognized import path "honnef.co/go/tools" (parse https://honnef.co/go/tools?go-get=1: no go-import meta tags ())
go: honnef.co/go/tools@v0.0.0-20190106161140-3f1c8253044a: unrecognized import path "honnef.co/go/tools" (parse https://honnef.co/go/tools?go-get=1: no go-import meta tags ())
go: honnef.co/go/tools@v0.0.0-20190102054323-c2f93a96b099: unrecognized import path "honnef.co/go/tools" (parse https://honnef.co/go/tools?go-get=1: no go-import meta tags ())
go: error loading module requirements

**Comment by v-kaywon** [comment]
@parikhkunalb Which version of Go are you using? I think the issue should be fixed in Go 1.12. Can you run `go version`? Also, can you show me how your `go.mod` looks like?
