### ISSUE TITLE
bulk insert failed when fieldtype is varchar(4000)

### ISSUE THREAD

**Issue by LiPL2017** [denisenkom/go-mssqldb#497]
Hi,
 I found bulk insert failed when fieldtype is varchar and length more than 4000. I read the source file [types.go](https://github.com/denisenkom/go-mssqldb/blob/master/types.go#L1190)  varchar(4000) was translated to varchar(max).
SqlServer 2012, varchar maxlen is 8000.

**Comment by chris-rossi** [comment]
I believe I've reproduced this and you are correct it should be translated to varchar(max) when it's larger than 8000 bytes. I will look into this.

@kardianos or @denisenkom could you assign this to me.
