### ISSUE TITLE
Allow to construct Driver instance from outside lib

### ISSUE THREAD

**Issue by zygisx** [denisenkom/go-mssqldb#498]
**Is your feature request related to a problem? Please describe.**
I'm using external library for application performance monitoring (APM), which wraps database driver and then helps to monitor queries performance. To configure that I need to pass sql driver (`database/sql/driver.Driver`) instance to performance monitoring lib. Here is how that code looks like:
```
apmsql.Register(`mssql`, &mssql_driver.Driver{})
```
Also I'm using `mssql` driver with `processQueryText = true` which support `?` in queries.
Though with code above I cannot initialize driver instance with `processQueryText` setted to true because there is no public API for that. 

So I suggest to expose setter for it on Driver.

**Describe the solution you'd like**
Driver should have setter for `processQueryText`

**Describe alternatives you've considered**
Alternative could be exposing `driverInstance` from `mssql.go` file. Here is how source code looks like:
```
var driverInstance = &Driver{processQueryText: true}
```

Though I believe setter is cleaner solution

I could provide PR for that.

**Comment by kardianos** [comment]
It is my intent to remove processQueryText altogether prior to v1 being release.
