### ISSUE TITLE
GUID parsing incorrectly

### ISSUE THREAD

**Issue by petertranfl** [denisenkom/go-mssqldb#504]
**Describe the bug**
When retrieving the GUID from an MSSQL database, the first half of the GUID is scrambled, while the latter half is correct.

**To Reproduce**
When binding the GUID using a struct, with data type UUID. Use the modified func decodeGuid to fix.

type Record struct {
ID uuid.UUID
}

func decodeGuid(buf []byte) []byte {
	res := make([]byte, 16)
	copy(res, buf)
	res[0], res[1], res[2], res[3] = res[3], res[2], res[1], res[0]
	res[4], res[5] = res[5], res[4]
	res[6], res[7] = res[7], res[6]
	return res
}

**Expected behavior**
Correct GUID display

### Further technical details
SQL Server version: (e.g. SQL Server 2017)
Operating system: (e.g. Windows 2019, Ubuntu 18.04, macOS 10.13, Docker container)
Table schema

**Additional context**
This issue was already fixed but no pull request was done. Here is the link to the post showing the fix as well.

https://github.com/denisenkom/go-mssqldb/issues/56

**Comment by v-kaywon** [comment]
@petertranfl the old issue mentioned cross operating systems. Can you let us know your client side operating system and the server side operating system?

**Comment by petertranfl** [comment]
Microsoft SQL Server 2014 (SP3) (KB4022619) - 12.0.6024.0 (X64) 
	Sep  7 2018 01:37:51 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

Client side operating system is Windows 10 (VM Parallels)

I created a pull request with the proposed changes

**Comment by petertranfl** [comment]
You can replicate the issue by mapping the GUID from a MS SQL database to a struct and displaying the struct
