### ISSUE TITLE
Return Status on procedure with parameters

### ISSUE THREAD

**Issue by navossoc** [denisenkom/go-mssqldb#507]
Hi, I would like to know if it is possible to return the status of a procedure with parameters.

I saw one example on the documentation and it works, but as soon I try to pass one parameter to my procedure it won't work anymore.
Not sure if I'm doing it wrong or if it is not possible.

An example would be something like this:

```sql
CREATE PROCEDURE sp_something
	@v varchar(10)
AS
BEGIN
	SELECT @v
	RETURN 22
END
GO
```

I'm trying to figure out what would be equivalent to this:
```sql
DECLARE	@return_value int

EXEC	@return_value = sp_something 'value'
SELECT	'Return Value' = @return_value

GO
```

```go
var rs mssql.ReturnStatus
_, err := db.Exec("sp_something @v", &rs, sql.Named("@v", "value"))
log.Printf("return status = %d", rs)
```

Or

```go
var rs mssql.ReturnStatus
_, err := db.Exec("sp_something @v", sql.Named("@v", "value"), &rs)
log.Printf("return status = %d", rs)
```

On my tests `rs` is always zero.

Someone can provide a little help?

Thanks.

**Comment by v-kaywon** [comment]
@navossoc when you exec a stored procedure, you do not put the parameter placeholder in the exec string. Try this instead:
```
var rs mssql.ReturnStatus
_, err = db.Exec("sp_something", &rs, sql.Named("v", "value"))
log.Printf("return status = %d", rs)
```
`rs` should be 22 as expected.

**Comment by navossoc** [comment]
@v-kaywon Yes, it seems to solve the problem. I don't know about that, thanks.

Now I wonder if it is possible to use `Query` instead of `Exec`.

Looking at the code, it seems something doable.

```go
func (s *Stmt) processQueryResponse(ctx context.Context) (res driver.Rows, err error) {
// ...
		case []columnStruct:
			cols = token
			break loop
		case ReturnStatus:
			s.c.setReturnStatus(token)
```

The value seems to be there, but it never get assigned.
If I don't break the loop, the return status will came back, but the rows will fail.

**Comment by v-kaywon** [comment]
@navossoc Yes return status doesn't seem to be working with query at the moment. I've created PR #509 to address this issue, maybe you can try it out.

**Comment by navossoc** [comment]
@v-kaywon looks good.

**Comment by v-kaywon** [comment]
I took a look at `QueryRow`, unfortunately that's implemented in the `sql` package, and inside the implementation, `Next` is only called once. Since it's inside the sql package, I cannot change that. I'll put this as a limitation in the README.

**Comment by navossoc** [comment]
Great!
