### ISSUE TITLE
bulkcopy: float64 to decimal[18, 2] is not expected

### ISSUE THREAD

**Issue by cugarwang** [denisenkom/go-mssqldb#514]
pass 264.9 in bulkcopy but got 264.89 in database.

Reproduce:

add test case in bulkcopy_test.go
testValues:
  {"test_decimal_18_2", 264.9},
tablesql:
  [test_decimal_18_2] [decimal](18, 2) NULL,
  
bulkcopy_test.go:154: columns test_decimal_18_2 : expected: 264.9, got: [50 54 52 46 56 57]

**Comment by v-kaywon** [comment]
@cugarwang  Looks like it's a truncation issue when a float is casted to an int. I've created a PR to address this issue (PR #515 ). Do you want to give it a try?

**Comment by cugarwang** [comment]
@v-kaywon It's ok now, Thanks.
