### ISSUE TITLE
datettimeoffset not working on bulk insert

### ISSUE THREAD

**Issue by thailandmatt** [denisenkom/go-mssqldb#517]
I am trying to bulk insert data into a table with a column type of datetimeoffset(7).

I have narrowed it down to a single field with a single record and a single time.Time value, but I continue to get an error similar to this:

```mssql: Invalid column value from bcp client for colid 1```

**To Reproduce**
(err handling / db connection omitted)
```
        txn, err := db.Begin()

	stmt, err := txn.Prepare(mssql.CopyIn("MyTable", mssql.BulkOptions{},
		"StartTime",
	))

         for _, recordToStore := range recordsToStore {		
		_, err = stmt.Exec(
			recordToStore.StartTime,
		)

	result, err := stmt.Exec()
```

**Expected behavior**
I would like it to do the insert

### Further technical details
SQL Server version: SQL Server 13.0.5101.9
Operating system: Windows 10

StartDateTime datetimeoffset(7)

**Additional context**
If I change the field type in MSSQL to datetime then the bulk insert succeeds

**Comment by chris-rossi** [comment]
Hi @thailandmatt, I've reproduced the issue you've encountered. I'll investigate further and get back to you soon.

**Comment by jwebb** [comment]
This should have been fixed by https://github.com/denisenkom/go-mssqldb/commit/dba0d6a56ef2df533911ac5733709e37d42f2830  - can you confirm what version you're running?

**Comment by chris-rossi** [comment]
Didn't notice that commit, fixes it on my end. Thanks @jwebb.
