### ISSUE TITLE
Allow timeouts to be defined when getting instances from server

### ISSUE THREAD

**Issue by fabiang** [denisenkom/go-mssqldb#522]
Hello,

I just had the problem, that the five seconds to get the instances list from SQLServer in no enough. I'm running into the following error:

```
Unable to get instances from Sql Server Browser on host %s: dial udp: i/o timeout
```

It seems the value for the timeouts is hardcoded in `tds.go` in the function `getInstances()`. Would be good to have another parameter to be passed by the connection string, instead of these hardcoded values.

Don't ask me why it's taking more then five seconds from to time to time. I'm still looking into this, as this should be an network or server related issue.

My current workaround is it, to define the instance port and skip passing the instance name in the connection string.

**Comment by v-kaywon** [comment]
Looks like there may have been a reason to set it to 5 seconds (see commit ffa91a0c914fb9807b11c781b85ec095bdc46e24). @denisenkom is there a reason why the timeout was hard coded to 5 seconds? Do you agree with @fabiang that it should be a settable parameter in the connection string? If so, I can help contribute.

**Comment by v-kaywon** [comment]
@fabiang seems like that's actually what the `dial timeout` property is for, but it is currently overwritten by the 5 seconds value. I'll created PR #523 addressing this issue. Please give it a try.

**Comment by v-kaywon** [comment]
@fabiang the fix is merged now. Can you give it a try? You can set the timeout by using the `dial timeout` property in the connection string.

**Comment by fabiang** [comment]
I've a job running every few minutes which is testing this right now. I'll give it time till tomorrow to verify it's fixed. Of cause it's possible that the network latency or the SQLServer load is better now.

**Comment by fabiang** [comment]
250 runs later I can say it's working for me. Thank you very much!
