### ISSUE TITLE
Query notification timeout unit

### ISSUE THREAD

**Issue by jackwakefield** [denisenkom/go-mssqldb#526]
According to [2.2.5.3.1 Query Notifications Header](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/e168d373-a7b7-41aa-b6ca-25985466a7e0)
> The time unit of NotifyTimeout is milliseconds

But in [SetQueryNotification](https://github.com/denisenkom/go-mssqldb/blob/master/mssql.go#L400) this is being set in seconds
```go
func (s *Stmt) SetQueryNotification(id, options string, timeout time.Duration) {
	to := uint32(timeout / time.Second)
	if to < 1 {
		to = 1
	}
	s.notifSub = &queryNotifSub{id, options, to}
}
```

Is that correct/intentional? I'll be happy to submit a pull request if not.

**Comment by chris-rossi** [comment]
This does appear to be incorrect, I don't see the timeout being scaled to milliseconds before getting packed. I would go ahead with a pull request.

**Comment by chris-rossi** [comment]
This issue can be closed.
