### ISSUE TITLE
wsarecv: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by zhlicen** [denisenkom/go-mssqldb#531]
Got the following error when starting a TX or executing any queries.
DB version is:  `Microsoft SQL Server 2008 R2 (RTM)`
Connection string is like:
```
"odbc:server=192.168.34.253;user id=sa;database=master;password={AdminAdmin};app name={myapp}"
```

- Exception message:
```
panic: Login error: read tcp 192.168.18.3:64585->192.168.34.253:1433: wsarecv: An existing connection was forcibly closed by the remote host
Stack trace:
```

- Code snippest:

```go
connString := "odbc:server=192.168.34.253;user id=sa;database=master;password={AdminAdmin};app name={MyAppName}" // fmt.Sprintf("odbc:server=192.168.34.253;user id=sa;database=master;password=AdminAdmin",`
conn, err := sql.Open("sqlserver", connString)
if err != nil {
	log.Fatal("Open connection failed:", err.Error())
}
fmt.Printf("Connected!\n")

_, err = conn.Begin()
if err != nil {
	panic(err)
}
```
- Output:
```
Connected!
panic: Login error: read tcp 192.168.18.3:49617->192.168.34.253:1433: wsarecv: An existing connection was forcibly closed by the remote host.
```

- Other tests:
  - Connect the SQL Server 2008 with DBeaver(a db tool) on the same client PC as the code: √ everything seems alright  
  - Connect another SQL Server 2016 with the same conn string: √ it works!!!

**Comment by v-kaywon** [comment]
Please take a look at the Known issues section in README:

> SQL Server 2008 and 2008 R2 engine cannot handle login records when SSL encryption is not disabled. To fix SQL Server 2008 R2 issue, install SQL Server 2008 R2 Service Pack 2. To fix SQL Server 2008 issue, install Microsoft SQL Server 2008 Service Pack 3 and Cumulative update package 3 for SQL Server 2008 SP3. More information: http://support.microsoft.com/kb/2653857

**Comment by zhlicen** [comment]
> Please take a look at the Known issues section in README:
> 
> > SQL Server 2008 and 2008 R2 engine cannot handle login records when SSL encryption is not disabled. To fix SQL Server 2008 R2 issue, install SQL Server 2008 R2 Service Pack 2. To fix SQL Server 2008 issue, install Microsoft SQL Server 2008 Service Pack 3 and Cumulative update package 3 for SQL Server 2008 SP3. More information: http://support.microsoft.com/kb/2653857

Thanks..issue solved after upgrade the DB
