### ISSUE TITLE
How to set the charset with dsn?

### ISSUE THREAD

**Issue by Karel-Xiang** [denisenkom/go-mssqldb#534]
Does dsn support charset in dsn?
for example “sqlserver://sa:tencent_123@10.66.136.79:1433?database=Test_DB&connection+timeout=30&chartset=utf8”

**Comment by chris-rossi** [comment]
Hi @Karel-Xiang, what are you hoping to do? Go is UTF-8 encoded by default.

**Comment by Karel-Xiang** [comment]
And gbk or big5？

**Comment by chris-rossi** [comment]
The driver doesn't currently have a charset parameter to set gbk or big5.

**Comment by Karel-Xiang** [comment]
Thanks..
