### ISSUE TITLE
Whether ipv6 is supported and how to use it?

### ISSUE THREAD

**Issue by Karel-Xiang** [denisenkom/go-mssqldb#537]
Whether ipv6 is supported and how to use it?

**Comment by chris-rossi** [comment]
It might be supported because the driver uses the "net" library but I haven't verified this. Have you tried connecting using an IPv6 address as the servername in the connection string? I will look into this.

**Comment by Karel-Xiang** [comment]
Thanks,it is supported ipv6,I have verified this.
