### ISSUE TITLE
Should be no instance resolution if server, instance and port are specified

### ISSUE THREAD

**Issue by raufismayilov** [denisenkom/go-mssqldb#539]
When specifying server, instance and port (both URL and ADO connection string format) the connector tries to list the server instances while the information should be sufficient to connect directly to the instance. In the situation where it is impossible to enumerate the list of servers this component doesn't work.

Connection string formats are as follows:

sqlserver://uid:pwd@192.168.1.10:50000/instance?database=db
server=192.168.1.10\instance;port=50000;database=db;user id=uid;password=pwd

I can see from the code that in the method "connect" in "tds.go" it is checked that if the instance is not empty then the connector tries to list all instances.

![image](https://user-images.githubusercontent.com/32014736/69128361-8f770b00-0ac5-11ea-8873-7018df2974ba.png)

**To Reproduce**

```package main

import (
	"database/sql"
	"log"
	"time"

	_ "github.com/denisenkom/go-mssqldb"
)

func main() {
	cstr := "server=srv\\inst;port=50000;database=db;user id=uid;password=pwd"

	c, err := sql.Open("sqlserver", cstr)

	if err != nil {
		log.Fatalf("unable to open connection to database: %q", err)
	}

	defer c.Close()

	r := c.QueryRow("select getdate() as dt")

	var dt time.Time

	err = r.Scan(&dt)

	if err != nil {
		log.Fatalf("unable to get data from db: %q", err)
	}
}
```

**Expected behavior**
If server, instance and port are specified then the connector should directly try to connect the database (at least Management Studio is able to do that).

### Further technical details
SQL Server version: Microsoft SQL Server 2016 (RTM) - 13.0.1601.5 (X64)
Operating system: Windows Server 2016 Datacenter 6.3 <X64> (Build 14393: ) (Hypervisor)

**Comment by chris-rossi** [comment]
Hi @raufismayilov, I'll look further into this.

**Comment by raufismayilov** [comment]
I have just fixed this in PR https://github.com/denisenkom/go-mssqldb/pull/543#issue-344604995
