### ISSUE TITLE
bulkcopy: mssql: type 29 not implemented (TIME data type)

### ISSUE THREAD

**Issue by xhit** [denisenkom/go-mssqldb#550]
**Describe the bug**
I'm trying to insert a value in column with data type TIME with bulkcopy and I get `bulkcopy: mssql: type 29 not implemented`

**Expected behavior**
I can insert `DATE`, `DATETIME`, `DATETIME2`, `DATETIMEOFFSET` and `SMALLDATETIME` date types with bulkcopy applying the layout for the correspondent date type with `time.Parse`. I think is possible with `TIME` date type with this layout: `15:04:05.000`

### Further technical details
SQL Server version: SQL Server 2014
Operating system: Windows 10
Table schema
```sql
CREATE TABLE [dbo].[datetest](
	[r] [time](7) NULL,
	[v] [date] NULL,
	[w] [datetime] NULL,
	[x] [smalldatetime] NULL,
	[y] [datetime2](7) NULL,
	[z] [datetimeoffset](7) NULL
)
```

**Comment by chris-rossi** [comment]
From a quick look at `makeParam()` it doesn't appear that we currently support the `time` type in the bulkcopy interface. This seems like it would be a good feature to add.
