### ISSUE TITLE
Empty Strings Instead Of Nulls Using Bulk

### ISSUE THREAD

**Issue by lyashenko-m** [denisenkom/go-mssqldb#555]
**Description**
We are using bulk-copy to insert data to our storage. Driver replaces null values to empty strings "" if table column types have length more that 4000, VARCHAR(MAX) for example. If length is less or equal to 4000 - everything goes correct. Nulls are nulls.

**To Reproduce**
Create table test as such:
```sql
CREATE TABLE TestNulls (
 TestColumn  VARCHAR(MAX) NULL
);
```
use bulk insert api to insert data. Null values will be replaced to empty strings or to 0x0000 byte.
**Expected behavior**
Null values from source should be null independent of destination table column length.

**Additional context**
Here are my findings:
1. I see here https://github.com/denisenkom/go-mssqldb/blob/master/types.go#L217 a case for types which lengths > 8000
2. Here is the correct behavior happens: https://github.com/denisenkom/go-mssqldb/blob/master/types.go#L473
3. But if go to logical branch where length > 8000 I don't see any checking if buf is nil or empty at the beginning of function. There only check for 0 length and writes of terminator 0x0000 which represents as empty string in the resultsets.
https://github.com/denisenkom/go-mssqldb/blob/master/types.go#L698
4. Thus I can make a conclusion that if table column length > 8000 there is no possible to write nulls.
5. Could you please add here: https://github.com/denisenkom/go-mssqldb/blob/master/types.go#L692 something like that?
```go
func writePLPType(w io.Writer, ti typeInfo, buf []byte) (err error) {
	if buf == nil {
		err = binary.Write(w, binary.LittleEndian, uint64(_PLP_NULL))
		return
	} 
  ...
}
```
or fix bulk insert on another way? I may not be aware  of all the related places where it can affect to.

Thanks, Michael.

**Comment by chris-rossi** [comment]
Thanks for bringing this to our attention. It appears that we need to add more tests for bulk insert as well.

**Comment by MichaelLyashenko** [comment]
@chris-rossi Thanks for a quick reply! Hope you will fix it soon 👍

**Comment by denisenkom** [comment]
PR merged
