### ISSUE TITLE
Error when executing a query and records

### ISSUE THREAD

**Issue by yurineves92** [denisenkom/go-mssqldb#560]
I have this error when running.

`{
    "Error": "mssql: Transaction count after EXECUTE indicates a mismatching number of BEGIN and COMMIT statements. Previous count = 1, current count = 0."
}`

**Comment by chris-rossi** [comment]
Hi @yurineves92 could you provide us more information such as a description of how your using the driver or a repro script to help us understand your issue?

**Comment by yurineves92** [comment]
`
// Insere uma nova ocorrencia tipica
func newOccTypical(_POST map[string]interface{}) error {
	occ, err := helpers.LoadTypicalOccurrence(_POST)
	if err == nil {
		var db *sql.DB
		db, err = mssql.ConnMssDatabase()
		if err == nil {
			defer db.Close()
			var tx *sql.Tx
			tx, err = db.Begin()
			if err == nil {
				var rsp []map[string]interface{}
				rsp, err = insertTypical(occ, _POST, tx, err)
				if err == nil {
					err = insertTypicalOccSupplier(rsp, occ, _POST, tx, err)
					err = insertTypicalOccIssuers(rsp, occ, _POST, tx, err)
					err = insertTypicalOccExectors(rsp, occ, _POST, tx, err)
					//err = insertTypicalIssuerCorr(rsp, occ, _POST, tx, err)
					//err = insertTypicalExecutorCorr(rsp, occ, _POST, tx, err)
				}
				if err != nil {
					tx.Rollback()
				} else {
					err = tx.Commit()
				}
			}
			defer tx.Rollback() // The rollback will be ignored if the tx has been committed later in the function.
		}
	}
	return err
}`

**Comment by yurineves92** [comment]
func newOccTypical(_POST map[string]interface{}) error {
	occ, err := helpers.LoadTypicalOccurrence(_POST)
	if err == nil {
		var db *sql.DB
		db, err = mssql.ConnMssDatabase()
		if err == nil {
			defer db.Close()
			var tx *sql.Tx
			tx, err = db.Begin()
			if err == nil {
				var rsp []map[string]interface{}
				rsp, err = insertTypical(occ, _POST, tx, err)
				if err == nil {
					err = insertTypicalOccSupplier(rsp, occ, _POST, tx, err)
					err = insertTypicalOccIssuers(rsp, occ, _POST, tx, err)
					err = insertTypicalOccExectors(rsp, occ, _POST, tx, err)
					//err = insertTypicalIssuerCorr(rsp, occ, _POST, tx, err)
					//err = insertTypicalExecutorCorr(rsp, occ, _POST, tx, err)
				}
				if err != nil {
					tx.Rollback()
				} else {
					err = tx.Commit()
				}
			}
			defer tx.Rollback() // The rollback will be ignored if the tx has been committed later in the function.
		}
	}
	return err
}

**Comment by chris-rossi** [comment]
Is it possible that your queries contain an additional `BEGIN` or `COMMIT` within them?
