### ISSUE TITLE
The field before the time is null, and the time field cannot be taken out normally, which becomes 0001-01-01

### ISSUE THREAD

**Issue by zhaoziming** [denisenkom/go-mssqldb#568]
**Describe the bug**
![111](https://user-images.githubusercontent.com/5771422/79956803-3451a600-84b3-11ea-9865-d81a470d5b69.png)
![222](https://user-images.githubusercontent.com/5771422/79956994-8266a980-84b3-11ea-8c77-e2ccf4b17066.png)
![333](https://user-images.githubusercontent.com/5771422/79957111-b2ae4800-84b3-11ea-9895-2b44c1e1c114.png)
![00000](https://user-images.githubusercontent.com/5771422/79957952-ef2e7380-84b4-11ea-9c2b-454498c4d0a5.png)

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

**To Reproduce**
Include a complete code listing that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

**Expected behavior**

### Further technical details
SQL Server version: (e.g. SQL Server 2017)
Operating system: (e.g. Windows 2019, Ubuntu 18.04, macOS 10.13, Docker container)
Table schema

**Additional context**

**Comment by zhaoziming** [comment]
OS:CentOS 6.8
GO:go version go1.14.2 linux/amd64
`	sql := `
        select
            sGridID as grid_id,
            sCityName as city_name,
	        sMinLat as bd_min_lat,
	        sMaxLat as bd_max_lat,
	        sMinLng as bd_min_lng,
	        sMaxLng as bd_max_lng,
	        sMiddleLat as bd_middle_lat,
	        sMiddleLng as bd_middle_lng,
	        --iMapX as map_x,iMapY as map_y,
	        0 as map_x,0 as map_y,
	        --CONVERT(datetime,'2016-07-02 14:30:00',20) as data_time
	        dAddTime as data_time
        from 
            City_Grid_250 
        where 
            iState = 1 and sCityID != '' and sCityName = ?

	for rows.Next() {
		var grid_id, city_name string
		var bd_min_lat, bd_max_lat, bd_min_lng, bd_max_lng, bd_middle_lat, bd_middle_lng float64
		var gd_min_lat, gd_max_lat, gd_min_lng, gd_max_lng, gd_middle_lat, gd_middle_lng float64
		var map_x,map_y int
		var data_time time.Time
		rows.Scan(&grid_id, &city_name, &bd_min_lat, &bd_max_lat, &bd_min_lng, &bd_max_lng,
			&bd_middle_lat, &bd_middle_lng, &map_x, &map_y, &data_time)
    `

**Comment by kardianos** [comment]
Please ensure `rows.Scan` checks for errors.

```
err := rows.Scan(*grid_id, ...)
if err != nil {
    return err
}
```

Please add that check and inform this issue.

**Comment by zhaoziming** [comment]
I got it ,thx
