### ISSUE TITLE
sqlserver 2000 Login error

### ISSUE THREAD

**Issue by aaart123** [denisenkom/go-mssqldb#569]
go 1.12.5   windows 7    sqlserver2000   error:"Login error: unexpected EOF"

**Comment by kardianos** [comment]
sql server 2000 is not a supported version :/ Sorry. You may have better luck with an ODBC driver.

**Comment by aaart123** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Daniel Theophanes"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 晚上11:51
收件人:&nbsp;"denisenkom/go-mssqldb"<go-mssqldb@noreply.github.com&gt;;
抄送:&nbsp;"腾腾"<297329925@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [denisenkom/go-mssqldb] sqlserver 2000 Login error (#569)





 
sql server 2000 is not a supported version :/ Sorry. You may have better luck with an ODBC driver.
