### ISSUE TITLE
Query data from table on difference MSSQL servers 

### ISSUE THREAD

**Issue by chinkung** [denisenkom/go-mssqldb#581]
**Is your feature request related to a problem? Please describe.**
There is no way to join data from tables on difference MSSQL server using single command.

**Describe the solution you'd like**
Ability to connect to MSSQL database on difference server on single instance so you can perform cross table query on single command.

**Describe alternatives you've considered**
I need to open 2 db connections to both server and perform full select query on both tables and store it to memory then compare it one-by-one. This is impossible to do with table contains huge amount number of records (e.g. 100M+ records)

**Additional context**
It would be great if table comparison is also implemented so you can compare data on table to find difference, it will be helpful to validate data on replication server

**Comment by kardianos** [comment]
This isn't a thing for this package, rather you want to use linked servers.
