### ISSUE TITLE
Every colon ":" are treated like parameters

### ISSUE THREAD

**Issue by errob37** [denisenkom/go-mssqldb#587]
Having a SELECT like this:

`SELECT geography::ConvexHullAggregate(geography::Point(pb.latitude ,pb.longitude , 4326)).EnvelopeCenter() from pb`

is treated like this:

`SELECT geography:@ConvexHullAggregate(geography:@Point(pb.latitude ,pb.longitude , 4326)).EnvelopeCenter() from pb`

This issue was already corrected in PR [35](https://github.com/denisenkom/go-mssqldb/issues/35) but reverted when supporting named parameter.

Named parameter commit [d3f369](https://github.com/denisenkom/go-mssqldb/commit/d3f369efb673a78ad0a61da72514a2b3d4284593)

**Comment by kardianos** [comment]
use the "sqlserver" driver version not "mssql".
