### ISSUE TITLE
can not Execute GO command

### ISSUE THREAD

**Issue by majidbigdeli** [denisenkom/go-mssqldb#614]
```
query := "GO
CREATE TABLE [dbo].[user]
(
    [id] [int] NULL
)"
```
conn.ExecContext(context.Background(), query)

i get error "Incorrect syntax near 'GO'."

**Comment by tc-hib** [comment]
Hello.

This is not a valid instruction in T-SQL.
This is an instruction specific to some tools, such as sqlcmd, ssms and osql.
Microsoft's OLEDB driver does not make it work either.
This instruction is interpreted on the client side, before anything is done with the driver.

See : https://docs.microsoft.com/sql/t-sql/language-elements/sql-server-utilities-statements-go

**Comment by kardianos** [comment]
"GO" isn't T-SQL. It is processed by the client.

You can emulate this with the "batch" package.
https://pkg.go.dev/github.com/denisenkom/go-mssqldb/batch
