### ISSUE TITLE
go lib version tagging

### ISSUE THREAD

**Issue by 6543** [denisenkom/go-mssqldb#615]
@denisenkom  your pre-release was tagged with `0.9.0` but go need a `v` as prefix

docs: https://blog.golang.org/publishing-go-modules
"... semantic version has the form vMAJOR.MINOR.PATCH ..."

just noticed - hope you dont mid

**Comment by denisenkom** [comment]
thanks for reporting, created and alias tag v0.9.0, does it work now?

**Comment by 6543** [comment]
@denisenkom it works thanks :+1:
