### ISSUE TITLE
Export connection string parsing logic

### ISSUE THREAD

**Issue by coquagli** [denisenkom/go-mssqldb#624]
**Is your feature request related to a problem? Please describe.**
I would like for the connection string parsing logic in [/conn_str.go](https://github.com/denisenkom/go-mssqldb/blob/master/conn_str.go) to be exported. This would allow consuming applications to more easily perform validation, logging, and extraction of connection string properties.

**Describe the solution you'd like**
Export the `connectParams` struct and the `parseConnectParams` function in [/conn_str.go](https://github.com/denisenkom/go-mssqldb/blob/master/conn_str.go). I am willing to make this code change myself. I would just like to start a conversation here before making a pull request.

**Describe alternatives you've considered**
The alternative is for consuming applications to duplicate the logic. This obviously works fine, but would result in copy-pasted code everywhere.

**Additional context**
It seems fairly standard to expose this kind of logic. For example, .NET exposes this logic via [SqlConnectionStringBuilder](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder?view=dotnet-plat-ext-5.0).

**Comment by criscola** [comment]
Other drivers implement some kind of strategy, e.g. https://godoc.org/github.com/go-sql-driver/mysql#Config.FormatDSN

**Comment by denisenkom** [comment]
Yeah, I think that would be ok, you can go ahead and submit a CR.

**Comment by vitaly-t** [comment]
> The alternative is for consuming applications to duplicate the logic

Use of generic [connection-string](https://github.com/vitaly-t/connection-string) avoids that ;)
