### ISSUE TITLE
Hash sign in password breaks DSN parsing

### ISSUE THREAD

**Issue by dustinmoris** [denisenkom/go-mssqldb#631]
The `splitConnectionStringURL(dsn string) (map[string]string, error)` function returns the wrong values if for example the user password contains a `#` sign.

The problem lies in line `290` of `conn_str.go` where `url.Parse(dsn)` is being called. Because the `#` sign is a reserved character in a URL it will stop interpreting everything after `#`.

The recommended DSN according to this library is as following:

```
sqlserver://username:password@host/instance?param1=value&param2=value
```

So a DSN like this will cause the parser to return the wrong data:

```
sqlserver://user1:s3cUrePa##word@localhost/MSSQL1
```

This library might have to parse the DSN itself, or even better (but I know this is a big ask, however not sure why it wasn't done that way from day 1) support proper MSSQL connection strings.

Happy to provide a PR if you agree with this approach/fix.

**Comment by denysvitali** [comment]
I guess you should URL encode your password (e.g with Node.JS's `encodeURIComponent("string")`). In your case, the password would be: `s3cUrePa%23%23word`

**Comment by dustinmoris** [comment]
Yeah sorry I realised it later that I have to URL encode everything.
