### ISSUE TITLE
@ sign in password breaks DB Connection

### ISSUE THREAD

**Issue by mehmetkara5007** [denisenkom/go-mssqldb#633]
> dsn := "sqlserver://gorm:LoremIpsum86@localhost:9930?database=gorm"
> db, err := gorm.Open(sqlserver.Open(dsn), &gorm.Config{})

This is example of DB connection for MSSQL.
if the password includes sign "@", then connection breaks and look for hostname after that sign.

For example;
dsn := "sqlserver://gorm:LoremIp@**sum86@localhost**:9930?database=gorm"
The bold part is taken as host name..

This should be fixed.

**Comment by 370750149** [comment]
used functiong QueryEscape wrap the password if with char @,#,$,%,&

**Comment by kardianos** [comment]
Yep. escape the url characters.

**Comment by mehmetkara5007** [comment]
Thank you. It works. But I have another issue not.
Hostname includes **'\\'** (_2 back slash_). I am getting this error now: 

> invalid URL escape \"%5C\

**Comment by mehmetkara5007** [comment]
> used functiong QueryEscape wrap the password if with char @,#,$,%,&
> like
> dsn := fmt.Sprintf("sqlserver://%s:%s@localhost:9930?database=gorm","gorm",url.QueryEscape("LoremIp@sum86"))

What about I have ======>  \\ , because QueryEscape does not work for this
