### ISSUE TITLE
Cannot go install?

### ISSUE THREAD

**Issue by sheeeng** [denisenkom/go-mssqldb#649]
I'm following the [instructions](https://docs.microsoft.com/en-us/azure/azure-sql/database/connect-query-go#create-golang-project-and-dependencies) from Microsoft's documentation.

```console
$ go version                                           
go version go1.16.3 darwin/amd64
$
$ go install -v github.com/denisenkom/go-mssqldb@latest

go install: package github.com/denisenkom/go-mssqldb is not a main package
```

Did I miss anything?

**Comment by robinknaapen** [comment]
@sheeeng 

This is not a application. It's a mssql driver for Go. To use this you should use `go get` in your project

Also mind that Go 1.16 is currently broken. See https://github.com/denisenkom/go-mssqldb/issues/639 and https://github.com/denisenkom/go-mssqldb/pull/642 for more information

**Comment by sheeeng** [comment]
Thanks for the clarification, @robinknaapen.

I understood that this is not an application. It's a mssql driver for Go programming language.
