### ISSUE TITLE
Expose error, severity, and state

### ISSUE THREAD

**Issue by coquagli** [denisenkom/go-mssqldb#653]
**Is your feature request related to a problem? Please describe.**
SQL Server and the Azure SQL products have an [error reporting](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/understanding-database-engine-errors?view=sql-server-ver15) pattern that uses [error number](https://docs.microsoft.com/en-us/sql/t-sql/functions/error-number-transact-sql?view=sql-server-ver15), [state](https://docs.microsoft.com/en-us/sql/t-sql/functions/error-state-transact-sql?view=sql-server-ver15), and [severity](https://docs.microsoft.com/en-us/sql/t-sql/functions/error-severity-transact-sql?view=sql-server-ver15) to uniquely define a particular error scenario. Currently, this SQL Server driver only exposes the error message, not the error number, state, nor severity.

Example error message as shown by SQL Server Management Studio:
```
Msg 297, Level 16, State 1, Line 1
The user does not have permission to perform this action.
```

Definitions of the terms (from [Understanding Database Engine Errors](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/understanding-database-engine-errors?view=sql-server-ver15)):
- **Error number**: Each error message has a unique error number
- **Severity**: The severity indicates how serious the error is. Errors that have a low severity, such as 1 or 2, are information messages or low-level warnings. Errors that have a high severity indicate problems that should be addressed as soon as possible. For more information about severities, see [Database Engine Error Severities](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-error-severities?view=sql-server-ver15).
- **State**: Some error messages can be raised at multiple points in the code for the Database Engine. For example, an 1105 error can be raised for several different conditions. Each specific condition that raises an error assigns a unique state code. 
    - When you are viewing databases that contain information about known issues, such as the Microsoft Knowledge Base, you can use the state number to determine whether the recorded issue is the same as the error you have encountered. For example, if a Knowledge Base Article describes an 1105 error that has a state of 2 and the 1105 error message you received had a state of 3, the error probably has a different cause than the one reported in the article.

**Describe the solution you'd like**
I would like for the driver to expose the error number, state, and severity of any encountered errors. This info is likely already returned as part of the payload from the database. It's just a matter of surfacing the information. 

The error number, state, and severity could be exposed in a format that matches that of SQL Server Management Studio or other common tools - see the example above.

**Describe alternatives you've considered**
The main alternative to exposing this information is to instead rely only on the error message text. 

**Additional context**
 [Understanding Database Engine Errors](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/understanding-database-engine-errors?view=sql-server-ver15)

**Comment by tc-hib** [comment]
I think we could define a struct for everything specific to SQL Server and the caller would pass it as an output parameter.

This could include something, maybe an optional channel or function, to receive messages too. I need that too.

See `SQLGetDiagRec` and `SQLGetDiagField` in ODBC.
See `ISQLServerErrorInfo` in OLEDB.

**Comment by tc-hib** [comment]
Hello @coquagli 
What you're asking for already exists.
Look at this [example](https://github.com/denisenkom/go-mssqldb/blob/d9abbec934ba5bf95d48b9510668cd7226ce8c5d/queries_test.go#L978).

There's also this [issue](https://github.com/denisenkom/go-mssqldb/issues/39) about multiple errors.
But I think we should make it possible to receive errors and messages as soon as possible too. (for example to track progress of a backup, with `BACKUP DATABASE .... WITH STATS`)

**Comment by coquagli** [comment]
Thanks @tc-hib. I'll mark this as closed in that case.

**Comment by coquagli** [comment]
Looking at this a bit deeper: Certain errors (specifically login errors) don't get returned as `mssql.Error`. Instead they are returned as plain old `error`. Looks like it's due to a snippet in [tds.go](https://github.com/denisenkom/go-mssqldb/blob/master/tds.go#L1208) that removes the typing of the error message in order to preface the error with `"login error: "`.
