### ISSUE TITLE
Output parameters and Return Status might be accidentally reused

### ISSUE THREAD

**Issue by tc-hib** [denisenkom/go-mssqldb#654]
**Describe the bug**
When we pass output parameters to a query, or a `*ReturnStatus`, they are stored in the connection.
This means they can be accidentally shared between several queries.
There is a function named `clearOuts` that's supposed to fix that, but:

- It does not clear the `*ReturnStatus`.
- It might not be called, if an errors occurs in `sendQuery`, for example.

**To Reproduce**

```go
func main() {
	db, err := sql.Open("sqlserver", "sqlserver://sa:sa@localhost/sqlexpress?database=master")
	if err != nil {
		log.Fatalln(err)
	}
	defer db.Close()

	var rs mssql.ReturnStatus
	r, _ := db.QueryContext(context.TODO(), "exec sp_recompile 'bad'", &rs)
	if r != nil {
		r.Close()
	}
	rs = 0
	r, _ = db.QueryContext(context.TODO(), "exec sp_recompile 'bad'") // don't pass &rs
	if r != nil {
		r.Close()
	}
	if rs != 0 {
		log.Fatalln("rs has been overwritten by the second query, the connection was the same")
	}
	log.Println("rs == 0, the second query ran on another connection, or the bug is fixed")
}
```

**Expected behavior**

The second query shouldn't have written to `rs`.

### Question

Why do we have `outs` in `Conn` and `returnStatus` in `tdbSession` ?
I have the feeling they both belong to `Stmt`, but I might miss something....
If this is how it should be, I can provide a simple PR to fix that.

**Comment by shogo82148** [comment]
for tracking this issue, I'm writing a reply to https://github.com/denisenkom/go-mssqldb/pull/656#issuecomment-833542872

> Do you have an idea of how we could safely handle "query scope" as opposed to connection/statement scope ?

For Go 1.10 or later, [driver.SesstionResetter](https://golang.org/pkg/database/sql/driver/#SessionResetter) is easiest way.

Or, call `Conn.clearOuts` on and the head of `QueryContext` and `ExecContext`.
Does someone know why `Conn.clearOuts` is not called on the head, but after `startReading`?

**Comment by tc-hib** [comment]
Thanks, SessionResetter is interesting.
But, I eventually think we should call clearOuts in entry points, as you said.
Could this be done like [this](https://github.com/denisenkom/go-mssqldb/compare/master...tc-hib:pr-fix-654-take2?expand=1)?
