### ISSUE TITLE
Dynamic port support

### ISSUE THREAD

**Issue by kilaka** [denisenkom/go-mssqldb#660]
Hi,

Does the driver support dynamic ports?

More info on mssql dynamic ports can be found [here](https://www.sqlshack.com/overview-of-sql-server-ports/).

From what I understand, dynamic ports are support by the [mssql jdbc driver](https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver15).

Thanks,
Alik.

[question]

**Comment by tc-hib** [comment]
Hello,
Yes, it supports using instance names instead of fixed ports.
[Connection strings](https://github.com/denisenkom/go-mssqldb#the-connection-string-can-be-specified-in-one-of-three-formats)

**Comment by kilaka** [comment]
@tc-hib Is this the right format? `sqlserver://host/instance?param1=value&param2=value`?
We provide the username/password separately.

Since what version is it supported?
We have a test case that jdbc (java) works but go-mssqldb doesn't :(

Any idea what can cause it to not work?

**Comment by tc-hib** [comment]
@kilaka Have you deleted your answer ?
If it works for you, could you please close this issue ?
Thanks.

**Comment by kilaka** [comment]
> @kilaka Have you deleted your answer ?
> If it works for you, could you please close this issue ?
> Thanks.
