### ISSUE TITLE
Calling SQLServer stored functions (not procs)

### ISSUE THREAD

**Issue by hhhapz** [denisenkom/go-mssqldb#672]
Hey! I was wondering if it is possible to call functions and get the return value using this driver?

According to https://docs.microsoft.com/en-us/sql/relational-databases/user-defined-functions/execute-user-defined-functions?view=sql-server-ver15, you must assign the result of the function to a variable. I have tried  many different things, however nothing has worked out for me so far:
```go
	const sqlstr = `@p1 = EXEC test_schema.my_func_with_0_params `
	var res int
	if _, err := db.ExecContext(ctx, sqlstr, sql.Out{Dest: &res}); err != nil {
		return 0, logerror(err)
	}
	return res, nil
}
```

**Comment by tc-hib** [comment]
Hello, I was about to make a PR about this. There's a bug in this driver, the `output` keyword is missing in RPC calls.
Could be fixed soon, as it is rather simple. If nobody does before I can get back to my computer I'll post the PR.

**Comment by hhhapz** [comment]
Hey @tc-hib, thanks for your response. However, I am using stored functions, not procs! And the return type of the function is incidentally an integer, not trying to get the return status (I can't find anything about what the purpose of this is, even in the readme it is quite vague about what the actual purpose is). If I try to use syntax similar to stored procedures to call the function, I just get an error `no rows in result set`. 

Here is the function I am attempting to call:
![image](https://user-images.githubusercontent.com/29532600/125198254-50459100-e28b-11eb-8c46-3a16a9a75286.png)

**Comment by tc-hib** [comment]
Alright so you actually need that bug fix I was talking about. I'll try to send a PR soon.

**Comment by tc-hib** [comment]
You'll need #673 for this to work.

Here is the syntax, from your first post:
```go
const sqlstr = `SELECT @p1 = test_schema.my_func_with_0_params()`
var res int
if _, err := db.ExecContext(ctx, sqlstr, sql.Named("p1", sql.Out{Dest: &res})); err != nil {
	return 0, logerror(err)
}
return res, nil
```

**Comment by hhhapz** [comment]
Thanks for making the PR :)

**Comment by dzsquared** [comment]
As a workaround in the meantime - while the TSQL syntax example shows a scalar function being placed into a variable, user-defined functions can be included in SELECT statements to return values in more traditional result sets.  In your example, the function can be called as a column within a select statement:
```sql
select test_schema.a_func_0_in() as udfColumn
```

Effectively giving a result set of 1 row, 1 column, with the value 10.

**Comment by hhhapz** [comment]
Cheers!!
