### ISSUE TITLE
encrypt tag issue

### ISSUE THREAD

**Issue by robarc** [denisenkom/go-mssqldb#68]
If I add encrypt=false or encrypt=true to my connection string, I receive the below error.  I'm assuming this is because I don't have a certificate setup so I figure that's OK.  But I also get an error when I set encrypt=disabled: 

encrypt=true or false error
----------------------------------------
prepared2015/01/21 15:46:01 http: panic serving 127.0.0.1:22083: TLS Handshake failed: x509: certificate signed by unknown authority
goroutine 6 [running]:
net/http.func·011()
	c:/go/src/net/http/server.go:1130 +0xc2
main.serveRest(0x353ab8, 0xc0822aa000, 0xc08229c000)
	C:/Users/rarchiba/Desktop/restServer/restServer.go:17 +0x79
net/http.HandlerFunc.ServeHTTP(0x787ab8, 0x353ab8, 0xc0822aa000, 0xc08229c000)
	c:/go/src/net/http/server.go:1265 +0x48
net/http.(*ServeMux).ServeHTTP(0xc0820563c0, 0x353ab8, 0xc0822aa000, 0xc08229c000)
	c:/go/src/net/http/server.go:1541 +0x184
net/http.serverHandler.ServeHTTP(0xc08200a360, 0x353ab8, 0xc0822aa000, 0xc08229c000)
	c:/go/src/net/http/server.go:1703 +0x1a1
net/http.(*conn).serve(0xc08202c320)
	c:/go/src/net/http/server.go:1204 +0xb5e
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:1751 +0x365

encrypt=disabled error
------------------------------------------
prepared2015/01/21 15:49:11 http: panic serving 127.0.0.1:22315: Invalid encrypt 'disabled': strconv.ParseBool: parsing "disabled": invalid syntax
goroutine 6 [running]:
net/http.func·011()
	c:/go/src/net/http/server.go:1130 +0xc2
main.serveRest(0x223910, 0xc0822ac000, 0xc08229e000)
	C:/Users/rarchiba/Desktop/restServer/restServer.go:17 +0x79
net/http.HandlerFunc.ServeHTTP(0x787ab8, 0x223910, 0xc0822ac000, 0xc08229e000)
	c:/go/src/net/http/server.go:1265 +0x48
net/http.(*ServeMux).ServeHTTP(0xc0820563c0, 0x223910, 0xc0822ac000, 0xc08229e000)
	c:/go/src/net/http/server.go:1541 +0x184
net/http.serverHandler.ServeHTTP(0xc08200a360, 0x223910, 0xc0822ac000, 0xc08229e000)
	c:/go/src/net/http/server.go:1703 +0x1a1
net/http.(*conn).serve(0xc08202c280)
	c:/go/src/net/http/server.go:1204 +0xb5e
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:1751 +0x365

**Comment by dimdin** [comment]
The parameter syntax is encrypt=disable and not "disabled".

**Comment by dimdin** [comment]
You can use encrpt=true;TrustServerCertificate=true for testing.

**Comment by robarc** [comment]
Thanks for the note on encrypt=disable.  Yes, I had typed it wrong.  Thanks.
