### ISSUE TITLE
an operation on a socket could not be performed because the system lacked sufficient buffer space or because queue was full

### ISSUE THREAD

**Issue by haochun** [denisenkom/go-mssqldb#69]
when i use this sql server driver to operate db,i occured a problem.i opend only on connction,because the golang doc said:

he returned DB is safe for concurrent use by multiple goroutines and maintains its own pool of idle connections. Thus, the Open function should be called just once. It is rarely necessary to close a DB.

.but,when my program run some hours,it throw an exception,like this:

![qq 20150123223343](https://cloud.githubusercontent.com/assets/9320176/5876168/d5bc92ac-a34f-11e4-80ef-69b8d1284b17.png)

**Comment by denisenkom** [comment]
Thanks @haochun for your report, would you be able to test a fix on the branch bugfix-69?

**Comment by haochun** [comment]
@denisenkom i have solve this problem.i just add  conn.SetMaxIdleConns(200) .but i do not know why.when i set 

conn.SetMaxOpenConns(200)
conn.SetMaxIdleConns(200)

the problem does not happed,if i only set :conn.SetMaxOpenConns(200)  it also be happed.

**Comment by denisenkom** [comment]
I see, I think closing connection should fix this problem.
Fix is merged into master branch, try again with latest code.

**Comment by haochun** [comment]
@denisenkom ok,thanks!i will try it . it means that i only need to set :conn.SetMaxOpenConns(200)?

**Comment by denisenkom** [comment]
bq. it means that i only need to set :conn.SetMaxOpenConns(200)?
no, you don't have to set it, it should work without changes from your side

**Comment by haochun** [comment]
@denisenkom That means I can not set any of
conn.SetMaxOpenConns(200)
conn.SetMaxIdleConns(200)
, i only need get a connection,it will adjust connection pool by go driver?

**Comment by denisenkom** [comment]
@haochun I am not sure what you mean.
I think the problem was caused by not closed UDP connections.  This should be fixed now with my latest update which closes connections.  This should mean that you don't have to change "MaxOpenConns" etc.

**Comment by haochun** [comment]
@denisenkom ok ,i know.thanks.
