### ISSUE TITLE
setupTLSCommonName redeclared

### ISSUE THREAD

**Issue by wonsikin** [denisenkom/go-mssqldb#706]
**Describe the bug**
Our Services are using this library and we have a static analysis in the CI. today we found the CI build failed.

```
# github.com/denisenkom/go-mssqldb/msdsn
/go/src/github.com/denisenkom/go-mssqldb/msdsn/conn_str_go115pre.go:7:6: setupTLSCommonName redeclared in this block
	previous declaration at /go/src/github.com/denisenkom/go-mssqldb/msdsn/conn_str_go115.go:11:57
```

It looks like this commit add an extra `setupTLSCommonName`

https://github.com/denisenkom/go-mssqldb/commit/d99d7d591a628b46e7b39274f817386c4c7424f3

cc: @kardianos

**Comment by kardianos** [comment]
I feel like an idiot. I corrected by adding in the older style build flags. It should be fixed now.
