### ISSUE TITLE
can not open connection when use udp to get the instances in internet

### ISSUE THREAD

**Issue by haochun** [denisenkom/go-mssqldb#71]
when i connection to localhost,it work.but,when i connect to the sql server on internet.it dose not work.it is wait on getIntances().i think the cause is that use UDP to get instances.
how can i solve it??

**Comment by dimdin** [comment]
UDP packets are used to translate sql server instance name to port number.
UDP packets are not reliable and can be dropped by your network infrastructure.
If you don't specify an instance name and you specify a port number it will work reliable.
see: https://technet.microsoft.com/en-us/library/ms177440(v=sql.105).aspx

**Comment by haochun** [comment]
yes,if i does not set the instance name,it will work normal.but,if the sql server has more than one instance,how can i do?

**Comment by dimdin** [comment]
Each instance uses a different port number. see: https://technet.microsoft.com/en-us/library/ms177440(v=sql.105).aspx

**Comment by haochun** [comment]
thanks very much!
