### ISSUE TITLE
BUG: CGO is being used for tests therefore the driver is not pure go

### ISSUE THREAD

**Issue by owenwaller** [denisenkom/go-mssqldb#711]
**Describe the bug**

The tests for `go-mssqldb` appear to depend on CGO when building on linux. This would be contrary to a "pure go" driver.

On a Linux build server __without__ gcc installed I am seeing this when building the tests in the `msdns` package

```
$ go test
# runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
FAIL	github.com/denisenkom/go-mssqldb/msdsn [build failed]
```

So there is a CGO dependency.

Where as if I explicity disable CGO the tests pass:
```
CGO_ENABLED=0 go test
PASS
ok  	github.com/denisenkom/go-mssqldb/msdsn	0.004s
```
This failure is 100% reproducible, and is on the current tip (commit #73c014ad7bf723bb066c5acde24fccab51084c81 at the time of writing) and the v0.11.0 version.

With gcc installed, the problem is not apparent.

Also on a Windows machine i.e. GOOS=windows the problem is also not apparent (even when CGO_ENABLED=1, as is the platform default). The problem is therefore specific to GOOS=linux and CGO_ENABLED=1 (and gcc not installed - which in this case is correct).

I've used the following bit of `go list` to try to narrow the problem down:
```
go list -f "{{if .CgoFiles}}{{.ImportPath }} from {{ .Dir }}{{end}}" $(go list -f "{{.ImportPath}}{{range .Deps}} {{.}}{{end}}")
```
but that only points into the standard library source code
```
go list -f "{{if .CgoFiles}}{{.ImportPath }} from {{ .Dir }}{{end}}" $(go list -f "{{.ImportPath}}{{range .Deps}} {{.}}{{end}}")
net from /home/XXX/go/src/net
runtime/cgo from /home/XXX/go/src/runtime/cgo
```

**Why is this a problem**
This is currently tripping up our (Jenkins based) build server. This sever, quite rightly, does not have gcc installed and so any CGO enabled code, including test code, will fail (as above). This is what we want as we do not want any CGO dependences in the project.

The only work around that I can see is to prefix our current `go test ./...` command with `CGO_ENABLED=0`. But that turns out to be impractical, as _every_ go command, or go testing or go analysis tool we use after out "Test" stage also needs to be prefixed with `CGO_ENABLED=0`

As an example several stages after we call `go test` in our pipeline, we are running `golangci-lint` as a linter. We are now having to prefix `golangci-lint` with `CGO_ENABLED=0` or `golangci-lint` runs into the above failure as well.

As the Jenkins pipelinne is extensive, this is both error prone and impractical to maintain over the short-medium term. The problem needs to be fixed in the upstream dependency.

I could set `CGO_ENABLED=0` globally on the build server but this isn't really want I want to be doing. The test code should just work.

**To Reproduce**
To reproduce this on any linux machine without gcc installed it is as simple as:
```
git clone https://github.com/denisenkom/go-mssqldb
cd go-mssqldb/msdsn
go test
```
which will produce:
```
# runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
FAIL	github.com/denisenkom/go-mssqldb [build failed]
```
**Expected behavior**

The expected behaviour is that the test passes, even if CGO_ENABLED=1 (the platform default on linux) and gcc is not installed. 
There should be no dependency on CGO at all.

**Further technical details**
`go env` shows
```
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/XXX/go/bin"
GOCACHE="/home/XXX/.cache/go-build"
GOENV="/home/XXX/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/XXX/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/XXX/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/XXX/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/XXX/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/XXX/go-mssqldb/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build780199589=/tmp/go-build -gno-record-gcc-switches"

```
running on a Unbuntu 18.04 LTS VM
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

**Additional context**

The same behaviour is apparent with Go versions v1.17.1, v1.17.2, v1.17.3, v1.17.4 and the current v1.17.5.

**Comment by kardianos** [comment]
... By default Go uses CGO for certain operations (name resolution) on Linux unless specifically asked to remove cgo. This is to ensure it follows OS name resolution and other network functions. If you casually inspect ./msdsn package, it doesn't contain any CGO.

**Comment by owenwaller** [comment]
@kardianos 

Ah ha. Sorry I was unaware of this behaviour on linux. Many thanks for correcting me.

So as the go standard library is therefore linking to glibc, via cgo, and therefore glibc is runtime dependency of any go program on linux (unless cgo is explicitly disabled), it makes no sense to not to install gcc on the build server in question.

Once gcc and the associated headers were installed, the test worked as expected.

Many thanks for the help in resolving this.
