### ISSUE TITLE
Query with condition using LIKE operator problem

### ISSUE THREAD

**Issue by nxquang1994** [denisenkom/go-mssqldb#715]
Hi everyone,

I currently meet an problem when query with LIKE operator, look in my code below:

`	query := "SELECT * FROM [stores].[orders] WHERE order_name LIKE '%@order_name%'"
	stmt, err := db.Prepare(query)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	orderName := "DOX"
	rows, err := stmt.QueryContext(
		ctx, 
		sql.Named("order_name", orderName),
	)
	for rows.Next() {
		// Append to a list of order here
		// .......
	}`

The for loop never come in because the rows are always empty. I track in many documents but there's not exists any mention about this problem. Please help me to solve this, thank you.

Regards.

**Comment by kardianos** [comment]
You need to append the value of the variable to the wildcards:
`like N'%' + @order_name + N'%'`

**Comment by nxquang1994** [comment]
> 

Hi @kardianos , you mean my query string look like:

`SELECT * FROM [stores].[orders] WHERE order_name LIKE 'N%'@order_name'N%'`

I tried but it still not works.

**Comment by kardianos** [comment]
No.
You need to concat (join) the '%' strings to the VALUE of the paramter. You can join using the + operator.

**Comment by nxquang1994** [comment]
Hi @kardianos , I tried all solutions which may match with your suggestion, but all of them are not work. I concated the '%' to order parameter value but is still not work.

`
orderName := "DTX"
orderName = "%" + orderName + "%"
rows, err := stmt.QueryContext(
   ctx,
   sql.Named("order_name", orderName),
)
`
What is my missing, the raw sql run on sql editor work fine.

**Comment by kardianos** [comment]
I can't help you further writing SQL. Please devote appropriate time to study Microsoft's T-SQL Documentation, all of which is free and available online.
