### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by gzw13999** [denisenkom/go-mssqldb#72]
panic: Login error: WSARecv tcp 192.168.1.105:38186: An existing connection was forcibly closed by the remote host.

**Comment by gzw13999** [comment]
Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64)   Apr  2 2010 15:48:46   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) (Hypervisor)

**Comment by dimdin** [comment]
You can solve the issue by installing SQL Server 2008 R2 Service Pack 2.
You can bypass the issue by specifying encrypt=disable in your connection string.
For more information see https://github.com/denisenkom/go-mssqldb#known-issues
