### ISSUE TITLE
 Login error

### ISSUE THREAD

**Issue by gzw13999** [denisenkom/go-mssqldb#73]
panic: Login error: Invalid TDS stream: unknown env type: 13

goroutine 16 [running]:
runtime.panic(0x71d3c0, 0xc0820014a0)
        c:/go/src/pkg/runtime/panic.c:279 +0x11f
sqlservertest/models.init路1()

**Comment by denisenkom** [comment]
@gzw13999 can you test this change: https://github.com/denisenkom/go-mssqldb/commit/7e2729fe645bb216b0a23f80af5b6fd5b5bc35bf
?
