### ISSUE TITLE
How about detatch your repository from my fork?

### ISSUE THREAD

**Issue by mattn** [denisenkom/go-mssqldb#74]
Hi.

I have a thing worried about in long time. go-mssqldb is awesome. However go-mssqldb is fork repository of my go-ole. So, I'm thinking you probably have better to detatch from my repo. Since go-mssqldb is a fork repository, inconspicuous, I guess.
I'm asking github support about this. And they seems to want your agreement. How do you think?

Thanks in your advance.

**Comment by mattn** [comment]
If you want to detach, please contact to github support: https://github.com/contact

They know my proposal. :)

**Comment by denisenkom** [comment]
Right, this makes sense, will contact github.

**Comment by denisenkom** [comment]
Detached

**Comment by mattn** [comment]
Congrats! :)
