### ISSUE TITLE
Need clear examples for "UPDATE" sql statement

### ISSUE THREAD

**Issue by arjunnath** [denisenkom/go-mssqldb#75]
The examples are not very clear regarding how to do an SQL "UPDATE".
Specifically, can it be done by a Prepare() followed by an Exec() or does sql get executed in the Prepare() statement itself ?
Also, can one use Query() to do an UPDATE ?

Thanks
-A

**Comment by denisenkom** [comment]
You can find one example here: http://golang.org/pkg/database/sql/#Tx.Stmt

**Comment by cuishuang** [comment]
updateSql := `update sj_tx set  status = ? ,sj_tx_beizhu = ? where sj_tx_id = ?  `
msDB.QueryRow(updateSql,status,remarks,id)
