### ISSUE TITLE
unable to open tcp connection with host

### ISSUE THREAD

**Issue by hajsf** [denisenkom/go-mssqldb#762]
I goth the below error:

```bash
2022/07/18 10:15:38 Prepare failed:unable to open tcp connection with host 'my-server:1433': dial tcp 172.16.20.185:1433: connectex: No connection could be made because the target machine actively refused it.
```
Though that I did the following:
1. Installed fresh version of MSSQL dev, first time MSSQL is installed at this machine, and confirmed it is running using `sqlcm`

<img width="368" alt="image" src="https://user-images.githubusercontent.com/98168280/179464794-91883009-c837-4a43-9bc7-aec78027bbbc.png">

2. Installed MSSQL studio (I'm to confirm MSSQLSERVER) is connected

<img width="490" alt="image" src="https://user-images.githubusercontent.com/98168280/179462391-39cd7e20-bf4c-48e6-a97e-1206ce97350a.png">

3. At Windows definder firewall, I allowed the connection of port `1433`

<img width="982" alt="image" src="https://user-images.githubusercontent.com/98168280/179461599-54b58c34-9c9a-4d60-ab9b-3f111e2170d9.png">

4. At `SQL server network connection -> protocols for MSSQLSERVER` I enabled both `Named Pipes` and `TCP/IP`

<img width="446" alt="image" src="https://user-images.githubusercontent.com/98168280/179461806-db1762ee-fe82-4bfc-9059-cc4f1a647051.png">

The code I'm trying to test is the simple one provided in the examples:
```go
package main

import (
	"database/sql"
	"flag"
	"fmt"
	"log"

	_ "github.com/denisenkom/go-mssqldb"
)

var (
	debug         = flag.Bool("debug", false, "enable debugging")
	password      = flag.String("password", "", "the database password")
	port     *int = flag.Int("port", 1433, "the database port")
	server        = flag.String("server", "my-server", "the database server") 
	user          = flag.String("user", "sa", "the database user")                  
)

func main() {
	flag.Parse()

	if *debug {
		fmt.Printf(" password:%s\n", *password)
		fmt.Printf(" port:%d\n", *port)
		fmt.Printf(" server:%s\n", *server)
		fmt.Printf(" user:%s\n", *user)
	}

	connString := fmt.Sprintf("server=%s;user id=%s;password=%s;port=%d", *server, *user, *password, *port)
	if *debug {
		fmt.Printf(" connString:%s\n", connString)
	}
	conn, err := sql.Open("mssql", connString)
	if err != nil {
		log.Fatal("Open connection failed:", err.Error())
	}
	defer conn.Close()

	stmt, err := conn.Prepare("select 1, 'abc'")
	if err != nil {
		log.Fatal("Prepare failed:", err.Error())
	}
	defer stmt.Close()

	row := stmt.QueryRow()
	var somenumber int64
	var somechars string
	err = row.Scan(&somenumber, &somechars)
	if err != nil {
		log.Fatal("Scan failed:", err.Error())
	}
	fmt.Printf("somenumber:%d\n", somenumber)
	fmt.Printf("somechars:%s\n", somechars)

	fmt.Printf("bye\n")
}
```

**Comment by dainiauskas** [comment]
Replace my-server to IP address, bug in IP address resolve from name

**Comment by kardianos** [comment]
This isn't an issue with the package.
