### ISSUE TITLE
SSPI client

### ISSUE THREAD

**Issue by GuyBrand** [denisenkom/go-mssqldb#77]
Hi .

Sorry for using the issues area , but you don't state your email , hope that's cool with you .

I see you have implanted SSPI and NTLM clients on the project .
I'm looking for something familiar for an http request .
So If you have some guideline , sample project or willing to do a small project for me , I'd be thankful .

Guy .

**Comment by denisenkom** [comment]
Hi Guy,

Fine with me.

BTW, take a look at this project: https://godoc.org/github.com/ThomsonReutersEikon/go-ntlm/ntlm

**Comment by GuyBrand** [comment]
Yes, I've seen thus already, it looks like a full ntlm implantation, but no
http request binding.

Anyhow, I've managed to change the clients proxy, so for now I get by, but
I believe it will pop up some day.
