### ISSUE TITLE
No instance matching XYZ returned from the host

### ISSUE THREAD

**Issue by adcorduneanu** [denisenkom/go-mssqldb#772]
I'm trying to integrate my k6 project with MSSQL, and seems there is a problem with the current setup of this implementation that's used in xk6-sql setup.

My MSSQL instance is a named instance on the current server and seems this is not accessible from the Go implementation, even that one works from anywhere else - visual studio, ssms, real apps, you name it...

I tried tampering with the connection string in all 3 formats, but nothing changed.

A screenshot proving the issue.
![image](https://user-images.githubusercontent.com/5188847/198845854-fea49d99-8d87-45f3-9b1b-3f486ae7a2c2.png)
![image](https://user-images.githubusercontent.com/5188847/198845184-6f6aa154-7e63-4d60-a0d2-298eba1bb33d.png)
![image](https://user-images.githubusercontent.com/5188847/198845640-c5be7baf-3eff-46da-8095-a4626ef314e5.png)

Win OS used - v10 21H2
Go version - version go1.19.2 windows/amd64
This software version, used in xk6 - v0.12.0

Choco command to setup a similar SQL setup
```powershell
choco install "sql-server-2019" -y --params='"/INSTANCENAME:SQL2012  /SkipRules:RebootRequiredCheck /IACCEPTSQLSERVERLICENSETERMS /Q /INDICATEPROGRESS /FEATURES:SQLEngine,FULLTEXT,AS,IS,BC,Conn  /SQLCOLLATION:Latin1_General_100_CI_AS /ASSERVERMODE:MULTIDIMENSIONAL /ASSYSADMINACCOUNTS:Users /ASCOLLATION:Latin1_General_100_CI_AS /FILESTREAMLEVEL:2 /FILESTREAMSHARENAME:SQL2012_Filestream /SQLMAXMEMORY:6144"'
```

Actual behavior
Using a named instance does not work

Expected behavior
Using named instances should work

Additional stuff
For xk6-sql just followed the steps described [here](https://github.com/grafana/xk6-sql#build) and as a code example, I followed this [example](https://github.com/grafana/xk6-sql/blob/master/tests/mssql_test.js).

**Comment by NikitaDef** [comment]
> I'm trying to integrate my k6 project with MSSQL, and seems there is a problem with the current setup of this implementation that's used in xk6-sql setup.
> 
> My MSSQL instance is a named instance on the current server and seems this is not accessible from the Go implementation, even that one works from anywhere else - visual studio, ssms, real apps, you name it...
> 
> I tried tampering with the connection string in all 3 formats, but nothing changed.
> 
> A screenshot proving the issue. ![image](https://user-images.githubusercontent.com/5188847/198845854-fea49d99-8d87-45f3-9b1b-3f486ae7a2c2.png) ![image](https://user-images.githubusercontent.com/5188847/198845184-6f6aa154-7e63-4d60-a0d2-298eba1bb33d.png) ![image](https://user-images.githubusercontent.com/5188847/198845640-c5be7baf-3eff-46da-8095-a4626ef314e5.png)
> 
> Win OS used - v10 21H2 Go version - version go1.19.2 windows/amd64 This software version, used in xk6 - v0.12.0
> 
> Choco command to setup a similar SQL setup
> 
> ```powershell
> choco install "sql-server-2019" -y --params='"/INSTANCENAME:SQL2012  /SkipRules:RebootRequiredCheck /IACCEPTSQLSERVERLICENSETERMS /Q /INDICATEPROGRESS /FEATURES:SQLEngine,FULLTEXT,AS,IS,BC,Conn  /SQLCOLLATION:Latin1_General_100_CI_AS /ASSERVERMODE:MULTIDIMENSIONAL /ASSYSADMINACCOUNTS:Users /ASCOLLATION:Latin1_General_100_CI_AS /FILESTREAMLEVEL:2 /FILESTREAMSHARENAME:SQL2012_Filestream /SQLMAXMEMORY:6144"'
> ```
> 
> Actual behavior Using a named instance does not work
> 
> Expected behavior Using named instances should work
> 
> Additional stuff For xk6-sql just followed the steps described [here](https://github.com/grafana/xk6-sql#build) and as a code example, I followed this [example](https://github.com/grafana/xk6-sql/blob/master/tests/mssql_test.js).

Hi, I guess, it depends on that code lines.
https://github.com/denisenkom/go-mssqldb/blob/e53873151a46af22b77fa010fc1485c31cbb38b1/tds.go#L1054

Remove port in connection string.

**Comment by adcorduneanu** [comment]
Hi @NikitaDef,

Thank you for your help.

I will close the issue as this one is fixed - for me, at least.

To provide some insights for those who might encounter the same issue - this was not a server setup, but a development computer, and until now I didn't require my SQL server to be exposed over TCP. 

After the modification of the TCP configuration, and a computer restarts it worked, as this didn't work with only service restart.
![image](https://user-images.githubusercontent.com/5188847/198849114-0ceeaa9b-0173-421c-8ec1-72a31238f70b.png)

What it's weird is the fact that even if it's local, and any other client connects, this one doesn't as it treats it as a **remote**, even isn't.
