### ISSUE TITLE
想获取执行结果的消息列

### ISSUE THREAD

**Issue by Mayter** [denisenkom/go-mssqldb#791]
在项目中，需要打印消息列的结果，没找到具体实现，不知道有没有办法打印这个消息列，结果列可以正常打印
![1](https://github.com/denisenkom/go-mssqldb/assets/6148807/dad30223-bf76-420f-9df0-9c343f5c7f41)

**Comment by denisenkom** [comment]
Take a look at this example: https://pkg.go.dev/github.com/microsoft/go-mssqldb#example-Rows-Usingmessages
