### ISSUE TITLE
Use a custom dialer to create connection with db

### ISSUE THREAD

**Issue by XiaoYiXiaoYang** [denisenkom/go-mssqldb#801]
**Is your feature request related to a problem? Please describe.**
when i use "github.com/lib/pq" as sql driver to connect to postgressql
i can use `func DialOpen(d Dialer, dsn string) (_ driver.Conn, err error)` method to connect to db with my custom dialer

and i suggest "github.com/denisenkom/go-mssqldb" need a same one

**Describe the solution you'd like**
add a method like `func DialOpen(d Dialer, dsn string) (_ driver.Conn, err error)`  before create connection

**Describe alternatives you've considered**

**Additional context**
"github.com/go-sql-driver/mysql" have a similar method to use my own custom dialer， it is `func RegisterDial(network string, dial DialFunc) `

**Comment by niudaii** [comment]
Please see #665 
```
type ProxyDialer struct {
	dialer proxy.Dialer
}

func (d ProxyDialer) DialContext(ctx context.Context, network string, addr string) (net.Conn, error) {
	return d.dialer.Dial(network, addr)
}
```

**Comment by XiaoYiXiaoYang** [comment]
thanks~~, it works for me good.
