### ISSUE TITLE
Unable to query on time, datetime2, or datetimeoffset with precision of 0

### ISSUE THREAD

**Issue by ianmburns** [denisenkom/go-mssqldb#83]
I receive the error message "Invalid scale for TIME/DATETIME2/DATETIMEOFFSET type" when attempting a query that contains a column of type datetime2(0).

I believe this is due to the readVarLen function in types.go not supporting a scale of 0 for these types.

See the precision, scale description in the [datetime2 documentation](https://msdn.microsoft.com/en-us/library/bb677335.aspx )

**Comment by denisenkom** [comment]
fixed

**Comment by ianmburns** [comment]
Thanks! :+1:
