### ISSUE TITLE
Supporting high availability groups

### ISSUE THREAD

**Issue by mjibson** [denisenkom/go-mssqldb#86]
I'd like to discuss how to add HA support. There are various issues.

1. We have a HA cluster here. The hostname we connect to is a DNS address that returns multiple IP addresses. tds.go uses net.Dial, which tries the first and gives up (see golang/go#9801). Solution: modify the connect function to try IP addresses until one works.
2. We need to connect to the primary of the cluster. Possible solutions:
    - Connect to all addresses above and ask each if they are the master.
    - Connect to the first available and ask which is the master, then connect to it if we aren't already.
3. Failover if the master fails. I'm happy to leave this for later.
4. Make sure we don't change anything about how non-HA servers are handled.

I'm happy to work on this if we can agree on a design.

**Comment by denisenkom** [comment]
Take a look at this algorithm: https://msdn.microsoft.com/en-us/library/ms175484.aspx
This is what Microsoft's Sql native provider is doing, I think go driver should behave similarly.

**Comment by mjibson** [comment]
My sysadmins tell me that Database Mirroring is different than HA, which is built on windows failover cluster. We are using this mode: https://msdn.microsoft.com/en-us/library/hh213417.aspx
