### ISSUE TITLE
Sql Server 2000 support

### ISSUE THREAD

**Issue by alepore** [denisenkom/go-mssqldb#91]
Hello,
I just want to ask if this project can't support Sql Server 2000 for some technical reasons or simply no one has tested it yet.

Thanks!

**Comment by dimdin** [comment]
Short answer: there are technical reasons

There are differences in the TDS wire format between SQL server 2000 and 2005. The differences are documented here: https://msdn.microsoft.com/en-us/library/dd339982.aspx

go-mssqldb assumes the server is at least SQL Server 2005. With some changes it will be possible to talk to SQL Server 2000. The main difference is that the DONE token have a LONG row count in SQL 2000 but a ULONGLONG row count in SQL 2005. Pull requests with a fix are welcome.

**Comment by alepore** [comment]
Thanks for the detailed answer!
