### ISSUE TITLE
Syntax error when creating index with `UNIQUE(s)`

### ISSUE THREAD

**Issue by linquize** [denisenkom/go-mssqldb#93]
I have a column with attribute `xorm:"UNIQUE(s) NOT NULL`
e.g.
````
type MyTable struct {
  A string `xorm:"UNIQUE(s) NOT NULL`
  B int
  C string `xorm:"UNIQUE(s)"`
}
````
But it gives me wrong syntax
`CREATE UNIQUE INDEX [UQE_mytable_A] ON [mytable] ([A[,]C])`

Expected:
`CREATE UNIQUE INDEX [UQE_mytable_A] ON [mytable] ([A])`
then
`CREATE UNIQUE INDEX [UQE_mytable_C] ON [mytable] ([C])`

I am using SQL Server 2012.

**Comment by dimdin** [comment]
This looks like a xorm problem

**Comment by linquize** [comment]
But no problem when using mysql, postgresql or sqlite3

**Comment by linquize** [comment]
Fixed by https://github.com/go-xorm/xorm/pull/223
