### ISSUE TITLE
SELECT * FROM table syntax

### ISSUE THREAD

**Issue by geosoft1** [denisenkom/go-mssqldb#97]
The query SELECT \* FROM table don't work for me. In fact return nothing but SELECT field FROM table work. I try on SQL Server 2005 and 2008 R2.

**Comment by denisenkom** [comment]
SELECT * FROM table should work.
You probably have some column or value which fails.  Can you isolate which column/value it is?

**Comment by geosoft1** [comment]
I am not really sure but i guess one of the problem come from SMALLDATETIME type. The documentation says this type is a two bytes int (uint16 in golang?) but if i query a particular smalldatetime field the result is 0 or nothing. I try with int types and even string type.

e.g.: a is a smalldatetime in SQL server

db.Query("select a from table")

var a int,int16,uint... result 0
var a string show nothing

the same problem seems to be with uniqueidentifier type columns.

**Comment by denisenkom** [comment]
We have a test for smalldatetime: https://github.com/denisenkom/go-mssqldb/blob/master/queries_test.go#L60


and for uniqueidentifier: https://github.com/denisenkom/go-mssqldb/blob/master/queries_test.go#L62


and they are passing.




Can you provide minimal reproducible program, including minimal mssql schema?


—

**Comment by geosoft1** [comment]
Windows Server 2008 R2


BULK INSERT articole

FROM 'c:\articole.csv'

WITH

(

FIELDTERMINATOR =','

ROWTERMINATOR = '\n'

)



in the picture atached select various fields works but select * return
nothing.


thank you for help.

On Sun, Apr 26, 2015 at 5:37 PM, denisenkom <notifications@github.com>
wrote:

> We have a test for smalldatetime:
> https://github.com/denisenkom/go-mssqldb/blob/master/queries_test.go#L60
>
>
> and for uniqueidentifier:
> https://github.com/denisenkom/go-mssqldb/blob/master/queries_test.go#L62
>
>
> and they are passing.
>
>
>
>
> Can you provide minimal reproducible program, including minimal mssql
> schema?
>
>
> --
> Sent from Mailbox
>
> On Tue, Apr 7, 2015 at 3:49 AM, geosoft1 <notifications@github.com> wrote:
>
> > I am not really sure but i guess one of the problem come from
> SMALLDATETIME type. The documentation says this type is a two bytes int
> (uint16 in golang?) but if i query a particular smalldatetime field the
> result is 0 or nothing. I try with int types and even string type.
> > e.g.: a is a smalldatetime in SQL server
> > db.Query("select a from table")
> > var a int,int16,uint... result 0
> > var a string show nothing
> > the same problem seems to be with uniqueidentifier type columns.
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/denisenkom/go-mssqldb/issues/97#issuecomment-90431468
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/denisenkom/go-mssqldb/issues/97#issuecomment-96392486>
> .
>



-- 
Cu stima | Best regards,
George

geosoft1.github.io
ubuntu <http://ubuntu.com> | mikrotik <http://mikrotik.com> | golang
<http://golang.org>

**Comment by denisenkom** [comment]
Please upload c:\articole.csv too

**Comment by geosoft1** [comment]
i put it in the preview mail but i send you again.see attach.

On Fri, May 1, 2015 at 5:14 AM, denisenkom <notifications@github.com> wrote:

> Please upload c:\articole.csv too
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/denisenkom/go-mssqldb/issues/97#issuecomment-98024463>
> .
>



-- 
Cu stima | Best regards,
George

geosoft1.github.io
ubuntu <http://ubuntu.com> | mikrotik <http://mikrotik.com> | golang
<http://golang.org>

**Comment by denisenkom** [comment]
I still didn't get it, I think github strips attachments.  Try creating a gist: https://gist.github.com/ and posting link here.

**Comment by geosoft1** [comment]
http://w3.geosoftnet.ro:8081/files/articole.zip

**Comment by kardianos** [comment]
Poster abandoned the project this was for and no longer reproduce.
