### ISSUE TITLE
DATETIME interface: unsupported driver

### ISSUE THREAD

**Issue by arcynum** [denisenkom/go-mssqldb#99]
I am attempting to build a physical table downloading service.

I am having problems when trying to process SQL Server DATETIME fields in this way.

I am experincing the following error when running the following code:
`sql: Scan error on column index 8: unsupported driver -> Scan pair: time.Time -> *[]uint8`

I have looked around and it seems this is an issue other drivers have encountered, but I can't point at a specific solution.

Being able to assign a datetime value through `Scan()` would be extremely useful.

```go
// Create and run the database query.
query, err := dbConnection.Query("SELECT * FROM table")
if err != nil {
	log.Fatal(err)
}
defer query.Close()

// Get the queries columns
cols, err := query.Columns()
if err != nil {
	log.Fatal(err)
}

// Byte data (so NULL fields can be handled later)
byteData := make([][]byte, len(cols))

// Interface for the scan
destination := make([]interface{}, len(cols))

// Assign the destination interface points to the byte data.
for i, _ := range byteData {
	destination[i] = &byteData[i]
}

// Parse query results.
for query.Next() {
	err := query.Scan(destination...)
	if err != nil {
		log.Fatal(err) // Bombing out here.
	}
}
```

**Comment by denisenkom** [comment]
I think you should scan DATETIME into time.Time and then convert it into some binary format of your choosing.
